<?php
require_once(dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'init.inc.php');

$dboID = 'reassignment';
$dbo = DBO_init($dboID);
$dbo->id = $dboID;
$dbo->table = 'mjobsheet';
$dbo->key = array('js_id');
$dbo->sql = 'select * from mjobsheet
where js_Status = \'WORK IN PROGRESS\'';
$dbo->col = array('js_id', 'js_cuid', 'js_ctid', 'js_request_date', 'js_request_by', 'js_title', 'js_description', 'js_material_provided', 'js_cyan', 'js_magenta', 'js_yellow', 'js_black', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_color_5', 'js_angle_1', 'js_angle_2', 'js_angle_3', 'js_angle_4', 'js_angle_5', 'js_bleeding', 'js_bleeding_remark', 'js_carcode', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_thicknessplate', 'js_category', 'js_trapping_size', 'js_barcodetype', 'js_barcodenumber', 'js_primcat', 'js_status', 'js_completiondate', 'js_assignto', 'js_refid', 'attachment', 'remark', 'js_orgid', 'js_model', 'js_diecut_no', 'info', 'js_carid', 'jobcategory', 'js_decision', 'js_width', 'js_height', 'js_manrequiretime', 'js_requiretime', 'filehistory', 'js_request_dateinmth', 'js_jobcolor', 'joboutput', 'js_lpi', '__map_mjobbarcode__jbc_jsid__', '__map_mjobbarcode__jbc_value__', 'js_mcid', 'js_code', 'js_month_occur', 'js_price', 'pmc_id', 'js_outputtype', 'js_outputwidth', 'js_outputheight', 'js_qcchecked', 'js_currency', 'js_finalprice', 'js_rate', 'js_totalinch', 'js_color_6', 'js_color_7', 'js_color_8', 'js_cartonsize_g', 'js_cartonsize_l1', 'js_cartonsize_w2', 'js_cartonsize_l3', 'js_cartonsize_w4', 'js_cartonsize_height', 'js_cartonsize_top', 'js_cartonsize_bottom', 'js_expectdelivery', 'js_cancelremark', 'js_forwardtocusttime', 'js_color_9', 'js_custrejectreason');
$dbo->colList = array('js_request_by', 'js_request_date', 'js_outputtype', 'js_description', 'js_assignto');
$dbo->colListEdit = array();
$dbo->colListNew = array();
$dbo->colListGlobalInput = array();
$dbo->colDetail = array('js_description', 'joboutput', 'js_diecut_ind', 'js_cartonsize_l1', 'js_cartonsize_w2', 'js_cartonsize_height', 'js_carid', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_color_5', 'js_color_6', 'js_color_7', 'js_color_8', 'js_color_9', 'js_trapping_size', 'js_bleeding', 'js_bleeding_remark', 'js_lpi', 'js_distortion', 'js_distortion_value', 'js_outputtype', 'js_outputwidth', 'js_outputheight', '__map_mjobbarcode__jbc_jsid__', 'remark', 'attachment', 'info', 'js_expectdelivery', 'js_price', 'js_requiretime', 'js_qcchecked', 'js_custrejectreason', 'filehistory');
$dbo->colNew = array('js_request_by', 'js_request_date', 'js_outputtype', 'js_description', 'js_assignto');
$dbo->colEdit = array('js_request_by', 'js_request_date', 'js_outputtype', 'js_description', 'js_assignto');
$dbo->colSearch = array('js_id', 'js_mcid', 'js_request_date', 'js_request_by', 'js_title', 'js_description', 'js_material_provided', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_color_5', 'js_color_6', 'js_color_7', 'js_color_8', 'js_bleeding', 'js_bleeding_remark', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_trapping_size', 'js_primcat', 'js_status', 'js_completiondate', 'js_assignto');
$dbo->colExport = array('js_description', 'joboutput', 'js_diecut_ind', 'js_cartonsize_l1', 'js_cartonsize_w2', 'js_cartonsize_height', 'js_carid', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_color_5', 'js_color_6', 'js_color_7', 'js_color_8', 'js_color_9', 'js_trapping_size', 'js_bleeding', 'js_bleeding_remark', 'js_lpi', 'js_distortion', 'js_distortion_value', 'js_outputtype', 'js_outputwidth', 'js_outputheight', '__map_mjobbarcode__jbc_jsid__', 'remark', 'attachment', 'info', 'js_expectdelivery', 'js_price', 'js_requiretime');
$dbo->colSort = array();
$dbo->colSum = array();
$dbo->colSumPage = array();
$dbo->colAvg = array();
$dbo->colAvgPage = array();
$dbo->colGroupable = array();
$dbo->canSearch = false;
$dbo->canNew = false;
$dbo->canEdit = true;
$dbo->canDelete = false;
$dbo->canDetail = true;
$dbo->canListEdit = false;
$dbo->canListNew = false;
$dbo->canNewGroup = array();
$dbo->canEditGroup = array();
$dbo->canDeleteGroup = array();
$dbo->listNewDirection = 'auto';
$dbo->listEditToggle = false;
$dbo->showSearch = true;
$dbo->formAutocomplete = 'off';
$dbo->titleList = 'Job List';
$dbo->titleDetail = 'Job Detail';
$dbo->titleNew = 'New Job';
$dbo->titleEdit = 'Reassignment ';
$dbo->titleSearch = 'Search Job';
$dbo->layoutDetail = '3;
3;
3;
1|1|1;
3;
1|1|1;
1|1|1;
1|1|1;
1|1|1;
1|1|1;
1|1|1;
3;
3;
3;
3;
3;
3;
3;';
$dbo->layoutNew = '3;
3;
3;
1|1|1;
3;
1|1|1;
1|1|1;
1|1|1;
1|1|1;
1|1|1;
1|1|1;
3;
3;
3;
3;
3;
3;
3;';
$dbo->theme = 'pixeladmin';
$dbo->layout = 'One';
$dbo->pageLinkCount = '7';
$dbo->recordPerPage = '10';
$dbo->showRecordNo = true;
$dbo->defaultState = 'list';
$dbo->maxSortCount = '9';
$dbo->defaultDateFormat = 'yyyy-mm-dd';
$dbo->defaultDateTimeFormat = 'yyyy-mm-dd hh24:min:ss';
$dbo->defaultTimeFormat = 'hh24:min:ss';
$dbo->lang = 'EN-US';
$dbo->pdfEngine = 'dompdf';
$dbo->detailBack = 'Back';
$dbo->listEditSubmit = 'Submit';

$dbo->cols['js_id'] = new DBO_COL('js_id', 'int4', '4', '-1');
$dbo->cols['js_id']->searchMode = 'exact';
$dbo->cols['js_id']->exportUseLookup = true;
$dbo->cols['js_id']->inputTypeDefault = 'text';
$dbo->cols['js_id']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_id']->capContClassDefault = array();
$dbo->cols['js_id']->valContClassDefault = array();
$dbo->cols['js_id']->option->defaultMethod = 'text';
$dbo->cols['js_id']->option->searchMethod = 'text';
$dbo->cols['js_id']->option->listMethod = 'text';
$dbo->cols['js_id']->option->detailMethod = 'text';
$dbo->cols['js_id']->option->newMethod = 'text';
$dbo->cols['js_id']->option->editMethod = 'text';
$dbo->cols['js_cuid'] = new DBO_COL('js_cuid', 'int4', '4', '-1');
$dbo->cols['js_cuid']->searchMode = 'exact';
$dbo->cols['js_cuid']->exportUseLookup = true;
$dbo->cols['js_cuid']->inputTypeDefault = 'text';
$dbo->cols['js_cuid']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cuid']->capContClassDefault = array();
$dbo->cols['js_cuid']->valContClassDefault = array();
$dbo->cols['js_cuid']->option->default = 'select org_id, org_name from fcorg
order by org_name';
$dbo->cols['js_cuid']->option->defaultMethod = 'sql';
$dbo->cols['js_cuid']->option->searchMethod = 'text';
$dbo->cols['js_cuid']->option->listMethod = 'text';
$dbo->cols['js_cuid']->option->detailMethod = 'text';
$dbo->cols['js_cuid']->option->newMethod = 'text';
$dbo->cols['js_cuid']->option->editMethod = 'text';
$dbo->cols['js_ctid'] = new DBO_COL('js_ctid', 'int4', '4', '-1');
$dbo->cols['js_ctid']->searchMode = 'exact';
$dbo->cols['js_ctid']->exportUseLookup = true;
$dbo->cols['js_ctid']->inputTypeDefault = 'select';
$dbo->cols['js_ctid']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_ctid']->capContClassDefault = array();
$dbo->cols['js_ctid']->valContClassDefault = array();
$dbo->cols['js_ctid']->option->default = 'select ct_id,ct_name
from pndcontact';
$dbo->cols['js_ctid']->option->defaultMethod = 'sql';
$dbo->cols['js_ctid']->option->searchMethod = 'text';
$dbo->cols['js_ctid']->option->listMethod = 'text';
$dbo->cols['js_ctid']->option->detailMethod = 'text';
$dbo->cols['js_ctid']->option->newMethod = 'text';
$dbo->cols['js_ctid']->option->editMethod = 'text';
$dbo->cols['js_request_date'] = new DBO_COL('js_request_date', 'timestamptz', '8', '-1');
$dbo->cols['js_request_date']->displayDataType = 'datetime';
$dbo->cols['js_request_date']->searchMode = 'exact';
$dbo->cols['js_request_date']->exportUseLookup = true;
$dbo->cols['js_request_date']->inputTypeDefault = 'text';
$dbo->cols['js_request_date']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_request_date']->attributeDefault = array('readonly'=>array(''));
$dbo->cols['js_request_date']->capContClassDefault = array();
$dbo->cols['js_request_date']->valContClassDefault = array();
$dbo->cols['js_request_date']->option->defaultMethod = 'text';
$dbo->cols['js_request_date']->option->searchMethod = 'text';
$dbo->cols['js_request_date']->option->listMethod = 'text';
$dbo->cols['js_request_date']->option->detailMethod = 'text';
$dbo->cols['js_request_date']->option->newMethod = 'text';
$dbo->cols['js_request_date']->option->editMethod = 'text';
$dbo->cols['js_request_by'] = new DBO_COL('js_request_by', 'varchar', '-1', '104');
$dbo->cols['js_request_by']->searchMode = 'exact';
$dbo->cols['js_request_by']->exportUseLookup = true;
$dbo->cols['js_request_by']->inputTypeDefault = 'text';
$dbo->cols['js_request_by']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_request_by']->attributeDefault = array('readonly'=>array(''));
$dbo->cols['js_request_by']->capContClassDefault = array();
$dbo->cols['js_request_by']->valContClassDefault = array();
$dbo->cols['js_request_by']->option->default = 'select usr_userid,usr_name from fcuser';
$dbo->cols['js_request_by']->option->defaultMethod = 'sql';
$dbo->cols['js_request_by']->option->searchMethod = 'text';
$dbo->cols['js_request_by']->option->listMethod = 'text';
$dbo->cols['js_request_by']->option->detailMethod = 'text';
$dbo->cols['js_request_by']->option->newMethod = 'text';
$dbo->cols['js_request_by']->option->editMethod = 'text';
$dbo->cols['js_title'] = new DBO_COL('js_title', 'varchar', '-1', '104');
$dbo->cols['js_title']->searchMode = 'exact';
$dbo->cols['js_title']->exportUseLookup = true;
$dbo->cols['js_title']->inputTypeDefault = 'text';
$dbo->cols['js_title']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_title']->capContClassDefault = array();
$dbo->cols['js_title']->valContClassDefault = array();
$dbo->cols['js_title']->option->defaultMethod = 'text';
$dbo->cols['js_title']->option->searchMethod = 'text';
$dbo->cols['js_title']->option->listMethod = 'text';
$dbo->cols['js_title']->option->detailMethod = 'text';
$dbo->cols['js_title']->option->newMethod = 'text';
$dbo->cols['js_title']->option->editMethod = 'text';
$dbo->cols['js_description'] = new DBO_COL('js_description', 'text', '-1', '-1');
$dbo->cols['js_description']->searchMode = 'exact';
$dbo->cols['js_description']->exportUseLookup = true;
$dbo->cols['js_description']->inputTypeDefault = 'text';
$dbo->cols['js_description']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_description']->attributeDefault = array('readonly'=>array(''));
$dbo->cols['js_description']->mandatoryDefault = '1';
$dbo->cols['js_description']->capContClassDefault = array();
$dbo->cols['js_description']->valContClassDefault = array();
$dbo->cols['js_description']->option->defaultMethod = 'text';
$dbo->cols['js_description']->option->searchMethod = 'text';
$dbo->cols['js_description']->option->listMethod = 'text';
$dbo->cols['js_description']->option->detailMethod = 'text';
$dbo->cols['js_description']->option->newMethod = 'text';
$dbo->cols['js_description']->option->editMethod = 'text';
$dbo->cols['js_material_provided'] = new DBO_COL('js_material_provided', 'varchar', '-1', '104');
$dbo->cols['js_material_provided']->searchMode = 'exact';
$dbo->cols['js_material_provided']->exportUseLookup = true;
$dbo->cols['js_material_provided']->inputTypeDefault = 'text';
$dbo->cols['js_material_provided']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_material_provided']->capContClassDefault = array();
$dbo->cols['js_material_provided']->valContClassDefault = array();
$dbo->cols['js_material_provided']->option->defaultMethod = 'text';
$dbo->cols['js_material_provided']->option->searchMethod = 'text';
$dbo->cols['js_material_provided']->option->listMethod = 'text';
$dbo->cols['js_material_provided']->option->detailMethod = 'text';
$dbo->cols['js_material_provided']->option->newMethod = 'text';
$dbo->cols['js_material_provided']->option->editMethod = 'text';
$dbo->cols['js_cyan'] = new DBO_COL('js_cyan', 'varchar', '-1', '16');
$dbo->cols['js_cyan']->searchMode = 'exact';
$dbo->cols['js_cyan']->exportUseLookup = true;
$dbo->cols['js_cyan']->inputTypeDefault = 'checkbox';
$dbo->cols['js_cyan']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cyan']->capContClassDefault = array();
$dbo->cols['js_cyan']->valContClassDefault = array();
$dbo->cols['js_cyan']->option->default = 'Y';
$dbo->cols['js_cyan']->option->defaultMethod = 'text';
$dbo->cols['js_cyan']->option->searchMethod = 'text';
$dbo->cols['js_cyan']->option->listMethod = 'text';
$dbo->cols['js_cyan']->option->detailMethod = 'text';
$dbo->cols['js_cyan']->option->newMethod = 'text';
$dbo->cols['js_cyan']->option->editMethod = 'text';
$dbo->cols['js_magenta'] = new DBO_COL('js_magenta', 'varchar', '-1', '16');
$dbo->cols['js_magenta']->searchMode = 'exact';
$dbo->cols['js_magenta']->exportUseLookup = true;
$dbo->cols['js_magenta']->inputTypeDefault = 'checkbox';
$dbo->cols['js_magenta']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_magenta']->capContClassDefault = array();
$dbo->cols['js_magenta']->valContClassDefault = array();
$dbo->cols['js_magenta']->option->default = 'Y';
$dbo->cols['js_magenta']->option->defaultMethod = 'text';
$dbo->cols['js_magenta']->option->searchMethod = 'text';
$dbo->cols['js_magenta']->option->listMethod = 'text';
$dbo->cols['js_magenta']->option->detailMethod = 'text';
$dbo->cols['js_magenta']->option->newMethod = 'text';
$dbo->cols['js_magenta']->option->editMethod = 'text';
$dbo->cols['js_yellow'] = new DBO_COL('js_yellow', 'varchar', '-1', '16');
$dbo->cols['js_yellow']->searchMode = 'exact';
$dbo->cols['js_yellow']->exportUseLookup = true;
$dbo->cols['js_yellow']->inputTypeDefault = 'checkbox';
$dbo->cols['js_yellow']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_yellow']->capContClassDefault = array();
$dbo->cols['js_yellow']->valContClassDefault = array();
$dbo->cols['js_yellow']->option->default = 'Y';
$dbo->cols['js_yellow']->option->defaultMethod = 'text';
$dbo->cols['js_yellow']->option->searchMethod = 'text';
$dbo->cols['js_yellow']->option->listMethod = 'text';
$dbo->cols['js_yellow']->option->detailMethod = 'text';
$dbo->cols['js_yellow']->option->newMethod = 'text';
$dbo->cols['js_yellow']->option->editMethod = 'text';
$dbo->cols['js_black'] = new DBO_COL('js_black', 'varchar', '-1', '16');
$dbo->cols['js_black']->searchMode = 'exact';
$dbo->cols['js_black']->exportUseLookup = true;
$dbo->cols['js_black']->inputTypeDefault = 'checkbox';
$dbo->cols['js_black']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_black']->capContClassDefault = array();
$dbo->cols['js_black']->valContClassDefault = array();
$dbo->cols['js_black']->option->default = 'Y';
$dbo->cols['js_black']->option->defaultMethod = 'text';
$dbo->cols['js_black']->option->searchMethod = 'text';
$dbo->cols['js_black']->option->listMethod = 'text';
$dbo->cols['js_black']->option->detailMethod = 'text';
$dbo->cols['js_black']->option->newMethod = 'text';
$dbo->cols['js_black']->option->editMethod = 'text';
$dbo->cols['js_color_1'] = new DBO_COL('js_color_1', 'varchar', '-1', '16');
$dbo->cols['js_color_1']->searchMode = 'exact';
$dbo->cols['js_color_1']->exportUseLookup = true;
$dbo->cols['js_color_1']->inputTypeDefault = 'text';
$dbo->cols['js_color_1']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_1']->capContClassDefault = array();
$dbo->cols['js_color_1']->valContClassDefault = array();
$dbo->cols['js_color_1']->option->default = 'select lu_code, lu_title from fclookup where lu_cat = \'JOBCOLOR\' order by 2';
$dbo->cols['js_color_1']->option->defaultMethod = 'sql';
$dbo->cols['js_color_1']->option->searchMethod = 'text';
$dbo->cols['js_color_1']->option->listMethod = 'text';
$dbo->cols['js_color_1']->option->detailMethod = 'text';
$dbo->cols['js_color_1']->option->newMethod = 'text';
$dbo->cols['js_color_1']->option->editMethod = 'text';
$dbo->cols['js_color_2'] = new DBO_COL('js_color_2', 'varchar', '-1', '16');
$dbo->cols['js_color_2']->searchMode = 'exact';
$dbo->cols['js_color_2']->exportUseLookup = true;
$dbo->cols['js_color_2']->inputTypeDefault = 'text';
$dbo->cols['js_color_2']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_2']->capContClassDefault = array();
$dbo->cols['js_color_2']->valContClassDefault = array();
$dbo->cols['js_color_2']->option->default = 'select lu_code, lu_title from fclookup where lu_cat = \'JOBCOLOR\' order by 2';
$dbo->cols['js_color_2']->option->defaultMethod = 'sql';
$dbo->cols['js_color_2']->option->searchMethod = 'text';
$dbo->cols['js_color_2']->option->listMethod = 'text';
$dbo->cols['js_color_2']->option->detailMethod = 'text';
$dbo->cols['js_color_2']->option->newMethod = 'text';
$dbo->cols['js_color_2']->option->editMethod = 'text';
$dbo->cols['js_color_3'] = new DBO_COL('js_color_3', 'varchar', '-1', '16');
$dbo->cols['js_color_3']->searchMode = 'exact';
$dbo->cols['js_color_3']->exportUseLookup = true;
$dbo->cols['js_color_3']->inputTypeDefault = 'text';
$dbo->cols['js_color_3']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_3']->capContClassDefault = array();
$dbo->cols['js_color_3']->valContClassDefault = array();
$dbo->cols['js_color_3']->option->default = 'select lu_code, lu_title from fclookup where lu_cat = \'JOBCOLOR\' order by 2';
$dbo->cols['js_color_3']->option->defaultMethod = 'sql';
$dbo->cols['js_color_3']->option->searchMethod = 'text';
$dbo->cols['js_color_3']->option->listMethod = 'text';
$dbo->cols['js_color_3']->option->detailMethod = 'text';
$dbo->cols['js_color_3']->option->newMethod = 'text';
$dbo->cols['js_color_3']->option->editMethod = 'text';
$dbo->cols['js_color_4'] = new DBO_COL('js_color_4', 'varchar', '-1', '16');
$dbo->cols['js_color_4']->searchMode = 'exact';
$dbo->cols['js_color_4']->exportUseLookup = true;
$dbo->cols['js_color_4']->inputTypeDefault = 'text';
$dbo->cols['js_color_4']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_4']->capContClassDefault = array();
$dbo->cols['js_color_4']->valContClassDefault = array();
$dbo->cols['js_color_4']->option->default = 'select lu_code, lu_title from fclookup where lu_cat = \'JOBCOLOR\' order by 2';
$dbo->cols['js_color_4']->option->defaultMethod = 'sql';
$dbo->cols['js_color_4']->option->searchMethod = 'text';
$dbo->cols['js_color_4']->option->listMethod = 'text';
$dbo->cols['js_color_4']->option->detailMethod = 'text';
$dbo->cols['js_color_4']->option->newMethod = 'text';
$dbo->cols['js_color_4']->option->editMethod = 'text';
$dbo->cols['js_color_5'] = new DBO_COL('js_color_5', 'varchar', '-1', '16');
$dbo->cols['js_color_5']->searchMode = 'exact';
$dbo->cols['js_color_5']->exportUseLookup = true;
$dbo->cols['js_color_5']->inputTypeDefault = 'text';
$dbo->cols['js_color_5']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_5']->capContClassDefault = array();
$dbo->cols['js_color_5']->valContClassDefault = array();
$dbo->cols['js_color_5']->option->default = 'select lu_code, lu_title from fclookup where lu_cat = \'JOBCOLOR\' order by 2';
$dbo->cols['js_color_5']->option->defaultMethod = 'sql';
$dbo->cols['js_color_5']->option->searchMethod = 'text';
$dbo->cols['js_color_5']->option->listMethod = 'text';
$dbo->cols['js_color_5']->option->detailMethod = 'text';
$dbo->cols['js_color_5']->option->newMethod = 'text';
$dbo->cols['js_color_5']->option->editMethod = 'text';
$dbo->cols['js_angle_1'] = new DBO_COL('js_angle_1', 'varchar', '-1', '16');
$dbo->cols['js_angle_1']->searchMode = 'exact';
$dbo->cols['js_angle_1']->exportUseLookup = true;
$dbo->cols['js_angle_1']->inputTypeDefault = 'text';
$dbo->cols['js_angle_1']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_angle_1']->capContClassDefault = array();
$dbo->cols['js_angle_1']->valContClassDefault = array();
$dbo->cols['js_angle_1']->option->defaultMethod = 'text';
$dbo->cols['js_angle_1']->option->searchMethod = 'text';
$dbo->cols['js_angle_1']->option->listMethod = 'text';
$dbo->cols['js_angle_1']->option->detailMethod = 'text';
$dbo->cols['js_angle_1']->option->newMethod = 'text';
$dbo->cols['js_angle_1']->option->editMethod = 'text';
$dbo->cols['js_angle_2'] = new DBO_COL('js_angle_2', 'varchar', '-1', '16');
$dbo->cols['js_angle_2']->searchMode = 'exact';
$dbo->cols['js_angle_2']->exportUseLookup = true;
$dbo->cols['js_angle_2']->inputTypeDefault = 'text';
$dbo->cols['js_angle_2']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_angle_2']->capContClassDefault = array();
$dbo->cols['js_angle_2']->valContClassDefault = array();
$dbo->cols['js_angle_2']->option->defaultMethod = 'text';
$dbo->cols['js_angle_2']->option->searchMethod = 'text';
$dbo->cols['js_angle_2']->option->listMethod = 'text';
$dbo->cols['js_angle_2']->option->detailMethod = 'text';
$dbo->cols['js_angle_2']->option->newMethod = 'text';
$dbo->cols['js_angle_2']->option->editMethod = 'text';
$dbo->cols['js_angle_3'] = new DBO_COL('js_angle_3', 'varchar', '-1', '16');
$dbo->cols['js_angle_3']->searchMode = 'exact';
$dbo->cols['js_angle_3']->exportUseLookup = true;
$dbo->cols['js_angle_3']->inputTypeDefault = 'text';
$dbo->cols['js_angle_3']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_angle_3']->capContClassDefault = array();
$dbo->cols['js_angle_3']->valContClassDefault = array();
$dbo->cols['js_angle_3']->option->defaultMethod = 'text';
$dbo->cols['js_angle_3']->option->searchMethod = 'text';
$dbo->cols['js_angle_3']->option->listMethod = 'text';
$dbo->cols['js_angle_3']->option->detailMethod = 'text';
$dbo->cols['js_angle_3']->option->newMethod = 'text';
$dbo->cols['js_angle_3']->option->editMethod = 'text';
$dbo->cols['js_angle_4'] = new DBO_COL('js_angle_4', 'varchar', '-1', '16');
$dbo->cols['js_angle_4']->searchMode = 'exact';
$dbo->cols['js_angle_4']->exportUseLookup = true;
$dbo->cols['js_angle_4']->inputTypeDefault = 'text';
$dbo->cols['js_angle_4']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_angle_4']->capContClassDefault = array();
$dbo->cols['js_angle_4']->valContClassDefault = array();
$dbo->cols['js_angle_4']->option->defaultMethod = 'text';
$dbo->cols['js_angle_4']->option->searchMethod = 'text';
$dbo->cols['js_angle_4']->option->listMethod = 'text';
$dbo->cols['js_angle_4']->option->detailMethod = 'text';
$dbo->cols['js_angle_4']->option->newMethod = 'text';
$dbo->cols['js_angle_4']->option->editMethod = 'text';
$dbo->cols['js_angle_5'] = new DBO_COL('js_angle_5', 'varchar', '-1', '16');
$dbo->cols['js_angle_5']->searchMode = 'exact';
$dbo->cols['js_angle_5']->exportUseLookup = true;
$dbo->cols['js_angle_5']->inputTypeDefault = 'text';
$dbo->cols['js_angle_5']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_angle_5']->capContClassDefault = array();
$dbo->cols['js_angle_5']->valContClassDefault = array();
$dbo->cols['js_angle_5']->option->defaultMethod = 'text';
$dbo->cols['js_angle_5']->option->searchMethod = 'text';
$dbo->cols['js_angle_5']->option->listMethod = 'text';
$dbo->cols['js_angle_5']->option->detailMethod = 'text';
$dbo->cols['js_angle_5']->option->newMethod = 'text';
$dbo->cols['js_angle_5']->option->editMethod = 'text';
$dbo->cols['js_bleeding'] = new DBO_COL('js_bleeding', 'varchar', '-1', '16');
$dbo->cols['js_bleeding']->searchMode = 'exact';
$dbo->cols['js_bleeding']->exportUseLookup = true;
$dbo->cols['js_bleeding']->inputTypeDefault = 'select';
$dbo->cols['js_bleeding']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_bleeding']->capContClassDefault = array();
$dbo->cols['js_bleeding']->valContClassDefault = array();
$dbo->cols['js_bleeding']->option->default = '0
3
5
7
10
15';
$dbo->cols['js_bleeding']->option->defaultMethod = 'text';
$dbo->cols['js_bleeding']->option->searchMethod = 'text';
$dbo->cols['js_bleeding']->option->listMethod = 'text';
$dbo->cols['js_bleeding']->option->detailMethod = 'text';
$dbo->cols['js_bleeding']->option->newMethod = 'text';
$dbo->cols['js_bleeding']->option->editMethod = 'text';
$dbo->cols['js_bleeding_remark'] = new DBO_COL('js_bleeding_remark', 'varchar', '-1', '1004');
$dbo->cols['js_bleeding_remark']->searchMode = 'exact';
$dbo->cols['js_bleeding_remark']->exportUseLookup = true;
$dbo->cols['js_bleeding_remark']->inputTypeDefault = 'TextareaAutosize';
$dbo->cols['js_bleeding_remark']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_bleeding_remark']->capContClassDefault = array();
$dbo->cols['js_bleeding_remark']->valContClassDefault = array();
$dbo->cols['js_bleeding_remark']->option->defaultMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->searchMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->listMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->detailMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->newMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->editMethod = 'text';
$dbo->cols['js_carcode'] = new DBO_COL('js_carcode', 'varchar', '-1', '16');
$dbo->cols['js_carcode']->searchMode = 'exact';
$dbo->cols['js_carcode']->exportUseLookup = true;
$dbo->cols['js_carcode']->inputTypeDefault = 'select';
$dbo->cols['js_carcode']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_carcode']->capContClassDefault = array();
$dbo->cols['js_carcode']->valContClassDefault = array();
$dbo->cols['js_carcode']->option->default = 'select car_id,car_name from mcarton
order by car_name';
$dbo->cols['js_carcode']->option->defaultMethod = 'sql';
$dbo->cols['js_carcode']->option->searchMethod = 'text';
$dbo->cols['js_carcode']->option->listMethod = 'text';
$dbo->cols['js_carcode']->option->detailMethod = 'text';
$dbo->cols['js_carcode']->option->newMethod = 'text';
$dbo->cols['js_carcode']->option->editMethod = 'text';
$dbo->cols['js_distortion'] = new DBO_COL('js_distortion', 'varchar', '-1', '5');
$dbo->cols['js_distortion']->searchMode = 'exact';
$dbo->cols['js_distortion']->exportUseLookup = true;
$dbo->cols['js_distortion']->inputTypeDefault = 'select';
$dbo->cols['js_distortion']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_distortion']->capContClassDefault = array();
$dbo->cols['js_distortion']->valContClassDefault = array();
$dbo->cols['js_distortion']->option->default = 'H|Horizontal 
V|Vertical ';
$dbo->cols['js_distortion']->option->defaultMethod = 'text';
$dbo->cols['js_distortion']->option->searchMethod = 'text';
$dbo->cols['js_distortion']->option->listMethod = 'text';
$dbo->cols['js_distortion']->option->detailMethod = 'text';
$dbo->cols['js_distortion']->option->newMethod = 'text';
$dbo->cols['js_distortion']->option->editMethod = 'text';
$dbo->cols['js_distortion_value'] = new DBO_COL('js_distortion_value', 'numeric', '-1', '1310728');
$dbo->cols['js_distortion_value']->displayDataType = 'currency';
$dbo->cols['js_distortion_value']->searchMode = 'exact';
$dbo->cols['js_distortion_value']->exportUseLookup = true;
$dbo->cols['js_distortion_value']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['js_distortion_value']->displayDetailModifier = 'showPercentageDet';
$dbo->cols['js_distortion_value']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_distortion_value']->inputNewModifier = 'showPercentage';
$dbo->cols['js_distortion_value']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_distortion_value']->inputEditModifier = 'showPercentage';
$dbo->cols['js_distortion_value']->inputTypeDefault = 'TextInputControl';
$dbo->cols['js_distortion_value']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_distortion_value']->capContClassDefault = array();
$dbo->cols['js_distortion_value']->valContClassDefault = array();
$dbo->cols['js_distortion_value']->valContExtClassDefault = 'input-group';
$dbo->cols['js_distortion_value']->option->defaultMethod = 'text';
$dbo->cols['js_distortion_value']->option->searchMethod = 'text';
$dbo->cols['js_distortion_value']->option->listMethod = 'text';
$dbo->cols['js_distortion_value']->option->detailMethod = 'text';
$dbo->cols['js_distortion_value']->option->newMethod = 'text';
$dbo->cols['js_distortion_value']->option->editMethod = 'text';
$dbo->cols['js_diecut_ind'] = new DBO_COL('js_diecut_ind', 'varchar', '-1', '54');
$dbo->cols['js_diecut_ind']->searchMode = 'exact';
$dbo->cols['js_diecut_ind']->exportUseLookup = true;
$dbo->cols['js_diecut_ind']->inputTypeDefault = 'PixelAdminRadioInline';
$dbo->cols['js_diecut_ind']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_diecut_ind']->capContClassDefault = array();
$dbo->cols['js_diecut_ind']->valContClassDefault = array();
$dbo->cols['js_diecut_ind']->option->default = 'select car_id,car_name from mcarton  
order by car_seq';
$dbo->cols['js_diecut_ind']->option->defaultMethod = 'sql';
$dbo->cols['js_diecut_ind']->option->searchMethod = 'text';
$dbo->cols['js_diecut_ind']->option->listMethod = 'text';
$dbo->cols['js_diecut_ind']->option->detailMethod = 'text';
$dbo->cols['js_diecut_ind']->option->newMethod = 'text';
$dbo->cols['js_diecut_ind']->option->editMethod = 'text';
$dbo->cols['js_thicknessplate'] = new DBO_COL('js_thicknessplate', 'varchar', '-1', '104');
$dbo->cols['js_thicknessplate']->searchMode = 'exact';
$dbo->cols['js_thicknessplate']->exportUseLookup = true;
$dbo->cols['js_thicknessplate']->inputTypeDefault = 'text';
$dbo->cols['js_thicknessplate']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_thicknessplate']->capContClassDefault = array();
$dbo->cols['js_thicknessplate']->valContClassDefault = array();
$dbo->cols['js_thicknessplate']->option->defaultMethod = 'text';
$dbo->cols['js_thicknessplate']->option->searchMethod = 'text';
$dbo->cols['js_thicknessplate']->option->listMethod = 'text';
$dbo->cols['js_thicknessplate']->option->detailMethod = 'text';
$dbo->cols['js_thicknessplate']->option->newMethod = 'text';
$dbo->cols['js_thicknessplate']->option->editMethod = 'text';
$dbo->cols['js_category'] = new DBO_COL('js_category', 'varchar', '-1', '504');
$dbo->cols['js_category']->searchMode = 'exact';
$dbo->cols['js_category']->exportUseLookup = true;
$dbo->cols['js_category']->inputTypeDefault = 'checkbox';
$dbo->cols['js_category']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_category']->capContClassDefault = array();
$dbo->cols['js_category']->valContClassDefault = array();
$dbo->cols['js_category']->option->default = 'select jcl_id, jcl_title 
from mjobcatlookup
order by jcl_title';
$dbo->cols['js_category']->option->defaultMethod = 'sql';
$dbo->cols['js_category']->option->searchMethod = 'text';
$dbo->cols['js_category']->option->listMethod = 'text';
$dbo->cols['js_category']->option->detailMethod = 'text';
$dbo->cols['js_category']->option->newMethod = 'text';
$dbo->cols['js_category']->option->editMethod = 'text';
$dbo->cols['js_trapping_size'] = new DBO_COL('js_trapping_size', 'numeric', '-1', '1310728');
$dbo->cols['js_trapping_size']->displayDataType = 'currency';
$dbo->cols['js_trapping_size']->searchMode = 'exact';
$dbo->cols['js_trapping_size']->exportUseLookup = true;
$dbo->cols['js_trapping_size']->inputTypeDefault = 'TextInputControl';
$dbo->cols['js_trapping_size']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_trapping_size']->capContClassDefault = array();
$dbo->cols['js_trapping_size']->valContClassDefault = array();
$dbo->cols['js_trapping_size']->valContExtClassDefault = 'form-group';
$dbo->cols['js_trapping_size']->option->defaultMethod = 'text';
$dbo->cols['js_trapping_size']->option->searchMethod = 'text';
$dbo->cols['js_trapping_size']->option->listMethod = 'text';
$dbo->cols['js_trapping_size']->option->detailMethod = 'text';
$dbo->cols['js_trapping_size']->option->newMethod = 'text';
$dbo->cols['js_trapping_size']->option->editMethod = 'text';
$dbo->cols['js_barcodetype'] = new DBO_COL('js_barcodetype', 'varchar', '-1', '54');
$dbo->cols['js_barcodetype']->searchMode = 'exact';
$dbo->cols['js_barcodetype']->exportUseLookup = true;
$dbo->cols['js_barcodetype']->inputTypeDefault = 'select';
$dbo->cols['js_barcodetype']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_barcodetype']->capContClassDefault = array();
$dbo->cols['js_barcodetype']->valContClassDefault = array();
$dbo->cols['js_barcodetype']->option->default = 'select lu_code,lu_title from fclookup
where lu_cat = \'BARCODETYPE\'
order by lu_title';
$dbo->cols['js_barcodetype']->option->defaultMethod = 'sql';
$dbo->cols['js_barcodetype']->option->searchMethod = 'text';
$dbo->cols['js_barcodetype']->option->listMethod = 'text';
$dbo->cols['js_barcodetype']->option->detailMethod = 'text';
$dbo->cols['js_barcodetype']->option->newMethod = 'text';
$dbo->cols['js_barcodetype']->option->editMethod = 'text';
$dbo->cols['js_barcodenumber'] = new DBO_COL('js_barcodenumber', 'varchar', '-1', '104');
$dbo->cols['js_barcodenumber']->searchMode = 'exact';
$dbo->cols['js_barcodenumber']->exportUseLookup = true;
$dbo->cols['js_barcodenumber']->inputTypeDefault = 'text';
$dbo->cols['js_barcodenumber']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_barcodenumber']->capContClassDefault = array();
$dbo->cols['js_barcodenumber']->valContClassDefault = array();
$dbo->cols['js_barcodenumber']->option->defaultMethod = 'text';
$dbo->cols['js_barcodenumber']->option->searchMethod = 'text';
$dbo->cols['js_barcodenumber']->option->listMethod = 'text';
$dbo->cols['js_barcodenumber']->option->detailMethod = 'text';
$dbo->cols['js_barcodenumber']->option->newMethod = 'text';
$dbo->cols['js_barcodenumber']->option->editMethod = 'text';
$dbo->cols['js_primcat'] = new DBO_COL('js_primcat', 'int4', '4', '-1');
$dbo->cols['js_primcat']->searchMode = 'exact';
$dbo->cols['js_primcat']->exportUseLookup = true;
$dbo->cols['js_primcat']->inputTypeDefault = 'text';
$dbo->cols['js_primcat']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_primcat']->capContClassDefault = array();
$dbo->cols['js_primcat']->valContClassDefault = array();
$dbo->cols['js_primcat']->option->default = 'select jcl_id, jcl_title 
from mjobcatlookup
order by jcl_title';
$dbo->cols['js_primcat']->option->defaultMethod = 'sql';
$dbo->cols['js_primcat']->option->searchMethod = 'text';
$dbo->cols['js_primcat']->option->listMethod = 'text';
$dbo->cols['js_primcat']->option->detailMethod = 'text';
$dbo->cols['js_primcat']->option->newMethod = 'text';
$dbo->cols['js_primcat']->option->editMethod = 'text';
$dbo->cols['js_status'] = new DBO_COL('js_status', 'varchar', '-1', '104');
$dbo->cols['js_status']->searchMode = 'exact';
$dbo->cols['js_status']->exportUseLookup = true;
$dbo->cols['js_status']->inputTypeDefault = 'text';
$dbo->cols['js_status']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_status']->capContClassDefault = array();
$dbo->cols['js_status']->valContClassDefault = array();
$dbo->cols['js_status']->option->defaultMethod = 'text';
$dbo->cols['js_status']->option->searchMethod = 'text';
$dbo->cols['js_status']->option->listMethod = 'text';
$dbo->cols['js_status']->option->detailMethod = 'text';
$dbo->cols['js_status']->option->newMethod = 'text';
$dbo->cols['js_status']->option->editMethod = 'text';
$dbo->cols['js_completiondate'] = new DBO_COL('js_completiondate', 'timestamptz', '8', '-1');
$dbo->cols['js_completiondate']->searchMode = 'exact';
$dbo->cols['js_completiondate']->exportUseLookup = true;
$dbo->cols['js_completiondate']->inputTypeDefault = 'text';
$dbo->cols['js_completiondate']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_completiondate']->capContClassDefault = array();
$dbo->cols['js_completiondate']->valContClassDefault = array();
$dbo->cols['js_completiondate']->option->defaultMethod = 'text';
$dbo->cols['js_completiondate']->option->searchMethod = 'text';
$dbo->cols['js_completiondate']->option->listMethod = 'text';
$dbo->cols['js_completiondate']->option->detailMethod = 'text';
$dbo->cols['js_completiondate']->option->newMethod = 'text';
$dbo->cols['js_completiondate']->option->editMethod = 'text';
$dbo->cols['js_assignto'] = new DBO_COL('js_assignto', 'varchar', '-1', '54');
$dbo->cols['js_assignto']->searchMode = 'exact';
$dbo->cols['js_assignto']->exportUseLookup = true;
$dbo->cols['js_assignto']->inputTypeDefault = 'select';
$dbo->cols['js_assignto']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_assignto']->capContClassDefault = array();
$dbo->cols['js_assignto']->valContClassDefault = array();
$dbo->cols['js_assignto']->option->default = 'select usr_userid,usr_name
from fcuser 
join fcuserorgrole on usr_userid = uor_usrid 
join fcrole on uor_rolid = rol_id
where lower(rol_name) = \'artist\'';
$dbo->cols['js_assignto']->option->defaultMethod = 'sql';
$dbo->cols['js_assignto']->option->searchMethod = 'text';
$dbo->cols['js_assignto']->option->listMethod = 'text';
$dbo->cols['js_assignto']->option->detailMethod = 'text';
$dbo->cols['js_assignto']->option->newMethod = 'text';
$dbo->cols['js_assignto']->option->editMethod = 'text';
$dbo->cols['js_refid'] = new DBO_COL('js_refid', 'int4', '4', '-1');
$dbo->cols['js_refid']->searchMode = 'exact';
$dbo->cols['js_refid']->exportUseLookup = true;
$dbo->cols['js_refid']->inputTypeDefault = 'text';
$dbo->cols['js_refid']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_refid']->capContClassDefault = array();
$dbo->cols['js_refid']->valContClassDefault = array();
$dbo->cols['js_refid']->option->defaultMethod = 'text';
$dbo->cols['js_refid']->option->searchMethod = 'text';
$dbo->cols['js_refid']->option->listMethod = 'text';
$dbo->cols['js_refid']->option->detailMethod = 'text';
$dbo->cols['js_refid']->option->newMethod = 'text';
$dbo->cols['js_refid']->option->editMethod = 'text';
$dbo->cols['attachment'] = new DBO_COL('attachment', 'unknown', '-2', '-1');
$dbo->cols['attachment']->searchMode = 'exact';
$dbo->cols['attachment']->exportUseLookup = true;
$dbo->cols['attachment']->size = '300M/5';
$dbo->cols['attachment']->format = '.zip, .rar';
$dbo->cols['attachment']->inputTypeDefault = 'Dropzone';
$dbo->cols['attachment']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['attachment']->mandatoryNew = '1';
$dbo->cols['attachment']->capContClassDefault = array();
$dbo->cols['attachment']->valContClassDefault = array();
$dbo->cols['attachment']->option->defaultMethod = 'text';
$dbo->cols['attachment']->option->searchMethod = 'text';
$dbo->cols['attachment']->option->listMethod = 'text';
$dbo->cols['attachment']->option->detailMethod = 'text';
$dbo->cols['attachment']->option->newMethod = 'text';
$dbo->cols['attachment']->option->editMethod = 'text';
$dbo->cols['remark'] = new DBO_COL('remark', 'unknown', '-2', '-1');
$dbo->cols['remark']->searchMode = 'exact';
$dbo->cols['remark']->exportUseLookup = true;
$dbo->cols['remark']->size = '3';
$dbo->cols['remark']->inputTypeDefault = 'TextareaAutosize';
$dbo->cols['remark']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['remark']->capContClassDefault = array();
$dbo->cols['remark']->valContClassDefault = array();
$dbo->cols['remark']->option->defaultMethod = 'text';
$dbo->cols['remark']->option->searchMethod = 'text';
$dbo->cols['remark']->option->listMethod = 'text';
$dbo->cols['remark']->option->detailMethod = 'text';
$dbo->cols['remark']->option->newMethod = 'text';
$dbo->cols['remark']->option->editMethod = 'text';
$dbo->cols['js_orgid'] = new DBO_COL('js_orgid', 'int4', '4', '-1');
$dbo->cols['js_orgid']->searchMode = 'exact';
$dbo->cols['js_orgid']->exportUseLookup = true;
$dbo->cols['js_orgid']->inputTypeDefault = 'select';
$dbo->cols['js_orgid']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_orgid']->capContClassDefault = array();
$dbo->cols['js_orgid']->valContClassDefault = array();
$dbo->cols['js_orgid']->option->defaultMethod = 'text';
$dbo->cols['js_orgid']->option->searchMethod = 'text';
$dbo->cols['js_orgid']->option->listMethod = 'text';
$dbo->cols['js_orgid']->option->detailMethod = 'text';
$dbo->cols['js_orgid']->option->newMethod = 'text';
$dbo->cols['js_orgid']->option->editMethod = 'text';
$dbo->cols['js_model'] = new DBO_COL('js_model', 'varchar', '-1', '2004');
$dbo->cols['js_model']->searchMode = 'exact';
$dbo->cols['js_model']->exportUseLookup = true;
$dbo->cols['js_model']->inputTypeDefault = 'text';
$dbo->cols['js_model']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_model']->capContClassDefault = array();
$dbo->cols['js_model']->valContClassDefault = array();
$dbo->cols['js_model']->option->defaultMethod = 'text';
$dbo->cols['js_model']->option->searchMethod = 'text';
$dbo->cols['js_model']->option->listMethod = 'text';
$dbo->cols['js_model']->option->detailMethod = 'text';
$dbo->cols['js_model']->option->newMethod = 'text';
$dbo->cols['js_model']->option->editMethod = 'text';
$dbo->cols['js_diecut_no'] = new DBO_COL('js_diecut_no', 'varchar', '-1', '104');
$dbo->cols['js_diecut_no']->searchMode = 'exact';
$dbo->cols['js_diecut_no']->exportUseLookup = true;
$dbo->cols['js_diecut_no']->inputTypeDefault = 'radio';
$dbo->cols['js_diecut_no']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_diecut_no']->capContClassDefault = array();
$dbo->cols['js_diecut_no']->valContClassDefault = array();
$dbo->cols['js_diecut_no']->option->defaultMethod = 'text';
$dbo->cols['js_diecut_no']->option->searchMethod = 'text';
$dbo->cols['js_diecut_no']->option->listMethod = 'text';
$dbo->cols['js_diecut_no']->option->detailMethod = 'text';
$dbo->cols['js_diecut_no']->option->newMethod = 'text';
$dbo->cols['js_diecut_no']->option->editMethod = 'text';
$dbo->cols['info'] = new DBO_COL('info', 'unknown', '-2', '-1');
$dbo->cols['info']->searchMode = 'exact';
$dbo->cols['info']->exportUseLookup = true;
$dbo->cols['info']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['info']->inputNewModifier = 'showinfo';
$dbo->cols['info']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['info']->inputEditModifier = 'showinfo';
$dbo->cols['info']->inputTypeDefault = 'text';
$dbo->cols['info']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['info']->capContClassDefault = array();
$dbo->cols['info']->valContClassDefault = array();
$dbo->cols['info']->option->defaultMethod = 'text';
$dbo->cols['info']->option->searchMethod = 'text';
$dbo->cols['info']->option->listMethod = 'text';
$dbo->cols['info']->option->detailMethod = 'text';
$dbo->cols['info']->option->newMethod = 'text';
$dbo->cols['info']->option->editMethod = 'text';
$dbo->cols['js_carid'] = new DBO_COL('js_carid', 'int4', '4', '-1');
$dbo->cols['js_carid']->searchMode = 'exact';
$dbo->cols['js_carid']->exportUseLookup = true;
$dbo->cols['js_carid']->inputTypeDefault = 'PixelAdminRadioInline';
$dbo->cols['js_carid']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_carid']->capContClassDefault = array();
$dbo->cols['js_carid']->valContClassDefault = array();
$dbo->cols['js_carid']->option->default = '1|Spot Color
2|CMYK';
$dbo->cols['js_carid']->option->defaultMethod = 'text';
$dbo->cols['js_carid']->option->searchMethod = 'text';
$dbo->cols['js_carid']->option->listMethod = 'text';
$dbo->cols['js_carid']->option->detailMethod = 'text';
$dbo->cols['js_carid']->option->newMethod = 'text';
$dbo->cols['js_carid']->option->editMethod = 'text';
$dbo->cols['jobcategory'] = new DBO_COL('jobcategory', 'varchar', '-1', '-1');
$dbo->cols['jobcategory']->searchMode = 'exact';
$dbo->cols['jobcategory']->exportUseLookup = true;
$dbo->cols['jobcategory']->inputTypeDefault = 'PixelAdminCheckboxInline';
$dbo->cols['jobcategory']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['jobcategory']->capContClassDefault = array();
$dbo->cols['jobcategory']->valContClassDefault = array();
$dbo->cols['jobcategory']->option->default = 'select jcl_id, jcl_title 
from mjobcatlookup
order by jcl_title';
$dbo->cols['jobcategory']->option->new = 'select jcl_id, jcl_title 
from mjobcatlookup where jcl_status = \'ACTIVE\'
order by jcl_title';
$dbo->cols['jobcategory']->option->edit = 'select jcl_id, jcl_title 
from mjobcatlookup where jcl_status = \'ACTIVE\'
order by jcl_title';
$dbo->cols['jobcategory']->option->defaultMethod = 'sql';
$dbo->cols['jobcategory']->option->searchMethod = 'text';
$dbo->cols['jobcategory']->option->listMethod = 'text';
$dbo->cols['jobcategory']->option->detailMethod = 'text';
$dbo->cols['jobcategory']->option->newMethod = 'sql';
$dbo->cols['jobcategory']->option->editMethod = 'sql';
$dbo->cols['js_decision'] = new DBO_COL('js_decision', 'varchar', '-1', '54');
$dbo->cols['js_decision']->searchMode = 'exact';
$dbo->cols['js_decision']->exportUseLookup = true;
$dbo->cols['js_decision']->inputTypeDefault = 'text';
$dbo->cols['js_decision']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_decision']->capContClassDefault = array();
$dbo->cols['js_decision']->valContClassDefault = array();
$dbo->cols['js_decision']->option->defaultMethod = 'text';
$dbo->cols['js_decision']->option->searchMethod = 'text';
$dbo->cols['js_decision']->option->listMethod = 'text';
$dbo->cols['js_decision']->option->detailMethod = 'text';
$dbo->cols['js_decision']->option->newMethod = 'text';
$dbo->cols['js_decision']->option->editMethod = 'text';
$dbo->cols['js_width'] = new DBO_COL('js_width', 'varchar', '-1', '54');
$dbo->cols['js_width']->searchMode = 'exact';
$dbo->cols['js_width']->exportUseLookup = true;
$dbo->cols['js_width']->inputTypeDefault = 'text';
$dbo->cols['js_width']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_width']->capContClassDefault = array();
$dbo->cols['js_width']->valContClassDefault = array();
$dbo->cols['js_width']->option->defaultMethod = 'text';
$dbo->cols['js_width']->option->searchMethod = 'text';
$dbo->cols['js_width']->option->listMethod = 'text';
$dbo->cols['js_width']->option->detailMethod = 'text';
$dbo->cols['js_width']->option->newMethod = 'text';
$dbo->cols['js_width']->option->editMethod = 'text';
$dbo->cols['js_height'] = new DBO_COL('js_height', 'varchar', '-1', '54');
$dbo->cols['js_height']->searchMode = 'exact';
$dbo->cols['js_height']->exportUseLookup = true;
$dbo->cols['js_height']->inputTypeDefault = 'text';
$dbo->cols['js_height']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_height']->capContClassDefault = array();
$dbo->cols['js_height']->valContClassDefault = array();
$dbo->cols['js_height']->option->defaultMethod = 'text';
$dbo->cols['js_height']->option->searchMethod = 'text';
$dbo->cols['js_height']->option->listMethod = 'text';
$dbo->cols['js_height']->option->detailMethod = 'text';
$dbo->cols['js_height']->option->newMethod = 'text';
$dbo->cols['js_height']->option->editMethod = 'text';
$dbo->cols['js_manrequiretime'] = new DBO_COL('js_manrequiretime', 'int4', '4', '-1');
$dbo->cols['js_manrequiretime']->searchMode = 'exact';
$dbo->cols['js_manrequiretime']->exportUseLookup = true;
$dbo->cols['js_manrequiretime']->inputTypeDefault = 'text';
$dbo->cols['js_manrequiretime']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_manrequiretime']->capContClassDefault = array();
$dbo->cols['js_manrequiretime']->valContClassDefault = array();
$dbo->cols['js_manrequiretime']->option->defaultMethod = 'text';
$dbo->cols['js_manrequiretime']->option->searchMethod = 'text';
$dbo->cols['js_manrequiretime']->option->listMethod = 'text';
$dbo->cols['js_manrequiretime']->option->detailMethod = 'text';
$dbo->cols['js_manrequiretime']->option->newMethod = 'text';
$dbo->cols['js_manrequiretime']->option->editMethod = 'text';
$dbo->cols['js_requiretime'] = new DBO_COL('js_requiretime', 'int4', '4', '-1');
$dbo->cols['js_requiretime']->searchMode = 'exact';
$dbo->cols['js_requiretime']->exportUseLookup = true;
$dbo->cols['js_requiretime']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_requiretime']->inputNewModifier = 'showRequiredMinute';
$dbo->cols['js_requiretime']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_requiretime']->inputEditModifier = 'showRequiredMinute';
$dbo->cols['js_requiretime']->inputTypeDefault = 'text';
$dbo->cols['js_requiretime']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_requiretime']->capContClassDefault = array();
$dbo->cols['js_requiretime']->valContClassDefault = array();
$dbo->cols['js_requiretime']->option->defaultMethod = 'text';
$dbo->cols['js_requiretime']->option->searchMethod = 'text';
$dbo->cols['js_requiretime']->option->listMethod = 'text';
$dbo->cols['js_requiretime']->option->detailMethod = 'text';
$dbo->cols['js_requiretime']->option->newMethod = 'text';
$dbo->cols['js_requiretime']->option->editMethod = 'text';
$dbo->cols['filehistory'] = new DBO_COL('filehistory', 'unknown', '-2', '-1');
$dbo->cols['filehistory']->searchMode = 'exact';
$dbo->cols['filehistory']->exportUseLookup = true;
$dbo->cols['filehistory']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['filehistory']->displayDetailModifier = 'showFileHistory';
$dbo->cols['filehistory']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['filehistory']->inputEditModifier = 'showFileHistory';
$dbo->cols['filehistory']->inputTypeDefault = 'text';
$dbo->cols['filehistory']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['filehistory']->capContClassDefault = array();
$dbo->cols['filehistory']->valContClassDefault = array();
$dbo->cols['filehistory']->option->defaultMethod = 'text';
$dbo->cols['filehistory']->option->searchMethod = 'text';
$dbo->cols['filehistory']->option->listMethod = 'text';
$dbo->cols['filehistory']->option->detailMethod = 'text';
$dbo->cols['filehistory']->option->newMethod = 'text';
$dbo->cols['filehistory']->option->editMethod = 'text';
$dbo->cols['js_request_dateinmth'] = new DBO_COL('js_request_dateinmth', 'varchar', '-1', '54');
$dbo->cols['js_request_dateinmth']->searchMode = 'exact';
$dbo->cols['js_request_dateinmth']->exportUseLookup = true;
$dbo->cols['js_request_dateinmth']->inputTypeDefault = 'text';
$dbo->cols['js_request_dateinmth']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_request_dateinmth']->capContClassDefault = array();
$dbo->cols['js_request_dateinmth']->valContClassDefault = array();
$dbo->cols['js_request_dateinmth']->option->defaultMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->searchMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->listMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->detailMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->newMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->editMethod = 'text';
$dbo->cols['js_jobcolor'] = new DBO_COL('js_jobcolor', 'varchar', '-1', '54');
$dbo->cols['js_jobcolor']->searchMode = 'exact';
$dbo->cols['js_jobcolor']->exportUseLookup = true;
$dbo->cols['js_jobcolor']->inputTypeDefault = 'PixelAdminRadioInline';
$dbo->cols['js_jobcolor']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_jobcolor']->capContClassDefault = array();
$dbo->cols['js_jobcolor']->valContClassDefault = array();
$dbo->cols['js_jobcolor']->option->default = '1
2
3
4
5
6
7
8';
$dbo->cols['js_jobcolor']->option->defaultMethod = 'text';
$dbo->cols['js_jobcolor']->option->searchMethod = 'text';
$dbo->cols['js_jobcolor']->option->listMethod = 'text';
$dbo->cols['js_jobcolor']->option->detailMethod = 'text';
$dbo->cols['js_jobcolor']->option->newMethod = 'text';
$dbo->cols['js_jobcolor']->option->editMethod = 'text';
$dbo->cols['joboutput'] = new DBO_COL('joboutput', 'varchar', '-1', '-1');
$dbo->cols['joboutput']->searchMode = 'exact';
$dbo->cols['joboutput']->exportUseLookup = true;
$dbo->cols['joboutput']->inputTypeDefault = 'PixelAdminCheckboxInline';
$dbo->cols['joboutput']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['joboutput']->mandatoryNew = '1';
$dbo->cols['joboutput']->mandatoryEdit = '1';
$dbo->cols['joboutput']->capContClassDefault = array();
$dbo->cols['joboutput']->valContClassDefault = array();
$dbo->cols['joboutput']->option->default = 'select jol_id,jol_title from mjoboutputlookup';
$dbo->cols['joboutput']->option->new = 'select jol_id,jol_title from mjoboutputlookup where jol_custtype = \'TYPE A\' order by jol_seq';
$dbo->cols['joboutput']->option->edit = 'select jol_id,jol_title from mjoboutputlookup where jol_custtype = \'TYPE A\' order by jol_seq';
$dbo->cols['joboutput']->option->defaultMethod = 'sql';
$dbo->cols['joboutput']->option->searchMethod = 'text';
$dbo->cols['joboutput']->option->listMethod = 'text';
$dbo->cols['joboutput']->option->detailMethod = 'text';
$dbo->cols['joboutput']->option->newMethod = 'sql';
$dbo->cols['joboutput']->option->editMethod = 'sql';
$dbo->cols['js_lpi'] = new DBO_COL('js_lpi', 'int4', '4', '-1');
$dbo->cols['js_lpi']->displayDataType = 'int';
$dbo->cols['js_lpi']->searchMode = 'exact';
$dbo->cols['js_lpi']->exportUseLookup = true;
$dbo->cols['js_lpi']->size = '5';
$dbo->cols['js_lpi']->inputTypeDefault = 'TextInputControl';
$dbo->cols['js_lpi']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_lpi']->capContClassDefault = array();
$dbo->cols['js_lpi']->valContClassDefault = array();
$dbo->cols['js_lpi']->valContExtClassDefault = 'form-group';
$dbo->cols['js_lpi']->option->defaultMethod = 'text';
$dbo->cols['js_lpi']->option->searchMethod = 'text';
$dbo->cols['js_lpi']->option->listMethod = 'text';
$dbo->cols['js_lpi']->option->detailMethod = 'text';
$dbo->cols['js_lpi']->option->newMethod = 'text';
$dbo->cols['js_lpi']->option->editMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__'] = new DBO_COL('__map_mjobbarcode__jbc_jsid__', 'int4', '4', '-1');
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->searchMode = 'exact';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->exportUseLookup = true;
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->displayDetailModifier = 'genDetailTableDisplay';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputNewModifier = 'genDetailTableInput';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputEditModifier = 'genDetailTableInput';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputTypeDefault = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->mandatoryNew = '1';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->mandatoryEdit = '1';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->capContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->valContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->defaultMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->searchMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->listMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->detailMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->newMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->editMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__'] = new DBO_COL('__map_mjobbarcode__jbc_value__', 'unknown', '-2', '-1');
$dbo->cols['__map_mjobbarcode__jbc_value__']->searchMode = 'exact';
$dbo->cols['__map_mjobbarcode__jbc_value__']->exportUseLookup = true;
$dbo->cols['__map_mjobbarcode__jbc_value__']->inputTypeDefault = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['__map_mjobbarcode__jbc_value__']->mandatoryNew = '1';
$dbo->cols['__map_mjobbarcode__jbc_value__']->mandatoryEdit = '1';
$dbo->cols['__map_mjobbarcode__jbc_value__']->capContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_value__']->valContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->defaultMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->searchMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->listMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->detailMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->newMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->editMethod = 'text';
$dbo->cols['js_mcid'] = new DBO_COL('js_mcid', 'int4', '4', '-1');
$dbo->cols['js_mcid']->searchMode = 'exact';
$dbo->cols['js_mcid']->exportUseLookup = true;
$dbo->cols['js_mcid']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['js_mcid']->displayDetailModifier = 'showPrinterInfo';
$dbo->cols['js_mcid']->inputTypeDefault = 'select';
$dbo->cols['js_mcid']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_mcid']->capContClassDefault = array();
$dbo->cols['js_mcid']->valContClassDefault = array();
$dbo->cols['js_mcid']->option->default = 'select mc_id, mc_name, org_name from mcustmachine join fcorg on mc_orgid = org_id order by 3,2';
$dbo->cols['js_mcid']->option->new = 'select mc_id, mc_name, org_name from mcustmachine join fcorg on mc_orgid = org_id order by 3,2';
$dbo->cols['js_mcid']->option->edit = 'select mc_id, mc_name, org_name from mcustmachine join fcorg on mc_orgid = org_id order by 3,2';
$dbo->cols['js_mcid']->option->defaultMethod = 'sql';
$dbo->cols['js_mcid']->option->searchMethod = 'text';
$dbo->cols['js_mcid']->option->listMethod = 'text';
$dbo->cols['js_mcid']->option->detailMethod = 'text';
$dbo->cols['js_mcid']->option->newMethod = 'sql';
$dbo->cols['js_mcid']->option->editMethod = 'sql';
$dbo->cols['js_code'] = new DBO_COL('js_code', 'varchar', '-1', '36');
$dbo->cols['js_code']->searchMode = 'exact';
$dbo->cols['js_code']->exportUseLookup = true;
$dbo->cols['js_code']->inputTypeDefault = 'text';
$dbo->cols['js_code']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_code']->capContClassDefault = array();
$dbo->cols['js_code']->valContClassDefault = array();
$dbo->cols['js_code']->option->defaultMethod = 'text';
$dbo->cols['js_code']->option->searchMethod = 'text';
$dbo->cols['js_code']->option->listMethod = 'text';
$dbo->cols['js_code']->option->detailMethod = 'text';
$dbo->cols['js_code']->option->newMethod = 'text';
$dbo->cols['js_code']->option->editMethod = 'text';
$dbo->cols['js_month_occur'] = new DBO_COL('js_month_occur', 'int4', '4', '-1');
$dbo->cols['js_month_occur']->searchMode = 'exact';
$dbo->cols['js_month_occur']->exportUseLookup = true;
$dbo->cols['js_month_occur']->inputTypeDefault = 'text';
$dbo->cols['js_month_occur']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_month_occur']->capContClassDefault = array();
$dbo->cols['js_month_occur']->valContClassDefault = array();
$dbo->cols['js_month_occur']->option->defaultMethod = 'text';
$dbo->cols['js_month_occur']->option->searchMethod = 'text';
$dbo->cols['js_month_occur']->option->listMethod = 'text';
$dbo->cols['js_month_occur']->option->detailMethod = 'text';
$dbo->cols['js_month_occur']->option->newMethod = 'text';
$dbo->cols['js_month_occur']->option->editMethod = 'text';
$dbo->cols['js_price'] = new DBO_COL('js_price', 'numeric', '-1', '1310728');
$dbo->cols['js_price']->searchMode = 'exact';
$dbo->cols['js_price']->exportUseLookup = true;
$dbo->cols['js_price']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_price']->inputNewModifier = 'showPrice';
$dbo->cols['js_price']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_price']->inputEditModifier = 'showPrice';
$dbo->cols['js_price']->inputTypeDefault = 'text';
$dbo->cols['js_price']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_price']->capContClassDefault = array();
$dbo->cols['js_price']->valContClassDefault = array();
$dbo->cols['js_price']->option->defaultMethod = 'text';
$dbo->cols['js_price']->option->searchMethod = 'text';
$dbo->cols['js_price']->option->listMethod = 'text';
$dbo->cols['js_price']->option->detailMethod = 'text';
$dbo->cols['js_price']->option->newMethod = 'text';
$dbo->cols['js_price']->option->editMethod = 'text';
$dbo->cols['pmc_id'] = new DBO_COL('pmc_id', 'int4', '4', '-1');
$dbo->cols['pmc_id']->searchMode = 'exact';
$dbo->cols['pmc_id']->exportUseLookup = true;
$dbo->cols['pmc_id']->inputTypeDefault = 'text';
$dbo->cols['pmc_id']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['pmc_id']->capContClassDefault = array();
$dbo->cols['pmc_id']->valContClassDefault = array();
$dbo->cols['pmc_id']->option->defaultMethod = 'text';
$dbo->cols['pmc_id']->option->searchMethod = 'text';
$dbo->cols['pmc_id']->option->listMethod = 'text';
$dbo->cols['pmc_id']->option->detailMethod = 'text';
$dbo->cols['pmc_id']->option->newMethod = 'text';
$dbo->cols['pmc_id']->option->editMethod = 'text';
$dbo->cols['js_outputtype'] = new DBO_COL('js_outputtype', 'varchar', '-1', '54');
$dbo->cols['js_outputtype']->searchMode = 'exact';
$dbo->cols['js_outputtype']->exportUseLookup = true;
$dbo->cols['js_outputtype']->inputTypeDefault = 'select';
$dbo->cols['js_outputtype']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_outputtype']->attributeDefault = array('readonly'=>array(''));
$dbo->cols['js_outputtype']->capContClassDefault = array();
$dbo->cols['js_outputtype']->valContClassDefault = array();
$dbo->cols['js_outputtype']->option->default = 'select lu_code,lu_title
from fclookup
where lu_cat = \'OUTPUTTYPE\'';
$dbo->cols['js_outputtype']->option->defaultMethod = 'sql';
$dbo->cols['js_outputtype']->option->searchMethod = 'text';
$dbo->cols['js_outputtype']->option->listMethod = 'text';
$dbo->cols['js_outputtype']->option->detailMethod = 'text';
$dbo->cols['js_outputtype']->option->newMethod = 'text';
$dbo->cols['js_outputtype']->option->editMethod = 'text';
$dbo->cols['js_outputwidth'] = new DBO_COL('js_outputwidth', 'int4', '4', '-1');
$dbo->cols['js_outputwidth']->displayDataType = 'int';
$dbo->cols['js_outputwidth']->searchMode = 'exact';
$dbo->cols['js_outputwidth']->exportUseLookup = true;
$dbo->cols['js_outputwidth']->inputTypeDefault = 'TextInputControl';
$dbo->cols['js_outputwidth']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_outputwidth']->capContClassDefault = array();
$dbo->cols['js_outputwidth']->valContClassDefault = array();
$dbo->cols['js_outputwidth']->option->defaultMethod = 'text';
$dbo->cols['js_outputwidth']->option->searchMethod = 'text';
$dbo->cols['js_outputwidth']->option->listMethod = 'text';
$dbo->cols['js_outputwidth']->option->detailMethod = 'text';
$dbo->cols['js_outputwidth']->option->newMethod = 'text';
$dbo->cols['js_outputwidth']->option->editMethod = 'text';
$dbo->cols['js_outputheight'] = new DBO_COL('js_outputheight', 'int4', '4', '-1');
$dbo->cols['js_outputheight']->displayDataType = 'int';
$dbo->cols['js_outputheight']->searchMode = 'exact';
$dbo->cols['js_outputheight']->exportUseLookup = true;
$dbo->cols['js_outputheight']->inputTypeDefault = 'TextInputControl';
$dbo->cols['js_outputheight']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_outputheight']->capContClassDefault = array();
$dbo->cols['js_outputheight']->valContClassDefault = array();
$dbo->cols['js_outputheight']->option->defaultMethod = 'text';
$dbo->cols['js_outputheight']->option->searchMethod = 'text';
$dbo->cols['js_outputheight']->option->listMethod = 'text';
$dbo->cols['js_outputheight']->option->detailMethod = 'text';
$dbo->cols['js_outputheight']->option->newMethod = 'text';
$dbo->cols['js_outputheight']->option->editMethod = 'text';
$dbo->cols['js_qcchecked'] = new DBO_COL('js_qcchecked', 'varchar', '-1', '2004');
$dbo->cols['js_qcchecked']->searchMode = 'exact';
$dbo->cols['js_qcchecked']->exportUseLookup = true;
$dbo->cols['js_qcchecked']->inputTypeDefault = 'text';
$dbo->cols['js_qcchecked']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_qcchecked']->capContClassDefault = array();
$dbo->cols['js_qcchecked']->valContClassDefault = array();
$dbo->cols['js_qcchecked']->option->default = 'select lu_code,lu_title
from fclookup 
where lu_cat = \'QCLIST\'
order by lu_title
';
$dbo->cols['js_qcchecked']->option->defaultMethod = 'sql';
$dbo->cols['js_qcchecked']->option->searchMethod = 'text';
$dbo->cols['js_qcchecked']->option->listMethod = 'text';
$dbo->cols['js_qcchecked']->option->detailMethod = 'text';
$dbo->cols['js_qcchecked']->option->newMethod = 'text';
$dbo->cols['js_qcchecked']->option->editMethod = 'text';
$dbo->cols['js_currency'] = new DBO_COL('js_currency', 'varchar', '-1', '54');
$dbo->cols['js_currency']->searchMode = 'exact';
$dbo->cols['js_currency']->exportUseLookup = true;
$dbo->cols['js_currency']->inputTypeDefault = 'text';
$dbo->cols['js_currency']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_currency']->capContClassDefault = array();
$dbo->cols['js_currency']->valContClassDefault = array();
$dbo->cols['js_currency']->option->defaultMethod = 'text';
$dbo->cols['js_currency']->option->searchMethod = 'text';
$dbo->cols['js_currency']->option->listMethod = 'text';
$dbo->cols['js_currency']->option->detailMethod = 'text';
$dbo->cols['js_currency']->option->newMethod = 'text';
$dbo->cols['js_currency']->option->editMethod = 'text';
$dbo->cols['js_finalprice'] = new DBO_COL('js_finalprice', 'numeric', '-1', '1310728');
$dbo->cols['js_finalprice']->searchMode = 'exact';
$dbo->cols['js_finalprice']->exportUseLookup = true;
$dbo->cols['js_finalprice']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['js_finalprice']->displayDetailModifier = 'showPriceDet';
$dbo->cols['js_finalprice']->inputTypeDefault = 'text';
$dbo->cols['js_finalprice']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_finalprice']->capContClassDefault = array();
$dbo->cols['js_finalprice']->valContClassDefault = array();
$dbo->cols['js_finalprice']->option->defaultMethod = 'text';
$dbo->cols['js_finalprice']->option->searchMethod = 'text';
$dbo->cols['js_finalprice']->option->listMethod = 'text';
$dbo->cols['js_finalprice']->option->detailMethod = 'text';
$dbo->cols['js_finalprice']->option->newMethod = 'text';
$dbo->cols['js_finalprice']->option->editMethod = 'text';
$dbo->cols['js_rate'] = new DBO_COL('js_rate', 'numeric', '-1', '1310728');
$dbo->cols['js_rate']->searchMode = 'exact';
$dbo->cols['js_rate']->exportUseLookup = true;
$dbo->cols['js_rate']->inputTypeDefault = 'text';
$dbo->cols['js_rate']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_rate']->capContClassDefault = array();
$dbo->cols['js_rate']->valContClassDefault = array();
$dbo->cols['js_rate']->option->defaultMethod = 'text';
$dbo->cols['js_rate']->option->searchMethod = 'text';
$dbo->cols['js_rate']->option->listMethod = 'text';
$dbo->cols['js_rate']->option->detailMethod = 'text';
$dbo->cols['js_rate']->option->newMethod = 'text';
$dbo->cols['js_rate']->option->editMethod = 'text';
$dbo->cols['js_totalinch'] = new DBO_COL('js_totalinch', 'numeric', '-1', '1310728');
$dbo->cols['js_totalinch']->searchMode = 'exact';
$dbo->cols['js_totalinch']->exportUseLookup = true;
$dbo->cols['js_totalinch']->inputTypeDefault = 'text';
$dbo->cols['js_totalinch']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_totalinch']->capContClassDefault = array();
$dbo->cols['js_totalinch']->valContClassDefault = array();
$dbo->cols['js_totalinch']->option->defaultMethod = 'text';
$dbo->cols['js_totalinch']->option->searchMethod = 'text';
$dbo->cols['js_totalinch']->option->listMethod = 'text';
$dbo->cols['js_totalinch']->option->detailMethod = 'text';
$dbo->cols['js_totalinch']->option->newMethod = 'text';
$dbo->cols['js_totalinch']->option->editMethod = 'text';
$dbo->cols['js_color_6'] = new DBO_COL('js_color_6', 'varchar', '-1', '16');
$dbo->cols['js_color_6']->searchMode = 'exact';
$dbo->cols['js_color_6']->exportUseLookup = true;
$dbo->cols['js_color_6']->inputTypeDefault = 'text';
$dbo->cols['js_color_6']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_6']->capContClassDefault = array();
$dbo->cols['js_color_6']->valContClassDefault = array();
$dbo->cols['js_color_6']->option->default = 'select lu_code, lu_title from fclookup where lu_cat = \'JOBCOLOR\' order by 2';
$dbo->cols['js_color_6']->option->defaultMethod = 'sql';
$dbo->cols['js_color_6']->option->searchMethod = 'text';
$dbo->cols['js_color_6']->option->listMethod = 'text';
$dbo->cols['js_color_6']->option->detailMethod = 'text';
$dbo->cols['js_color_6']->option->newMethod = 'text';
$dbo->cols['js_color_6']->option->editMethod = 'text';
$dbo->cols['js_color_7'] = new DBO_COL('js_color_7', 'varchar', '-1', '16');
$dbo->cols['js_color_7']->searchMode = 'exact';
$dbo->cols['js_color_7']->exportUseLookup = true;
$dbo->cols['js_color_7']->inputTypeDefault = 'text';
$dbo->cols['js_color_7']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_7']->capContClassDefault = array();
$dbo->cols['js_color_7']->valContClassDefault = array();
$dbo->cols['js_color_7']->option->default = 'select lu_code, lu_title from fclookup where lu_cat = \'JOBCOLOR\' order by 2';
$dbo->cols['js_color_7']->option->defaultMethod = 'sql';
$dbo->cols['js_color_7']->option->searchMethod = 'text';
$dbo->cols['js_color_7']->option->listMethod = 'text';
$dbo->cols['js_color_7']->option->detailMethod = 'text';
$dbo->cols['js_color_7']->option->newMethod = 'text';
$dbo->cols['js_color_7']->option->editMethod = 'text';
$dbo->cols['js_color_8'] = new DBO_COL('js_color_8', 'varchar', '-1', '16');
$dbo->cols['js_color_8']->searchMode = 'exact';
$dbo->cols['js_color_8']->exportUseLookup = true;
$dbo->cols['js_color_8']->inputTypeDefault = 'text';
$dbo->cols['js_color_8']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_8']->capContClassDefault = array();
$dbo->cols['js_color_8']->valContClassDefault = array();
$dbo->cols['js_color_8']->option->default = 'select lu_code, lu_title from fclookup where lu_cat = \'JOBCOLOR\' order by 2';
$dbo->cols['js_color_8']->option->defaultMethod = 'sql';
$dbo->cols['js_color_8']->option->searchMethod = 'text';
$dbo->cols['js_color_8']->option->listMethod = 'text';
$dbo->cols['js_color_8']->option->detailMethod = 'text';
$dbo->cols['js_color_8']->option->newMethod = 'text';
$dbo->cols['js_color_8']->option->editMethod = 'text';
$dbo->cols['js_cartonsize_g'] = new DBO_COL('js_cartonsize_g', 'numeric', '-1', '1310728');
$dbo->cols['js_cartonsize_g']->searchMode = 'exact';
$dbo->cols['js_cartonsize_g']->exportUseLookup = true;
$dbo->cols['js_cartonsize_g']->inputTypeDefault = 'text';
$dbo->cols['js_cartonsize_g']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cartonsize_g']->capContClassDefault = array();
$dbo->cols['js_cartonsize_g']->valContClassDefault = array();
$dbo->cols['js_cartonsize_g']->option->defaultMethod = 'text';
$dbo->cols['js_cartonsize_g']->option->searchMethod = 'text';
$dbo->cols['js_cartonsize_g']->option->listMethod = 'text';
$dbo->cols['js_cartonsize_g']->option->detailMethod = 'text';
$dbo->cols['js_cartonsize_g']->option->newMethod = 'text';
$dbo->cols['js_cartonsize_g']->option->editMethod = 'text';
$dbo->cols['js_cartonsize_l1'] = new DBO_COL('js_cartonsize_l1', 'numeric', '-1', '1310728');
$dbo->cols['js_cartonsize_l1']->searchMode = 'exact';
$dbo->cols['js_cartonsize_l1']->exportUseLookup = true;
$dbo->cols['js_cartonsize_l1']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_cartonsize_l1']->inputNewModifier = 'showLength';
$dbo->cols['js_cartonsize_l1']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_cartonsize_l1']->inputEditModifier = 'showLength';
$dbo->cols['js_cartonsize_l1']->inputTypeDefault = 'text';
$dbo->cols['js_cartonsize_l1']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cartonsize_l1']->capContClassDefault = array();
$dbo->cols['js_cartonsize_l1']->valContClassDefault = array();
$dbo->cols['js_cartonsize_l1']->option->defaultMethod = 'text';
$dbo->cols['js_cartonsize_l1']->option->searchMethod = 'text';
$dbo->cols['js_cartonsize_l1']->option->listMethod = 'text';
$dbo->cols['js_cartonsize_l1']->option->detailMethod = 'text';
$dbo->cols['js_cartonsize_l1']->option->newMethod = 'text';
$dbo->cols['js_cartonsize_l1']->option->editMethod = 'text';
$dbo->cols['js_cartonsize_w2'] = new DBO_COL('js_cartonsize_w2', 'numeric', '-1', '1310728');
$dbo->cols['js_cartonsize_w2']->searchMode = 'exact';
$dbo->cols['js_cartonsize_w2']->exportUseLookup = true;
$dbo->cols['js_cartonsize_w2']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_cartonsize_w2']->inputNewModifier = 'showWidth';
$dbo->cols['js_cartonsize_w2']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_cartonsize_w2']->inputEditModifier = 'showWidth';
$dbo->cols['js_cartonsize_w2']->inputTypeDefault = 'text';
$dbo->cols['js_cartonsize_w2']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cartonsize_w2']->capContClassDefault = array();
$dbo->cols['js_cartonsize_w2']->valContClassDefault = array();
$dbo->cols['js_cartonsize_w2']->option->defaultMethod = 'text';
$dbo->cols['js_cartonsize_w2']->option->searchMethod = 'text';
$dbo->cols['js_cartonsize_w2']->option->listMethod = 'text';
$dbo->cols['js_cartonsize_w2']->option->detailMethod = 'text';
$dbo->cols['js_cartonsize_w2']->option->newMethod = 'text';
$dbo->cols['js_cartonsize_w2']->option->editMethod = 'text';
$dbo->cols['js_cartonsize_l3'] = new DBO_COL('js_cartonsize_l3', 'numeric', '-1', '1310728');
$dbo->cols['js_cartonsize_l3']->searchMode = 'exact';
$dbo->cols['js_cartonsize_l3']->exportUseLookup = true;
$dbo->cols['js_cartonsize_l3']->inputTypeDefault = 'text';
$dbo->cols['js_cartonsize_l3']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cartonsize_l3']->capContClassDefault = array();
$dbo->cols['js_cartonsize_l3']->valContClassDefault = array();
$dbo->cols['js_cartonsize_l3']->option->defaultMethod = 'text';
$dbo->cols['js_cartonsize_l3']->option->searchMethod = 'text';
$dbo->cols['js_cartonsize_l3']->option->listMethod = 'text';
$dbo->cols['js_cartonsize_l3']->option->detailMethod = 'text';
$dbo->cols['js_cartonsize_l3']->option->newMethod = 'text';
$dbo->cols['js_cartonsize_l3']->option->editMethod = 'text';
$dbo->cols['js_cartonsize_w4'] = new DBO_COL('js_cartonsize_w4', 'numeric', '-1', '1310728');
$dbo->cols['js_cartonsize_w4']->searchMode = 'exact';
$dbo->cols['js_cartonsize_w4']->exportUseLookup = true;
$dbo->cols['js_cartonsize_w4']->inputTypeDefault = 'text';
$dbo->cols['js_cartonsize_w4']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cartonsize_w4']->capContClassDefault = array();
$dbo->cols['js_cartonsize_w4']->valContClassDefault = array();
$dbo->cols['js_cartonsize_w4']->option->defaultMethod = 'text';
$dbo->cols['js_cartonsize_w4']->option->searchMethod = 'text';
$dbo->cols['js_cartonsize_w4']->option->listMethod = 'text';
$dbo->cols['js_cartonsize_w4']->option->detailMethod = 'text';
$dbo->cols['js_cartonsize_w4']->option->newMethod = 'text';
$dbo->cols['js_cartonsize_w4']->option->editMethod = 'text';
$dbo->cols['js_cartonsize_height'] = new DBO_COL('js_cartonsize_height', 'numeric', '-1', '1310728');
$dbo->cols['js_cartonsize_height']->searchMode = 'exact';
$dbo->cols['js_cartonsize_height']->exportUseLookup = true;
$dbo->cols['js_cartonsize_height']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_cartonsize_height']->inputNewModifier = 'showHeight';
$dbo->cols['js_cartonsize_height']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_cartonsize_height']->inputEditModifier = 'showHeight';
$dbo->cols['js_cartonsize_height']->inputTypeDefault = 'text';
$dbo->cols['js_cartonsize_height']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cartonsize_height']->capContClassDefault = array();
$dbo->cols['js_cartonsize_height']->valContClassDefault = array();
$dbo->cols['js_cartonsize_height']->option->defaultMethod = 'text';
$dbo->cols['js_cartonsize_height']->option->searchMethod = 'text';
$dbo->cols['js_cartonsize_height']->option->listMethod = 'text';
$dbo->cols['js_cartonsize_height']->option->detailMethod = 'text';
$dbo->cols['js_cartonsize_height']->option->newMethod = 'text';
$dbo->cols['js_cartonsize_height']->option->editMethod = 'text';
$dbo->cols['js_cartonsize_top'] = new DBO_COL('js_cartonsize_top', 'numeric', '-1', '1310728');
$dbo->cols['js_cartonsize_top']->searchMode = 'exact';
$dbo->cols['js_cartonsize_top']->exportUseLookup = true;
$dbo->cols['js_cartonsize_top']->inputTypeDefault = 'text';
$dbo->cols['js_cartonsize_top']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cartonsize_top']->capContClassDefault = array();
$dbo->cols['js_cartonsize_top']->valContClassDefault = array();
$dbo->cols['js_cartonsize_top']->option->defaultMethod = 'text';
$dbo->cols['js_cartonsize_top']->option->searchMethod = 'text';
$dbo->cols['js_cartonsize_top']->option->listMethod = 'text';
$dbo->cols['js_cartonsize_top']->option->detailMethod = 'text';
$dbo->cols['js_cartonsize_top']->option->newMethod = 'text';
$dbo->cols['js_cartonsize_top']->option->editMethod = 'text';
$dbo->cols['js_cartonsize_bottom'] = new DBO_COL('js_cartonsize_bottom', 'numeric', '-1', '1310728');
$dbo->cols['js_cartonsize_bottom']->searchMode = 'exact';
$dbo->cols['js_cartonsize_bottom']->exportUseLookup = true;
$dbo->cols['js_cartonsize_bottom']->inputTypeDefault = 'text';
$dbo->cols['js_cartonsize_bottom']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cartonsize_bottom']->capContClassDefault = array();
$dbo->cols['js_cartonsize_bottom']->valContClassDefault = array();
$dbo->cols['js_cartonsize_bottom']->option->defaultMethod = 'text';
$dbo->cols['js_cartonsize_bottom']->option->searchMethod = 'text';
$dbo->cols['js_cartonsize_bottom']->option->listMethod = 'text';
$dbo->cols['js_cartonsize_bottom']->option->detailMethod = 'text';
$dbo->cols['js_cartonsize_bottom']->option->newMethod = 'text';
$dbo->cols['js_cartonsize_bottom']->option->editMethod = 'text';
$dbo->cols['js_expectdelivery'] = new DBO_COL('js_expectdelivery', 'timestamptz', '8', '-1');
$dbo->cols['js_expectdelivery']->searchMode = 'exact';
$dbo->cols['js_expectdelivery']->exportUseLookup = true;
$dbo->cols['js_expectdelivery']->inputTypeDefault = 'BootstrapDateTime';
$dbo->cols['js_expectdelivery']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_expectdelivery']->mandatoryNew = '1';
$dbo->cols['js_expectdelivery']->mandatoryEdit = '1';
$dbo->cols['js_expectdelivery']->capContClassDefault = array();
$dbo->cols['js_expectdelivery']->valContClassDefault = array();
$dbo->cols['js_expectdelivery']->option->defaultMethod = 'text';
$dbo->cols['js_expectdelivery']->option->searchMethod = 'text';
$dbo->cols['js_expectdelivery']->option->listMethod = 'text';
$dbo->cols['js_expectdelivery']->option->detailMethod = 'text';
$dbo->cols['js_expectdelivery']->option->newMethod = 'text';
$dbo->cols['js_expectdelivery']->option->editMethod = 'text';
$dbo->cols['js_cancelremark'] = new DBO_COL('js_cancelremark', 'text', '-1', '-1');
$dbo->cols['js_cancelremark']->searchMode = 'exact';
$dbo->cols['js_cancelremark']->exportUseLookup = true;
$dbo->cols['js_cancelremark']->inputTypeDefault = 'text';
$dbo->cols['js_cancelremark']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_cancelremark']->capContClassDefault = array();
$dbo->cols['js_cancelremark']->valContClassDefault = array();
$dbo->cols['js_cancelremark']->option->defaultMethod = 'text';
$dbo->cols['js_cancelremark']->option->searchMethod = 'text';
$dbo->cols['js_cancelremark']->option->listMethod = 'text';
$dbo->cols['js_cancelremark']->option->detailMethod = 'text';
$dbo->cols['js_cancelremark']->option->newMethod = 'text';
$dbo->cols['js_cancelremark']->option->editMethod = 'text';
$dbo->cols['js_forwardtocusttime'] = new DBO_COL('js_forwardtocusttime', 'timestamptz', '8', '-1');
$dbo->cols['js_forwardtocusttime']->searchMode = 'exact';
$dbo->cols['js_forwardtocusttime']->exportUseLookup = true;
$dbo->cols['js_forwardtocusttime']->inputTypeDefault = 'text';
$dbo->cols['js_forwardtocusttime']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_forwardtocusttime']->capContClassDefault = array();
$dbo->cols['js_forwardtocusttime']->valContClassDefault = array();
$dbo->cols['js_forwardtocusttime']->option->defaultMethod = 'text';
$dbo->cols['js_forwardtocusttime']->option->searchMethod = 'text';
$dbo->cols['js_forwardtocusttime']->option->listMethod = 'text';
$dbo->cols['js_forwardtocusttime']->option->detailMethod = 'text';
$dbo->cols['js_forwardtocusttime']->option->newMethod = 'text';
$dbo->cols['js_forwardtocusttime']->option->editMethod = 'text';
$dbo->cols['js_color_9'] = new DBO_COL('js_color_9', 'varchar', '-1', '16');
$dbo->cols['js_color_9']->searchMode = 'exact';
$dbo->cols['js_color_9']->exportUseLookup = true;
$dbo->cols['js_color_9']->inputTypeDefault = 'text';
$dbo->cols['js_color_9']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_color_9']->capContClassDefault = array();
$dbo->cols['js_color_9']->valContClassDefault = array();
$dbo->cols['js_color_9']->option->defaultMethod = 'text';
$dbo->cols['js_color_9']->option->searchMethod = 'text';
$dbo->cols['js_color_9']->option->listMethod = 'text';
$dbo->cols['js_color_9']->option->detailMethod = 'text';
$dbo->cols['js_color_9']->option->newMethod = 'text';
$dbo->cols['js_color_9']->option->editMethod = 'text';
$dbo->cols['js_custrejectreason'] = new DBO_COL('js_custrejectreason', 'varchar', '-1', '-1');
$dbo->cols['js_custrejectreason']->searchMode = 'exact';
$dbo->cols['js_custrejectreason']->exportUseLookup = true;
$dbo->cols['js_custrejectreason']->inputTypeDefault = 'text';
$dbo->cols['js_custrejectreason']->inputTypeConfig = array('default'=>array(), 'list'=>array(), 'new'=>array(), 'edit'=>array(), 'detail'=>array(), 'search'=>array());
$dbo->cols['js_custrejectreason']->capContClassDefault = array();
$dbo->cols['js_custrejectreason']->valContClassDefault = array();
$dbo->cols['js_custrejectreason']->option->default = 'select lu_code,lu_title
from fclookup 
where lu_cat = \'QCLIST\'
order by lu_title';
$dbo->cols['js_custrejectreason']->option->defaultMethod = 'sql';
$dbo->cols['js_custrejectreason']->option->searchMethod = 'text';
$dbo->cols['js_custrejectreason']->option->listMethod = 'text';
$dbo->cols['js_custrejectreason']->option->detailMethod = 'text';
$dbo->cols['js_custrejectreason']->option->newMethod = 'text';
$dbo->cols['js_custrejectreason']->option->editMethod = 'text';

// support multiple language. only caption
global $LANG;
if(file_exists(dirname(__FILE__).DIRECTORY_SEPARATOR.$dbo->id.'.conf.lang.'.$LANG.'.php')){
	require(dirname(__FILE__).DIRECTORY_SEPARATOR.$dbo->id.'.conf.lang.'.$LANG.'.php');
}else if($availang = glob(dirname(__FILE__).DIRECTORY_SEPARATOR.$dboID.'.conf.lang.*')){
	require($availang[0]);
}

// for DBO Builder
$dbo->saveDir = dirname(dirname(__FILE__));

$dbo->run();

/*
# enable overwriting DBO class
class DBO_custom_reassignment extends DBO{
	function __construct(){
		parent::__construct();
	}
}

$dbo->newModifier = 'dbo_reassignment_custom_new';
function dbo_reassignment_custom_new($table, $cols, $dbo){
	global $DB;
	$ret = array();
	$ok = $DB->doInsert($table, $cols);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

$dbo->editModifier = 'dbo_reassignment_custom_edit';
function dbo_reassignment_custom_edit($table, $cols, $wheres, $dbo){
	global $DB;
	$ret = array();
	$ok = $DB->doUpdate($table, $cols, $wheres);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

$dbo->searchModifier = 'dbo_reassignment_custom_search';
function dbo_reassignment_custom_search(&$search, $dbo){
}

$dbo->deleteModifier = 'dbo_reassignment_custom_delete';
function dbo_reassignment_custom_delete($table, $wheres, $dbo){
	global $DB;
	$ret = array();
	$ok = $DB->doDelete($table, $wheres);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

function dbo_reassignment_display_modifier($col, $colVal, $data=array(), $html=null){
}
*/
?>