<?php
require_once(dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'init.inc.php');

$dbo->cols['js_id']->caption->set('default', 'js_id', 'text');
$dbo->cols['js_orgid']->caption->set('default', 'Customer', 'text');
$dbo->cols['js_ctid']->caption->set('default', 'js_ctid', 'text');
$dbo->cols['js_request_date']->caption->set('default', 'Request date', 'text');
$dbo->cols['js_request_by']->caption->set('default', 'js_request_by', 'text');
$dbo->cols['js_title']->caption->set('default', 'js_title', 'text');
$dbo->cols['js_model']->caption->set('default', 'js_model', 'text');
$dbo->cols['js_description']->caption->set('default', 'Job description', 'text');
$dbo->cols['js_material_provided']->caption->set('default', 'js_material_provided', 'text');
$dbo->cols['js_color_1']->caption->set('default', 'js_color_1', 'text');
$dbo->cols['js_color_2']->caption->set('default', 'js_color_2', 'text');
$dbo->cols['js_color_3']->caption->set('default', 'js_color_3', 'text');
$dbo->cols['js_color_4']->caption->set('default', 'js_color_4', 'text');
$dbo->cols['js_color_5']->caption->set('default', 'js_color_5', 'text');
$dbo->cols['js_angle_1']->caption->set('default', 'js_angle_1', 'text');
$dbo->cols['js_angle_2']->caption->set('default', 'js_angle_2', 'text');
$dbo->cols['js_angle_3']->caption->set('default', 'js_angle_3', 'text');
$dbo->cols['js_angle_4']->caption->set('default', 'js_angle_4', 'text');
$dbo->cols['js_angle_5']->caption->set('default', 'js_angle_5', 'text');
$dbo->cols['js_bleeding']->caption->set('default', 'js_bleeding', 'text');
$dbo->cols['js_bleeding_remark']->caption->set('default', 'js_bleeding_remark', 'text');
$dbo->cols['js_distortion']->caption->set('default', 'js_distortion', 'text');
$dbo->cols['js_distortion_value']->caption->set('default', 'js_distortion_value', 'text');
$dbo->cols['js_diecut_ind']->caption->set('default', 'js_diecut_ind', 'text');
$dbo->cols['js_diecut_no']->caption->set('default', 'js_diecut_no', 'text');
$dbo->cols['js_trapping_size']->caption->set('default', 'js_trapping_size', 'text');
$dbo->cols['js_primcat']->caption->set('default', 'js_primcat', 'text');
$dbo->cols['js_status']->caption->set('default', 'js_status', 'text');
$dbo->cols['js_completiondate']->caption->set('default', 'Completion date', 'text');
$dbo->cols['js_assignto']->caption->set('default', 'js_assignto', 'text');
$dbo->cols['js_carid']->caption->set('default', 'js_carid', 'text');
$dbo->cols['js_decision']->caption->set('default', 'js_decision', 'text');
$dbo->cols['js_width']->caption->set('default', 'js_width', 'text');
$dbo->cols['js_height']->caption->set('default', 'js_height', 'text');
$dbo->cols['js_requiretime']->caption->set('default', 'js_requiretime', 'text');
$dbo->cols['js_request_dateinmth']->caption->set('default', 'js_request_dateinmth', 'text');
$dbo->cols['js_jobcolor']->caption->set('default', 'Color of job', 'text');
$dbo->cols['js_lpi']->caption->set('default', 'js_lpi', 'text');
$dbo->cols['js_mcid']->caption->set('default', 'js_mcid', 'text');
$dbo->cols['js_code']->caption->set('default', 'js_code', 'text');
$dbo->cols['js_month_occur']->caption->set('default', 'js_month_occur', 'text');
$dbo->cols['js_price']->caption->set('default', 'js_price', 'text');
$dbo->cols['js_outputtype']->caption->set('default', 'js_outputtype', 'text');
$dbo->cols['js_outputwidth']->caption->set('default', 'js_outputwidth', 'text');
$dbo->cols['js_outputheight']->caption->set('default', 'js_outputheight', 'text');
$dbo->cols['js_qcchecked']->caption->set('default', 'js_qcchecked', 'text');
$dbo->cols['js_currency']->caption->set('default', 'Currency', 'text');
$dbo->cols['js_finalprice']->caption->set('default', 'Price', 'text');
$dbo->cols['js_rate']->caption->set('default', 'Rate', 'text');
$dbo->cols['js_totalinch']->caption->set('default', 'Total inch <sup>2</sup>', 'text');
$dbo->cols['org_id']->caption->set('default', 'org_id', 'text');
$dbo->cols['org_type']->caption->set('default', 'org_type', 'text');
$dbo->cols['org_external']->caption->set('default', 'org_external', 'text');
$dbo->cols['org_name']->caption->set('default', 'org_name', 'text');
$dbo->cols['org_parentid']->caption->set('default', 'org_parentid', 'text');
$dbo->cols['org_primaryid']->caption->set('default', 'org_primaryid', 'text');
$dbo->cols['org_address']->caption->set('default', 'org_address', 'text');
$dbo->cols['org_contactno']->caption->set('default', 'org_contactno', 'text');
$dbo->cols['org_status']->caption->set('default', 'org_status', 'text');
$dbo->cols['org_lccode']->caption->set('default', 'org_lccode', 'text');
$dbo->cols['org_concode']->caption->set('default', 'org_concode', 'text');
$dbo->cols['org_region']->caption->set('default', 'org_region', 'text');
$dbo->cols['org_created']->caption->set('default', 'org_created', 'text');
$dbo->cols['jobcategory']->caption->set('default', 'Category', 'text');
$dbo->cols['joboutput']->caption->set('default', 'Output requirement', 'text');
$dbo->cols['totalbarcode']->caption->set('default', 'Total barcode', 'text');

$dbo->titleList = 'List Record';
$dbo->titleDetail = 'Detail';
$dbo->titleNew = 'New Record';
$dbo->titleEdit = 'Edit Record';
$dbo->titleSearch = 'Search Record';
$dbo->text->searchCancel = 'Reset';
$dbo->text->searchSubmit = 'Search';
$dbo->text->searchToggle = 'Search';
$dbo->text->editCancel = 'Cancel';
$dbo->text->editSubmit = 'Edit';
$dbo->text->newCancel = 'Cancel';
$dbo->text->newSubmit = 'Submit';
$dbo->text->listSubmit = 'Submit';
$dbo->text->detailCancel = 'Cancel';
$dbo->text->detailDelete = 'Delete';
$dbo->text->listNew = 'New';
$dbo->text->listEdit = 'Edit';
$dbo->text->listDelete = 'Delete';
$dbo->text->listDetail = 'Detail';
$dbo->text->messageAfterNew = '';
$dbo->text->messageAfterEdit = '';
$dbo->text->messageAfterDelete = '';
$dbo->text->defaultMessageAfterNew = 'Record created.';
$dbo->text->defaultMessageAfterEdit = 'Record updated.';
$dbo->text->defaultMessageAfterDelete = 'Record deleted.';

?>