<?php
require_once(dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'init.inc.php');

$dboID = 'rpt_dailycallsummary';
$dbo = DBO_init($dboID);
$dbo->id = $dboID;
$dbo->table = 'rpt_dailycallsummary';
$dbo->key = array();
$dbo->sql = 'select * from rpt_dailycallsummary';
$dbo->col = array('rpt_completiondate', 'rpt_astotaljob', 'rpt_astotalprice', 'rpt_astotalinch', 'rpt_eutotaljob', 'rpt_eutotalprice', 'rpt_eutotalinch', 'rpt_lctotaljob', 'rpt_lctotalprice', 'rpt_lctotalinch', 'rpt_callid', 'rpt_totalpriceinmyr', 'rpt_totalpriceinusd');
$dbo->colList = array('rpt_completiondate', 'rpt_astotaljob', 'rpt_astotalprice', 'rpt_astotalinch', 'rpt_eutotaljob', 'rpt_eutotalprice', 'rpt_eutotalinch', 'rpt_lctotaljob', 'rpt_lctotalprice', 'rpt_lctotalinch', 'rpt_totalpriceinmyr', 'rpt_totalpriceinusd');
$dbo->colListEdit = array();
$dbo->colListNew = array();
$dbo->colListGlobalInput = array();
$dbo->colDetail = array();
$dbo->colNew = array();
$dbo->colEdit = array();
$dbo->colSearch = array('rpt_completiondate');
$dbo->colExport = array();
$dbo->colSort = array();
$dbo->colSum = array('rpt_astotaljob', 'rpt_astotalprice', 'rpt_astotalinch', 'rpt_eutotaljob', 'rpt_eutotalprice', 'rpt_eutotalinch', 'rpt_lctotaljob', 'rpt_lctotalprice', 'rpt_lctotalinch', 'rpt_totalpriceinmyr', 'rpt_totalpriceinusd');
$dbo->colSumPage = array('rpt_astotaljob', 'rpt_astotalprice', 'rpt_astotalinch', 'rpt_eutotaljob', 'rpt_eutotalprice', 'rpt_eutotalinch', 'rpt_lctotaljob', 'rpt_lctotalprice', 'rpt_lctotalinch', 'rpt_totalpriceinmyr', 'rpt_totalpriceinusd');
$dbo->colAvg = array();
$dbo->colAvgPage = array();
$dbo->canSearch = true;
$dbo->canNew = false;
$dbo->canEdit = false;
$dbo->canDelete = false;
$dbo->canDetail = false;
$dbo->canListEdit = false;
$dbo->canListNew = false;
$dbo->canNewGroup = array();
$dbo->canEditGroup = array();
$dbo->canDeleteGroup = array();
$dbo->showSearch = true;
$dbo->titleList = 'List Record';
$dbo->titleDetail = 'Detail';
$dbo->titleNew = 'New Record';
$dbo->titleEdit = 'Edit Record';
$dbo->titleSearch = 'Search Record';
$dbo->theme = 'pixeladmin';
$dbo->layout = 'One';
$dbo->pageLinkCount = '5';
$dbo->recordPerPage = '50';
$dbo->showRecordNo = '1';
$dbo->defaultState = 'search';
$dbo->maxSortCount = '9';
$dbo->defaultDateFormat = 'yyyy-mm-dd';
$dbo->defaultDateTimeFormat = 'yyyy-mm-dd hh24:min:ss';
$dbo->defaultTimeFormat = 'hh24:min:ss';
$dbo->lang = 'EN-US';
$dbo->searchCancel = 'Reset';
$dbo->searchSubmit = 'Search';
$dbo->detailBack = 'Back';
$dbo->editCancel = 'Cancel';
$dbo->editSubmit = 'Edit';
$dbo->listEditSubmit = 'Submit';
$dbo->newCancel = 'Cancel';
$dbo->newSubmit = 'Submit';

$dbo->cols['completiondate'] = new DBO_COL('completiondate', 'date', '4', '-1');
$dbo->cols['completiondate']->inputTypeDefault = 'rangedate';
$dbo->cols['completiondate']->mandatorySearch = '1';
$dbo->cols['completiondate']->searchMode = 'exact';
$dbo->cols['completiondate']->capContClassDefault = array();
$dbo->cols['completiondate']->valContClassDefault = array();
$dbo->cols['completiondate']->option->defaultMethod = 'text';
$dbo->cols['completiondate']->option->searchMethod = 'text';
$dbo->cols['completiondate']->option->listMethod = 'text';
$dbo->cols['completiondate']->option->detailMethod = 'text';
$dbo->cols['completiondate']->option->newMethod = 'text';
$dbo->cols['completiondate']->option->editMethod = 'text';
$dbo->cols['astotaljob'] = new DBO_COL('astotaljob', 'int8', '8', '-1');
$dbo->cols['astotaljob']->displayDataType = 'int';
$dbo->cols['astotaljob']->displayListModifierMethod = 'phpfunc';
$dbo->cols['astotaljob']->displayListModifier = 'totalJobLink';
$dbo->cols['astotaljob']->inputTypeDefault = 'text';
$dbo->cols['astotaljob']->searchMode = 'exact';
$dbo->cols['astotaljob']->capContClassDefault = array();
$dbo->cols['astotaljob']->valContClassDefault = array();
$dbo->cols['astotaljob']->option->defaultMethod = 'text';
$dbo->cols['astotaljob']->option->searchMethod = 'text';
$dbo->cols['astotaljob']->option->listMethod = 'text';
$dbo->cols['astotaljob']->option->detailMethod = 'text';
$dbo->cols['astotaljob']->option->newMethod = 'text';
$dbo->cols['astotaljob']->option->editMethod = 'text';
$dbo->cols['astotalprice'] = new DBO_COL('astotalprice', 'numeric', '-1', '-1');
$dbo->cols['astotalprice']->displayDataType = 'currency';
$dbo->cols['astotalprice']->inputTypeDefault = 'text';
$dbo->cols['astotalprice']->searchMode = 'exact';
$dbo->cols['astotalprice']->capContClassDefault = array();
$dbo->cols['astotalprice']->valContClassDefault = array();
$dbo->cols['astotalprice']->option->defaultMethod = 'text';
$dbo->cols['astotalprice']->option->searchMethod = 'text';
$dbo->cols['astotalprice']->option->listMethod = 'text';
$dbo->cols['astotalprice']->option->detailMethod = 'text';
$dbo->cols['astotalprice']->option->newMethod = 'text';
$dbo->cols['astotalprice']->option->editMethod = 'text';
$dbo->cols['astotalinch'] = new DBO_COL('astotalinch', 'numeric', '-1', '-1');
$dbo->cols['astotalinch']->displayDataType = 'currency';
$dbo->cols['astotalinch']->inputTypeDefault = 'text';
$dbo->cols['astotalinch']->searchMode = 'exact';
$dbo->cols['astotalinch']->capContClassDefault = array();
$dbo->cols['astotalinch']->valContClassDefault = array();
$dbo->cols['astotalinch']->option->defaultMethod = 'text';
$dbo->cols['astotalinch']->option->searchMethod = 'text';
$dbo->cols['astotalinch']->option->listMethod = 'text';
$dbo->cols['astotalinch']->option->detailMethod = 'text';
$dbo->cols['astotalinch']->option->newMethod = 'text';
$dbo->cols['astotalinch']->option->editMethod = 'text';
$dbo->cols['eutotaljob'] = new DBO_COL('eutotaljob', 'int8', '8', '-1');
$dbo->cols['eutotaljob']->displayDataType = 'int';
$dbo->cols['eutotaljob']->displayListModifierMethod = 'phpfunc';
$dbo->cols['eutotaljob']->displayListModifier = 'totalJobLink';
$dbo->cols['eutotaljob']->inputTypeDefault = 'text';
$dbo->cols['eutotaljob']->searchMode = 'exact';
$dbo->cols['eutotaljob']->capContClassDefault = array();
$dbo->cols['eutotaljob']->valContClassDefault = array();
$dbo->cols['eutotaljob']->option->defaultMethod = 'text';
$dbo->cols['eutotaljob']->option->searchMethod = 'text';
$dbo->cols['eutotaljob']->option->listMethod = 'text';
$dbo->cols['eutotaljob']->option->detailMethod = 'text';
$dbo->cols['eutotaljob']->option->newMethod = 'text';
$dbo->cols['eutotaljob']->option->editMethod = 'text';
$dbo->cols['eutotalprice'] = new DBO_COL('eutotalprice', 'numeric', '-1', '-1');
$dbo->cols['eutotalprice']->displayDataType = 'currency';
$dbo->cols['eutotalprice']->inputTypeDefault = 'text';
$dbo->cols['eutotalprice']->searchMode = 'exact';
$dbo->cols['eutotalprice']->capContClassDefault = array();
$dbo->cols['eutotalprice']->valContClassDefault = array();
$dbo->cols['eutotalprice']->option->defaultMethod = 'text';
$dbo->cols['eutotalprice']->option->searchMethod = 'text';
$dbo->cols['eutotalprice']->option->listMethod = 'text';
$dbo->cols['eutotalprice']->option->detailMethod = 'text';
$dbo->cols['eutotalprice']->option->newMethod = 'text';
$dbo->cols['eutotalprice']->option->editMethod = 'text';
$dbo->cols['eutotalinch'] = new DBO_COL('eutotalinch', 'numeric', '-1', '-1');
$dbo->cols['eutotalinch']->displayDataType = 'currency';
$dbo->cols['eutotalinch']->inputTypeDefault = 'text';
$dbo->cols['eutotalinch']->searchMode = 'exact';
$dbo->cols['eutotalinch']->capContClassDefault = array();
$dbo->cols['eutotalinch']->valContClassDefault = array();
$dbo->cols['eutotalinch']->option->defaultMethod = 'text';
$dbo->cols['eutotalinch']->option->searchMethod = 'text';
$dbo->cols['eutotalinch']->option->listMethod = 'text';
$dbo->cols['eutotalinch']->option->detailMethod = 'text';
$dbo->cols['eutotalinch']->option->newMethod = 'text';
$dbo->cols['eutotalinch']->option->editMethod = 'text';
$dbo->cols['lctotaljob'] = new DBO_COL('lctotaljob', 'int8', '8', '-1');
$dbo->cols['lctotaljob']->displayDataType = 'int';
$dbo->cols['lctotaljob']->displayListModifierMethod = 'phpfunc';
$dbo->cols['lctotaljob']->displayListModifier = 'totalJobLink';
$dbo->cols['lctotaljob']->inputTypeDefault = 'text';
$dbo->cols['lctotaljob']->searchMode = 'exact';
$dbo->cols['lctotaljob']->capContClassDefault = array();
$dbo->cols['lctotaljob']->valContClassDefault = array();
$dbo->cols['lctotaljob']->option->defaultMethod = 'text';
$dbo->cols['lctotaljob']->option->searchMethod = 'text';
$dbo->cols['lctotaljob']->option->listMethod = 'text';
$dbo->cols['lctotaljob']->option->detailMethod = 'text';
$dbo->cols['lctotaljob']->option->newMethod = 'text';
$dbo->cols['lctotaljob']->option->editMethod = 'text';
$dbo->cols['lctotalprice'] = new DBO_COL('lctotalprice', 'numeric', '-1', '-1');
$dbo->cols['lctotalprice']->displayDataType = 'currency';
$dbo->cols['lctotalprice']->inputTypeDefault = 'text';
$dbo->cols['lctotalprice']->searchMode = 'exact';
$dbo->cols['lctotalprice']->capContClassDefault = array();
$dbo->cols['lctotalprice']->valContClassDefault = array();
$dbo->cols['lctotalprice']->option->defaultMethod = 'text';
$dbo->cols['lctotalprice']->option->searchMethod = 'text';
$dbo->cols['lctotalprice']->option->listMethod = 'text';
$dbo->cols['lctotalprice']->option->detailMethod = 'text';
$dbo->cols['lctotalprice']->option->newMethod = 'text';
$dbo->cols['lctotalprice']->option->editMethod = 'text';
$dbo->cols['lctotalinch'] = new DBO_COL('lctotalinch', 'numeric', '-1', '-1');
$dbo->cols['lctotalinch']->displayDataType = 'currency';
$dbo->cols['lctotalinch']->inputTypeDefault = 'text';
$dbo->cols['lctotalinch']->searchMode = 'exact';
$dbo->cols['lctotalinch']->capContClassDefault = array();
$dbo->cols['lctotalinch']->valContClassDefault = array();
$dbo->cols['lctotalinch']->option->defaultMethod = 'text';
$dbo->cols['lctotalinch']->option->searchMethod = 'text';
$dbo->cols['lctotalinch']->option->listMethod = 'text';
$dbo->cols['lctotalinch']->option->detailMethod = 'text';
$dbo->cols['lctotalinch']->option->newMethod = 'text';
$dbo->cols['lctotalinch']->option->editMethod = 'text';
$dbo->cols['totalpriceinmyr'] = new DBO_COL('totalpriceinmyr', 'numeric', '-1', '-1');
$dbo->cols['totalpriceinmyr']->displayDataType = 'currency';
$dbo->cols['totalpriceinmyr']->inputTypeDefault = 'text';
$dbo->cols['totalpriceinmyr']->searchMode = 'exact';
$dbo->cols['totalpriceinmyr']->capContClassDefault = array();
$dbo->cols['totalpriceinmyr']->valContClassDefault = array();
$dbo->cols['totalpriceinmyr']->option->defaultMethod = 'text';
$dbo->cols['totalpriceinmyr']->option->searchMethod = 'text';
$dbo->cols['totalpriceinmyr']->option->listMethod = 'text';
$dbo->cols['totalpriceinmyr']->option->detailMethod = 'text';
$dbo->cols['totalpriceinmyr']->option->newMethod = 'text';
$dbo->cols['totalpriceinmyr']->option->editMethod = 'text';
$dbo->cols['totalpriceinusd'] = new DBO_COL('totalpriceinusd', 'numeric', '-1', '-1');
$dbo->cols['totalpriceinusd']->displayDataType = 'currency';
$dbo->cols['totalpriceinusd']->inputTypeDefault = 'text';
$dbo->cols['totalpriceinusd']->searchMode = 'exact';
$dbo->cols['totalpriceinusd']->capContClassDefault = array();
$dbo->cols['totalpriceinusd']->valContClassDefault = array();
$dbo->cols['totalpriceinusd']->option->defaultMethod = 'text';
$dbo->cols['totalpriceinusd']->option->searchMethod = 'text';
$dbo->cols['totalpriceinusd']->option->listMethod = 'text';
$dbo->cols['totalpriceinusd']->option->detailMethod = 'text';
$dbo->cols['totalpriceinusd']->option->newMethod = 'text';
$dbo->cols['totalpriceinusd']->option->editMethod = 'text';
$dbo->cols['rpt_completiondate'] = new DBO_COL('rpt_completiondate', 'date', '4', '-1');
$dbo->cols['rpt_completiondate']->inputTypeDefault = 'rangedate';
$dbo->cols['rpt_completiondate']->searchMode = 'exact';
$dbo->cols['rpt_completiondate']->capContClassDefault = array();
$dbo->cols['rpt_completiondate']->valContClassDefault = array();
$dbo->cols['rpt_completiondate']->option->defaultMethod = 'text';
$dbo->cols['rpt_completiondate']->option->searchMethod = 'text';
$dbo->cols['rpt_completiondate']->option->listMethod = 'text';
$dbo->cols['rpt_completiondate']->option->detailMethod = 'text';
$dbo->cols['rpt_completiondate']->option->newMethod = 'text';
$dbo->cols['rpt_completiondate']->option->editMethod = 'text';
$dbo->cols['rpt_astotaljob'] = new DBO_COL('rpt_astotaljob', 'int4', '4', '-1');
$dbo->cols['rpt_astotaljob']->displayDataType = 'int';
$dbo->cols['rpt_astotaljob']->displayListModifierMethod = 'phpfunc';
$dbo->cols['rpt_astotaljob']->displayListModifier = 'totalJobLink';
$dbo->cols['rpt_astotaljob']->inputTypeDefault = 'text';
$dbo->cols['rpt_astotaljob']->searchMode = 'exact';
$dbo->cols['rpt_astotaljob']->capContClassDefault = array();
$dbo->cols['rpt_astotaljob']->valContClassDefault = array();
$dbo->cols['rpt_astotaljob']->option->defaultMethod = 'text';
$dbo->cols['rpt_astotaljob']->option->searchMethod = 'text';
$dbo->cols['rpt_astotaljob']->option->listMethod = 'text';
$dbo->cols['rpt_astotaljob']->option->detailMethod = 'text';
$dbo->cols['rpt_astotaljob']->option->newMethod = 'text';
$dbo->cols['rpt_astotaljob']->option->editMethod = 'text';
$dbo->cols['rpt_astotalprice'] = new DBO_COL('rpt_astotalprice', 'numeric', '-1', '1310728');
$dbo->cols['rpt_astotalprice']->displayDataType = 'currency';
$dbo->cols['rpt_astotalprice']->inputTypeDefault = 'text';
$dbo->cols['rpt_astotalprice']->searchMode = 'exact';
$dbo->cols['rpt_astotalprice']->capContClassDefault = array();
$dbo->cols['rpt_astotalprice']->valContClassDefault = array();
$dbo->cols['rpt_astotalprice']->option->defaultMethod = 'text';
$dbo->cols['rpt_astotalprice']->option->searchMethod = 'text';
$dbo->cols['rpt_astotalprice']->option->listMethod = 'text';
$dbo->cols['rpt_astotalprice']->option->detailMethod = 'text';
$dbo->cols['rpt_astotalprice']->option->newMethod = 'text';
$dbo->cols['rpt_astotalprice']->option->editMethod = 'text';
$dbo->cols['rpt_astotalinch'] = new DBO_COL('rpt_astotalinch', 'numeric', '-1', '1310728');
$dbo->cols['rpt_astotalinch']->displayDataType = 'currency';
$dbo->cols['rpt_astotalinch']->inputTypeDefault = 'text';
$dbo->cols['rpt_astotalinch']->searchMode = 'exact';
$dbo->cols['rpt_astotalinch']->capContClassDefault = array();
$dbo->cols['rpt_astotalinch']->valContClassDefault = array();
$dbo->cols['rpt_astotalinch']->option->defaultMethod = 'text';
$dbo->cols['rpt_astotalinch']->option->searchMethod = 'text';
$dbo->cols['rpt_astotalinch']->option->listMethod = 'text';
$dbo->cols['rpt_astotalinch']->option->detailMethod = 'text';
$dbo->cols['rpt_astotalinch']->option->newMethod = 'text';
$dbo->cols['rpt_astotalinch']->option->editMethod = 'text';
$dbo->cols['rpt_eutotaljob'] = new DBO_COL('rpt_eutotaljob', 'int4', '4', '-1');
$dbo->cols['rpt_eutotaljob']->displayDataType = 'int';
$dbo->cols['rpt_eutotaljob']->displayListModifierMethod = 'phpfunc';
$dbo->cols['rpt_eutotaljob']->displayListModifier = 'totalJobLink';
$dbo->cols['rpt_eutotaljob']->inputTypeDefault = 'text';
$dbo->cols['rpt_eutotaljob']->searchMode = 'exact';
$dbo->cols['rpt_eutotaljob']->capContClassDefault = array();
$dbo->cols['rpt_eutotaljob']->valContClassDefault = array();
$dbo->cols['rpt_eutotaljob']->option->defaultMethod = 'text';
$dbo->cols['rpt_eutotaljob']->option->searchMethod = 'text';
$dbo->cols['rpt_eutotaljob']->option->listMethod = 'text';
$dbo->cols['rpt_eutotaljob']->option->detailMethod = 'text';
$dbo->cols['rpt_eutotaljob']->option->newMethod = 'text';
$dbo->cols['rpt_eutotaljob']->option->editMethod = 'text';
$dbo->cols['rpt_eutotalprice'] = new DBO_COL('rpt_eutotalprice', 'numeric', '-1', '1310728');
$dbo->cols['rpt_eutotalprice']->displayDataType = 'currency';
$dbo->cols['rpt_eutotalprice']->inputTypeDefault = 'text';
$dbo->cols['rpt_eutotalprice']->searchMode = 'exact';
$dbo->cols['rpt_eutotalprice']->capContClassDefault = array();
$dbo->cols['rpt_eutotalprice']->valContClassDefault = array();
$dbo->cols['rpt_eutotalprice']->option->defaultMethod = 'text';
$dbo->cols['rpt_eutotalprice']->option->searchMethod = 'text';
$dbo->cols['rpt_eutotalprice']->option->listMethod = 'text';
$dbo->cols['rpt_eutotalprice']->option->detailMethod = 'text';
$dbo->cols['rpt_eutotalprice']->option->newMethod = 'text';
$dbo->cols['rpt_eutotalprice']->option->editMethod = 'text';
$dbo->cols['rpt_eutotalinch'] = new DBO_COL('rpt_eutotalinch', 'numeric', '-1', '1310728');
$dbo->cols['rpt_eutotalinch']->displayDataType = 'currency';
$dbo->cols['rpt_eutotalinch']->inputTypeDefault = 'text';
$dbo->cols['rpt_eutotalinch']->searchMode = 'exact';
$dbo->cols['rpt_eutotalinch']->capContClassDefault = array();
$dbo->cols['rpt_eutotalinch']->valContClassDefault = array();
$dbo->cols['rpt_eutotalinch']->option->defaultMethod = 'text';
$dbo->cols['rpt_eutotalinch']->option->searchMethod = 'text';
$dbo->cols['rpt_eutotalinch']->option->listMethod = 'text';
$dbo->cols['rpt_eutotalinch']->option->detailMethod = 'text';
$dbo->cols['rpt_eutotalinch']->option->newMethod = 'text';
$dbo->cols['rpt_eutotalinch']->option->editMethod = 'text';
$dbo->cols['rpt_lctotaljob'] = new DBO_COL('rpt_lctotaljob', 'int4', '4', '-1');
$dbo->cols['rpt_lctotaljob']->displayDataType = 'currency';
$dbo->cols['rpt_lctotaljob']->displayListModifierMethod = 'phpfunc';
$dbo->cols['rpt_lctotaljob']->displayListModifier = 'totalJobLink';
$dbo->cols['rpt_lctotaljob']->inputTypeDefault = 'text';
$dbo->cols['rpt_lctotaljob']->searchMode = 'exact';
$dbo->cols['rpt_lctotaljob']->capContClassDefault = array();
$dbo->cols['rpt_lctotaljob']->valContClassDefault = array();
$dbo->cols['rpt_lctotaljob']->option->defaultMethod = 'text';
$dbo->cols['rpt_lctotaljob']->option->searchMethod = 'text';
$dbo->cols['rpt_lctotaljob']->option->listMethod = 'text';
$dbo->cols['rpt_lctotaljob']->option->detailMethod = 'text';
$dbo->cols['rpt_lctotaljob']->option->newMethod = 'text';
$dbo->cols['rpt_lctotaljob']->option->editMethod = 'text';
$dbo->cols['rpt_lctotalprice'] = new DBO_COL('rpt_lctotalprice', 'numeric', '-1', '1310728');
$dbo->cols['rpt_lctotalprice']->displayDataType = 'currency';
$dbo->cols['rpt_lctotalprice']->inputTypeDefault = 'text';
$dbo->cols['rpt_lctotalprice']->searchMode = 'exact';
$dbo->cols['rpt_lctotalprice']->capContClassDefault = array();
$dbo->cols['rpt_lctotalprice']->valContClassDefault = array();
$dbo->cols['rpt_lctotalprice']->option->defaultMethod = 'text';
$dbo->cols['rpt_lctotalprice']->option->searchMethod = 'text';
$dbo->cols['rpt_lctotalprice']->option->listMethod = 'text';
$dbo->cols['rpt_lctotalprice']->option->detailMethod = 'text';
$dbo->cols['rpt_lctotalprice']->option->newMethod = 'text';
$dbo->cols['rpt_lctotalprice']->option->editMethod = 'text';
$dbo->cols['rpt_lctotalinch'] = new DBO_COL('rpt_lctotalinch', 'numeric', '-1', '1310728');
$dbo->cols['rpt_lctotalinch']->displayDataType = 'currency';
$dbo->cols['rpt_lctotalinch']->inputTypeDefault = 'text';
$dbo->cols['rpt_lctotalinch']->searchMode = 'exact';
$dbo->cols['rpt_lctotalinch']->capContClassDefault = array();
$dbo->cols['rpt_lctotalinch']->valContClassDefault = array();
$dbo->cols['rpt_lctotalinch']->option->defaultMethod = 'text';
$dbo->cols['rpt_lctotalinch']->option->searchMethod = 'text';
$dbo->cols['rpt_lctotalinch']->option->listMethod = 'text';
$dbo->cols['rpt_lctotalinch']->option->detailMethod = 'text';
$dbo->cols['rpt_lctotalinch']->option->newMethod = 'text';
$dbo->cols['rpt_lctotalinch']->option->editMethod = 'text';
$dbo->cols['rpt_callid'] = new DBO_COL('rpt_callid', 'int4', '4', '-1');
$dbo->cols['rpt_callid']->inputTypeDefault = 'text';
$dbo->cols['rpt_callid']->searchMode = 'exact';
$dbo->cols['rpt_callid']->capContClassDefault = array();
$dbo->cols['rpt_callid']->valContClassDefault = array();
$dbo->cols['rpt_callid']->option->defaultMethod = 'text';
$dbo->cols['rpt_callid']->option->searchMethod = 'text';
$dbo->cols['rpt_callid']->option->listMethod = 'text';
$dbo->cols['rpt_callid']->option->detailMethod = 'text';
$dbo->cols['rpt_callid']->option->newMethod = 'text';
$dbo->cols['rpt_callid']->option->editMethod = 'text';
$dbo->cols['rpt_totalpriceinmyr'] = new DBO_COL('rpt_totalpriceinmyr', 'numeric', '-1', '1310728');
$dbo->cols['rpt_totalpriceinmyr']->displayDataType = 'currency';
$dbo->cols['rpt_totalpriceinmyr']->inputTypeDefault = 'text';
$dbo->cols['rpt_totalpriceinmyr']->searchMode = 'exact';
$dbo->cols['rpt_totalpriceinmyr']->capContClassDefault = array();
$dbo->cols['rpt_totalpriceinmyr']->valContClassDefault = array();
$dbo->cols['rpt_totalpriceinmyr']->option->defaultMethod = 'text';
$dbo->cols['rpt_totalpriceinmyr']->option->searchMethod = 'text';
$dbo->cols['rpt_totalpriceinmyr']->option->listMethod = 'text';
$dbo->cols['rpt_totalpriceinmyr']->option->detailMethod = 'text';
$dbo->cols['rpt_totalpriceinmyr']->option->newMethod = 'text';
$dbo->cols['rpt_totalpriceinmyr']->option->editMethod = 'text';
$dbo->cols['rpt_totalpriceinusd'] = new DBO_COL('rpt_totalpriceinusd', 'numeric', '-1', '1310728');
$dbo->cols['rpt_totalpriceinusd']->displayDataType = 'currency';
$dbo->cols['rpt_totalpriceinusd']->inputTypeDefault = 'text';
$dbo->cols['rpt_totalpriceinusd']->searchMode = 'exact';
$dbo->cols['rpt_totalpriceinusd']->capContClassDefault = array();
$dbo->cols['rpt_totalpriceinusd']->valContClassDefault = array();
$dbo->cols['rpt_totalpriceinusd']->option->defaultMethod = 'text';
$dbo->cols['rpt_totalpriceinusd']->option->searchMethod = 'text';
$dbo->cols['rpt_totalpriceinusd']->option->listMethod = 'text';
$dbo->cols['rpt_totalpriceinusd']->option->detailMethod = 'text';
$dbo->cols['rpt_totalpriceinusd']->option->newMethod = 'text';
$dbo->cols['rpt_totalpriceinusd']->option->editMethod = 'text';

// support multiple language. only caption
global $LANG;
if(file_exists(dirname(__FILE__).DIRECTORY_SEPARATOR.$dbo->id.'.conf.lang.'.$LANG.'.php')){
	require(dirname(__FILE__).DIRECTORY_SEPARATOR.$dbo->id.'.conf.lang.'.$LANG.'.php');
}else if($availang = glob(dirname(__FILE__).DIRECTORY_SEPARATOR.$dboID.'.conf.lang.*')){
	require($availang[0]);
}

// for DBO Builder
$dbo->saveDir = dirname(dirname(__FILE__));

$dbo->run();

/*
$dbo->newModifier = 'dbo_rpt_dailycallsummary_custom_new';
function dbo_rpt_dailycallsummary_custom_new($table, $cols){
	global $DB;
	$ret = array();
	$ok = $DB->doInsert($table, $cols);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

$dbo->editModifier = 'dbo_rpt_dailycallsummary_custom_edit';
function dbo_rpt_dailycallsummary_custom_edit($table, $cols, $wheres){
	global $DB;
	$ret = array();
	$ok = $DB->doUpdate($table, $cols, $wheres);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

$dbo->searchModifier = 'dbo_rpt_dailycallsummary_custom_search';
function dbo_rpt_dailycallsummary_custom_search(&$search){
}

$dbo->deleteModifier = 'dbo_rpt_dailycallsummary_custom_delete';
function dbo_rpt_dailycallsummary_custom_delete($table, $wheres){
	global $DB;
	$ret = array();
	$ok = $DB->doDelete($table, $wheres);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

function dbo_rpt_dailycallsummary_display_modifier($col, $colVal, $data=array(), $html=null){
}
*/
?>