<?php
require_once(dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'init.inc.php');

$dbo->cols['org_id']->caption->set('default', 'org_id', 'text');
$dbo->cols['org_code']->caption->set('default', 'Organization code', 'text');
$dbo->cols['org_name']->caption->set('default', 'Organization Name', 'text');
$dbo->cols['org_parentid']->caption->set('default', 'org_parentid', 'text');
$dbo->cols['org_primaryid']->caption->set('default', 'org_primaryid', 'text');
$dbo->cols['org_address']->caption->set('default', 'Address', 'text');
$dbo->cols['org_contactno']->caption->set('default', 'Contact No.', 'text');
$dbo->cols['org_status']->caption->set('default', 'Status', 'text');
$dbo->cols['org_type']->caption->set('default', 'org_type', 'text');
$dbo->cols['org_external']->caption->set('default', 'External', 'text');
$dbo->cols['org_lccode']->caption->set('default', 'org_lccode', 'text');
$dbo->cols['org_concode']->caption->set('default', 'org_concode', 'text');
$dbo->cols['org_region']->caption->set('default', 'Region', 'text');
$dbo->cols['org_created']->caption->set('default', 'org_created', 'text');
$dbo->cols['tp_id']->caption->set('default', 'tp_id', 'text');
$dbo->cols['tp_orgid']->caption->set('default', 'tp_orgid', 'text');
$dbo->cols['tp_customertype']->caption->set('default', 'Customer type', 'text');
$dbo->cols['ox_id']->caption->set('default', 'ox_id', 'text');
$dbo->cols['ox_orgid']->caption->set('default', 'ox_orgid', 'text');
$dbo->cols['ox_customertype']->caption->set('default', 'Customer type', 'text');

$dbo->titleList = 'List Record';
$dbo->titleDetail = 'Detail';
$dbo->titleNew = 'New Record';
$dbo->titleEdit = 'Edit Record';
$dbo->titleSearch = 'Search Record';
$dbo->text->searchCancel = 'Cancel';
$dbo->text->searchSubmit = 'Search';
$dbo->text->searchToggle = 'Search';
$dbo->text->editCancel = 'Cancel';
$dbo->text->editSubmit = 'Save';
$dbo->text->newCancel = 'Cancel';
$dbo->text->newSubmit = 'Save';
$dbo->text->listSubmit = 'Submit';
$dbo->text->detailCancel = 'Back';
$dbo->text->detailDelete = 'Delete ';
$dbo->text->listListNew = 'List New';
$dbo->text->listListNewAdd = 'Add';
$dbo->text->listListNewDelete = 'Delete';
$dbo->text->listListEditToggle = 'Edit Toggle';
$dbo->text->listNew = 'New';
$dbo->text->listEdit = 'Edit';
$dbo->text->listDelete = 'Delete';
$dbo->text->listDetail = 'Detail';
$dbo->text->messageConfirmDelete = ' ';
$dbo->text->messageConfirmMultipleDelete = ' ';
$dbo->text->messageAfterNew = '';
$dbo->text->messageAfterEdit = '';
$dbo->text->messageAfterDelete = '';
$dbo->text->defaultMessageConfirmDelete = 'Confirm delete?';
$dbo->text->defaultMessageConfirmMultipleDelete = 'Confirm delete?';
$dbo->text->defaultMessageAfterNew = 'Record created.';
$dbo->text->defaultMessageAfterEdit = 'Record updated.';
$dbo->text->defaultMessageAfterDelete = 'Record deleted.';
$dbo->text->sum = 'Total';
$dbo->text->sumPage = 'Total';
$dbo->text->sumPageGroup = 'Total (Group)';
$dbo->text->avg = 'Average';
$dbo->text->avgPage = 'Average';
$dbo->text->avgPageGroup = 'Average (Group)';
$dbo->text->listNewEditSubmit = 'Save';

?>