<?php
require_once(dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'init.inc.php');

$dbo->cols['mc_id']->caption->set('default', 'mc_id', 'text');
$dbo->cols['mc_orgid']->caption->set('default', 'Customer name', 'text');
$dbo->cols['mc_orgid']->caption->setTabCaption('default', 'PRESS', 'text');
$dbo->cols['mc_pressmanufacturer']->caption->set('default', 'Manufacturer', 'text');
$dbo->cols['mc_pressyearbuilt']->caption->set('default', 'Year built', 'text');
$dbo->cols['mc_pressmodel']->caption->set('default', 'Model', 'text');
$dbo->cols['mc_presswidth']->caption->set('default', 'Width', 'text');
$dbo->cols['mc_presstype']->caption->set('default', 'Press type', 'text');
$dbo->cols['mc_pressspeed']->caption->set('default', 'Speed', 'text');
$dbo->cols['mc_presscylinderrepeat']->caption->set('default', 'Cylinder repeat', 'text');
$dbo->cols['mc_inkmanufacturer']->caption->set('default', 'Manufacturer', 'text');
$dbo->cols['mc_inkmanufacturer']->caption->setTabCaption('default', 'INK', 'text');
$dbo->cols['mc_inkcommercialname']->caption->set('default', 'Commercial name', 'text');
$dbo->cols['mc_inktype']->caption->set('default', 'Type', 'text');
$dbo->cols['mc_inktypeother']->caption->set('default', 'Type other', 'text');
$dbo->cols['mc_inkviscosity']->caption->set('default', 'Viscosity', 'text');
$dbo->cols['mc_inkvicosityother']->caption->set('default', 'Viscosity other', 'text');
$dbo->cols['mc_inkprintingunit_1']->caption->set('default', 'Printing Unit', 'text');
$dbo->cols['mc_inkprintingunit_2']->caption->set('default', ' ', 'text');
$dbo->cols['mc_inkprintingunit_3']->caption->set('default', ' ', 'text');
$dbo->cols['mc_inkprintingunit_4']->caption->set('default', ' ', 'text');
$dbo->cols['mc_inkprintingunit_5']->caption->set('default', ' ', 'text');
$dbo->cols['mc_inkvisocity_1']->caption->set('default', 'Viscosity (secs)', 'text');
$dbo->cols['mc_inkvisocity_2']->caption->set('default', ' ', 'text');
$dbo->cols['mc_inkvisocity_3']->caption->set('default', ' ', 'text');
$dbo->cols['mc_inkvisocity_4']->caption->set('default', ' ', 'text');
$dbo->cols['mc_inkvisocity_5']->caption->set('default', ' ', 'text');
$dbo->cols['mc_inkph_1']->caption->set('default', 'pH', 'text');
$dbo->cols['mc_inkph_2']->caption->set('default', 'mc_inkph_2', 'text');
$dbo->cols['mc_inkph_3']->caption->set('default', 'mc_inkph_3', 'text');
$dbo->cols['mc_inkph_4']->caption->set('default', 'mc_inkph_4', 'text');
$dbo->cols['mc_inkph_5']->caption->set('default', 'mc_inkph_5', 'text');
$dbo->cols['mc_inkdensity_1']->caption->set('default', 'Density', 'text');
$dbo->cols['mc_inkdensity_2']->caption->set('default', 'mc_inkdensity_2', 'text');
$dbo->cols['mc_inkdensity_3']->caption->set('default', 'mc_inkdensity_3', 'text');
$dbo->cols['mc_inkdensity_4']->caption->set('default', 'mc_inkdensity_4', 'text');
$dbo->cols['mc_inkdensity_5']->caption->set('default', 'mc_inkdensity_5', 'text');
$dbo->cols['mc_platemanufacturer']->caption->set('default', 'Manufacturer', 'text');
$dbo->cols['mc_platemanufacturer']->caption->setTabCaption('default', 'PLATES', 'text');
$dbo->cols['mc_platecommercialname']->caption->set('default', 'Commercial name', 'text');
$dbo->cols['mc_platetype']->caption->set('default', 'Type', 'text');
$dbo->cols['mc_platedurometer']->caption->set('default', 'Durometer', 'text');
$dbo->cols['mc_platedurometer']->caption->setSectionCaption('default', 'Characteristics', 'text');
$dbo->cols['mc_platethickness']->caption->set('default', 'Thckness (mm)', 'text');
$dbo->cols['mc_platerelief']->caption->set('default', 'Relief (mm)', 'text');
$dbo->cols['mc_mountingtapemanufacturer']->caption->set('default', 'mc_mountingtapemanufacturer', 'text');
$dbo->cols['mc_mountingtapename']->caption->set('default', 'mc_mountingtapename', 'text');
$dbo->cols['mc_mountingtapedensity']->caption->set('default', 'mc_mountingtapedensity', 'text');
$dbo->cols['mc_mountingtapthickness']->caption->set('default', 'mc_mountingtapthickness', 'text');
$dbo->cols['mc_mountingcarrierthickness']->caption->set('default', 'mc_mountingcarrierthickness', 'text');
$dbo->cols['mc_mountingcushionmanufacturer']->caption->set('default', 'mc_mountingcushionmanufacturer', 'text');
$dbo->cols['mc_mountingcushonname']->caption->set('default', 'mc_mountingcushonname', 'text');
$dbo->cols['mc_mountingdensity']->caption->set('default', 'mc_mountingdensity', 'text');
$dbo->cols['mc_mountingcushionthickness']->caption->set('default', 'mc_mountingcushionthickness', 'text');
$dbo->cols['mc_cimplevel_1']->caption->set('default', 'mc_cimplevel_1', 'text');
$dbo->cols['mc_cimplevel_2']->caption->set('default', 'mc_cimplevel_2', 'text');
$dbo->cols['mc_cimplevel_3']->caption->set('default', 'mc_cimplevel_3', 'text');
$dbo->cols['mc_cimplevel_4']->caption->set('default', 'mc_cimplevel_4', 'text');
$dbo->cols['mc_cimplevel_5']->caption->set('default', 'mc_cimplevel_5', 'text');
$dbo->cols['mc_cimpsubstrate_1']->caption->set('default', 'mc_cimpsubstrate_1', 'text');
$dbo->cols['mc_cimpsubstrate_2']->caption->set('default', 'mc_cimpsubstrate_2', 'text');
$dbo->cols['mc_cimpsubstrate_3']->caption->set('default', 'mc_cimpsubstrate_3', 'text');
$dbo->cols['mc_cimpsubstrate_4']->caption->set('default', 'mc_cimpsubstrate_4', 'text');
$dbo->cols['mc_cimpsubstrate_5']->caption->set('default', 'mc_cimpsubstrate_5', 'text');
$dbo->cols['mc_cimpanlox_1']->caption->set('default', 'mc_cimpanlox_1', 'text');
$dbo->cols['mc_cimpanlox_2']->caption->set('default', 'mc_cimpanlox_2', 'text');
$dbo->cols['mc_cimpanlox_3']->caption->set('default', 'mc_cimpanlox_3', 'text');
$dbo->cols['mc_cimpanlox_4']->caption->set('default', 'mc_cimpanlox_4', 'text');
$dbo->cols['mc_cimpanlox_5']->caption->set('default', 'mc_cimpanlox_5', 'text');
$dbo->cols['mc_aniloxmanufacturer']->caption->set('default', 'mc_aniloxmanufacturer', 'text');
$dbo->cols['mc_aniloxtype']->caption->set('default', 'mc_aniloxtype', 'text');
$dbo->cols['mc_aniloxengravingangle']->caption->set('default', 'mc_aniloxengravingangle', 'text');
$dbo->cols['mc_aniloxinking']->caption->set('default', 'mc_aniloxinking', 'text');
$dbo->cols['mc_aniloxprintingunit_1']->caption->set('default', 'mc_aniloxprintingunit_1', 'text');
$dbo->cols['mc_aniloxprintingunit_2']->caption->set('default', 'mc_aniloxprintingunit_2', 'text');
$dbo->cols['mc_aniloxprintingunit_3']->caption->set('default', 'mc_aniloxprintingunit_3', 'text');
$dbo->cols['mc_aniloxprintingunit_4']->caption->set('default', 'mc_aniloxprintingunit_4', 'text');
$dbo->cols['mc_aniloxprintingunit_5']->caption->set('default', 'mc_aniloxprintingunit_5', 'text');
$dbo->cols['mc_aniloxmanufacturer_1']->caption->set('default', 'mc_aniloxmanufacturer_1', 'text');
$dbo->cols['mc_aniloxmanufacturer_2']->caption->set('default', 'mc_aniloxmanufacturer_2', 'text');
$dbo->cols['mc_aniloxmanufacturer_3']->caption->set('default', 'mc_aniloxmanufacturer_3', 'text');
$dbo->cols['mc_aniloxmanufacturer_4']->caption->set('default', 'mc_aniloxmanufacturer_4', 'text');
$dbo->cols['mc_aniloxmanufacturer_5']->caption->set('default', 'mc_aniloxmanufacturer_5', 'text');
$dbo->cols['mc_aniloxtype_1']->caption->set('default', 'mc_aniloxtype_1', 'text');
$dbo->cols['mc_aniloxtype_2']->caption->set('default', 'mc_aniloxtype_2', 'text');
$dbo->cols['mc_aniloxtype_3']->caption->set('default', 'mc_aniloxtype_3', 'text');
$dbo->cols['mc_aniloxtype_4']->caption->set('default', 'mc_aniloxtype_4', 'text');
$dbo->cols['mc_aniloxtype_5']->caption->set('default', 'mc_aniloxtype_5', 'text');
$dbo->cols['mc_aniloxengravingangle_1']->caption->set('default', 'mc_aniloxengravingangle_1', 'text');
$dbo->cols['mc_aniloxengravingangle_2']->caption->set('default', 'mc_aniloxengravingangle_2', 'text');
$dbo->cols['mc_aniloxengravingangle_3']->caption->set('default', 'mc_aniloxengravingangle_3', 'text');
$dbo->cols['mc_aniloxengravingangle_4']->caption->set('default', 'mc_aniloxengravingangle_4', 'text');
$dbo->cols['mc_aniloxengravingangle_5']->caption->set('default', 'mc_aniloxengravingangle_5', 'text');
$dbo->cols['mc_aniloxinking_1']->caption->set('default', 'mc_aniloxinking_1', 'text');
$dbo->cols['mc_aniloxinking_2']->caption->set('default', 'mc_aniloxinking_2', 'text');
$dbo->cols['mc_aniloxinking_3']->caption->set('default', 'mc_aniloxinking_3', 'text');
$dbo->cols['mc_aniloxinking_4']->caption->set('default', 'mc_aniloxinking_4', 'text');
$dbo->cols['mc_aniloxinking_5']->caption->set('default', 'mc_aniloxinking_5', 'text');
$dbo->cols['mc_aniloxcellcount_1']->caption->set('default', 'mc_aniloxcellcount_1', 'text');
$dbo->cols['mc_aniloxcellcount_2']->caption->set('default', 'mc_aniloxcellcount_2', 'text');
$dbo->cols['mc_aniloxcellcount_3']->caption->set('default', 'mc_aniloxcellcount_3', 'text');
$dbo->cols['mc_aniloxcellcount_4']->caption->set('default', 'mc_aniloxcellcount_4', 'text');
$dbo->cols['mc_aniloxcellcount_5']->caption->set('default', 'mc_aniloxcellcount_5', 'text');
$dbo->cols['mc_aniloxvolumn_1']->caption->set('default', 'mc_aniloxvolumn_1', 'text');
$dbo->cols['mc_aniloxvolumn_2']->caption->set('default', 'mc_aniloxvolumn_2', 'text');
$dbo->cols['mc_aniloxvolumn_3']->caption->set('default', 'mc_aniloxvolumn_3', 'text');
$dbo->cols['mc_aniloxvolumn_4']->caption->set('default', 'mc_aniloxvolumn_4', 'text');
$dbo->cols['mc_aniloxvolumn_5']->caption->set('default', 'mc_aniloxvolumn_5', 'text');
$dbo->cols['mc_aniloxdoration_1']->caption->set('default', 'mc_aniloxdoration_1', 'text');
$dbo->cols['mc_aniloxdoration_2']->caption->set('default', 'mc_aniloxdoration_2', 'text');
$dbo->cols['mc_aniloxdoration_3']->caption->set('default', 'mc_aniloxdoration_3', 'text');
$dbo->cols['mc_aniloxdoration_4']->caption->set('default', 'mc_aniloxdoration_4', 'text');
$dbo->cols['mc_aniloxdoration_5']->caption->set('default', 'mc_aniloxdoration_5', 'text');
$dbo->cols['mc_aniloxdoctoring_1']->caption->set('default', 'mc_aniloxdoctoring_1', 'text');
$dbo->cols['mc_aniloxdoctoring_2']->caption->set('default', 'mc_aniloxdoctoring_2', 'text');
$dbo->cols['mc_aniloxdoctoring_3']->caption->set('default', 'mc_aniloxdoctoring_3', 'text');
$dbo->cols['mc_aniloxdoctoring_4']->caption->set('default', 'mc_aniloxdoctoring_4', 'text');
$dbo->cols['mc_aniloxdoctoring_5']->caption->set('default', 'mc_aniloxdoctoring_5', 'text');
$dbo->cols['mc_substratemanufacturer']->caption->set('default', 'mc_substratemanufacturer', 'text');
$dbo->cols['mc_substratename']->caption->set('default', 'mc_substratename', 'text');
$dbo->cols['mc_substratetype']->caption->set('default', 'mc_substratetype', 'text');
$dbo->cols['mc_substratedyna']->caption->set('default', 'mc_substratedyna', 'text');
$dbo->cols['mc_substrateweight']->caption->set('default', 'mc_substrateweight', 'text');
$dbo->cols['mc_substrateflute']->caption->set('default', 'mc_substrateflute', 'text');
$dbo->cols['mc_substratethickness']->caption->set('default', 'mc_substratethickness', 'text');

$dbo->titleList = 'List Record';
$dbo->titleDetail = 'Detail';
$dbo->titleNew = 'New Record';
$dbo->titleEdit = 'Edit Record';
$dbo->titleSearch = 'Search Record';
$dbo->text->searchCancel = 'Cancel';
$dbo->text->searchSubmit = 'Search';
$dbo->text->editCancel = 'Cancel';
$dbo->text->editSubmit = 'Save';
$dbo->text->newCancel = 'Cancel';
$dbo->text->newSubmit = 'Save';
$dbo->text->detailCancel = 'Back';
$dbo->text->defaultMessageAfterNew = 'Record created.';
$dbo->text->defaultMessageAfterEdit = 'Record updated.';
$dbo->text->defaultMessageAfterDelete = 'Record deleted.';

?>