<?php
require_once(dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'init.inc.php');

$dboID = 'jobsheet';
$dbo = DBO_init($dboID);
$dbo->id = $dboID;
$dbo->fileSaveMode = 511;
$dbo->table = 'mjobsheet';
$dbo->key = array('js_id');
$dbo->sql = 'select mjobsheet.*, \'\' attachment, \'\' remark, \'\' info,
\'\' filehistory, pmc_id,
cast(jobcategory as varchar) as jobcategory,
cast(joboutput as varchar) as joboutput,
js_id as "__map_mjobbarcode__jbc_jsid__",
null as "__map_mjobbarcode__jbc_btcode__", 
null as "__map_mjobbarcode__jbc_value__"
from mjobsheet 
join fcpmcase on js_id = pmc_casekey
left join (
select string_agg(jc_jclid::char,\', \' order by jc_jclid) jobcategory,jc_jsid from mjobcat
group by jc_jsid) a on js_id = a.jc_jsid
left join (
select string_agg(jo_outputcode,\', \' order by jo_id) joboutput,jo_jsid from mjoboutput
group by jo_id) b on js_id = b.jo_jsid';
$dbo->col = array('js_id', 'js_orgid', 'js_ctid', 'js_request_date', 'js_request_by', 'js_title', 'js_model', 'js_description', 'js_material_provided', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_color_5', 'js_angle_1', 'js_angle_2', 'js_angle_3', 'js_angle_4', 'js_angle_5', 'js_bleeding', 'js_bleeding_remark', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_diecut_no', 'js_trapping_size', 'js_primcat', 'js_status', 'js_completiondate', 'js_assignto', 'js_carid', 'js_decision', 'js_width', 'js_height', 'js_requiretime', 'js_request_dateinmth', 'js_jobcolor', 'js_lpi', 'js_mcid', 'js_code', 'js_month_occur', 'js_price', 'attachment', 'remark', 'info', 'filehistory', 'pmc_id', 'jobcategory', 'joboutput', '__map_mjobbarcode__jbc_jsid__', '__map_mjobbarcode__jbc_btcode__', '__map_mjobbarcode__jbc_value__');
$dbo->colList = array('js_description', 'js_bleeding', 'js_bleeding_remark', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_primcat');
$dbo->colListEdit = array();
$dbo->colListNew = array();
$dbo->colListGlobalInput = array();
$dbo->colDetail = array('js_description', 'pmc_id', 'js_code', 'js_mcid', 'js_jobcolor', 'joboutput', 'jobcategory', 'js_price', 'js_requiretime', 'js_trapping_size', '__map_mjobbarcode__jbc_jsid__', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_angle_1', 'js_angle_2', 'js_angle_3', 'js_angle_4', 'js_lpi', 'js_bleeding', 'js_bleeding_remark', 'js_width', 'js_height', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_carid', 'filehistory');
$dbo->colNew = array('js_description', 'js_mcid', 'js_jobcolor', 'joboutput', 'jobcategory', 'js_price', 'js_requiretime', 'js_trapping_size', '__map_mjobbarcode__jbc_jsid__', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_angle_1', 'js_angle_2', 'js_angle_3', 'js_angle_4', 'js_lpi', 'js_bleeding', 'js_bleeding_remark', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_carid', 'attachment', 'info', 'remark');
$dbo->colEdit = array('js_description', 'js_mcid', 'js_jobcolor', 'joboutput', 'jobcategory', 'js_price', 'js_requiretime', 'js_trapping_size', '__map_mjobbarcode__jbc_jsid__', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_angle_1', 'js_angle_2', 'js_angle_3', 'js_angle_4', 'js_lpi', 'js_bleeding', 'js_bleeding_remark', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_carid', 'filehistory', 'attachment', 'info', 'remark');
$dbo->colSearch = array('js_id', 'js_mcid', 'js_request_date', 'js_request_by', 'js_title', 'js_description', 'js_material_provided', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_angle_1', 'js_angle_2', 'js_angle_3', 'js_angle_4', 'js_bleeding', 'js_bleeding_remark', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_carid', 'js_trapping_size', 'js_primcat', 'js_status', 'js_completiondate', 'js_assignto');
$dbo->colExport = array('js_id', 'js_ctid', 'js_request_date', 'js_request_by', 'js_title', 'js_description', 'js_material_provided', 'js_color_1', 'js_color_2', 'js_color_3', 'js_color_4', 'js_angle_1', 'js_angle_2', 'js_angle_3', 'js_angle_4', 'js_bleeding', 'js_bleeding_remark', 'js_distortion', 'js_distortion_value', 'js_diecut_ind', 'js_trapping_size', 'js_primcat', 'js_status', 'js_completiondate', 'js_assignto');
$dbo->colSort = array();
$dbo->canSearch = false;
$dbo->canNew = true;
$dbo->canEdit = true;
$dbo->canDelete = false;
$dbo->canDetail = true;
$dbo->canListEdit = false;
$dbo->canListNew = false;
$dbo->canNewGroup = array();
$dbo->canEditGroup = array();
$dbo->canDeleteGroup = array();
$dbo->showSearch = true;
$dbo->titleList = 'Job List';
$dbo->titleDetail = 'Job Detail';
$dbo->titleNew = 'New Job';
$dbo->titleEdit = 'Edit Job';
$dbo->titleSearch = 'Search Job';
$dbo->layoutDetail = '4;
4;
4;
4;
4;
4;
4;
4;
4;
4;
4;
1|1|1|1;
1|1|1|1;
4;
4;
4;
2|2;
=
1|1;
2;
2;
2|2;
=
1;
1;';
$dbo->layoutNew = '4;
4;
4;
4;
4;
4;
4;
4;
4;
1|1|1|1;
1|1|1|1;
4;
4;
4;
=
1|1;
2;
2;
2|2;
=
1;
1;';
$dbo->layoutEdit = '4;
4;
4;
4;
4;
4;
4;
4;
4;
1|1|1|1;
1|1|1|1;
4;
4;
4;
=
1|1;
2;
2;
2|2;
=
1;
1;';
$dbo->theme = 'pixeladmin';
$dbo->layout = 'One';
$dbo->pageLinkCount = 7;
$dbo->recordPerPage = 10;
$dbo->showRecordNo = 1;
$dbo->defaultState = 'list';
$dbo->maxSortCount = 9;
$dbo->lang = 'EN-US';
$dbo->render = array();
$dbo->detailBack = 'Back';
$dbo->listEditSubmit = 'Submit';

$dbo->cols['js_id'] = new DBO_COL('js_id', 'int4', '4', '-1');
$dbo->cols['js_id']->inputTypeDefault = 'text';
$dbo->cols['js_id']->searchMode = 'exact';
$dbo->cols['js_id']->capContClassDefault = array();
$dbo->cols['js_id']->valContClassDefault = array();
$dbo->cols['js_id']->option->defaultMethod = 'text';
$dbo->cols['js_id']->option->searchMethod = 'text';
$dbo->cols['js_id']->option->listMethod = 'text';
$dbo->cols['js_id']->option->detailMethod = 'text';
$dbo->cols['js_id']->option->newMethod = 'text';
$dbo->cols['js_id']->option->editMethod = 'text';
$dbo->cols['js_cuid'] = new DBO_COL('js_cuid', 'int4', '4', '-1');
$dbo->cols['js_cuid']->inputTypeDefault = 'text';
$dbo->cols['js_cuid']->searchMode = 'exact';
$dbo->cols['js_cuid']->capContClassDefault = array();
$dbo->cols['js_cuid']->valContClassDefault = array();
$dbo->cols['js_cuid']->option->default = 'select org_id, org_name from fcorg
order by org_name';
$dbo->cols['js_cuid']->option->defaultMethod = 'sql';
$dbo->cols['js_cuid']->option->searchMethod = 'text';
$dbo->cols['js_cuid']->option->listMethod = 'text';
$dbo->cols['js_cuid']->option->detailMethod = 'text';
$dbo->cols['js_cuid']->option->newMethod = 'text';
$dbo->cols['js_cuid']->option->editMethod = 'text';
$dbo->cols['js_ctid'] = new DBO_COL('js_ctid', 'int4', '4', '-1');
$dbo->cols['js_ctid']->inputTypeDefault = 'select';
$dbo->cols['js_ctid']->mandatoryDefault = 1;
$dbo->cols['js_ctid']->searchMode = 'exact';
$dbo->cols['js_ctid']->capContClassDefault = array();
$dbo->cols['js_ctid']->valContClassDefault = array();
$dbo->cols['js_ctid']->option->default = 'select ct_id,ct_name
from pndcontact';
$dbo->cols['js_ctid']->option->defaultMethod = 'sql';
$dbo->cols['js_ctid']->option->searchMethod = 'text';
$dbo->cols['js_ctid']->option->listMethod = 'text';
$dbo->cols['js_ctid']->option->detailMethod = 'text';
$dbo->cols['js_ctid']->option->newMethod = 'text';
$dbo->cols['js_ctid']->option->editMethod = 'text';
$dbo->cols['js_request_date'] = new DBO_COL('js_request_date', 'timestamptz', '8', '-1');
$dbo->cols['js_request_date']->displayDataType = 'datetime';
$dbo->cols['js_request_date']->inputTypeDefault = 'text';
$dbo->cols['js_request_date']->searchMode = 'exact';
$dbo->cols['js_request_date']->capContClassDefault = array();
$dbo->cols['js_request_date']->valContClassDefault = array();
$dbo->cols['js_request_date']->option->defaultMethod = 'text';
$dbo->cols['js_request_date']->option->searchMethod = 'text';
$dbo->cols['js_request_date']->option->listMethod = 'text';
$dbo->cols['js_request_date']->option->detailMethod = 'text';
$dbo->cols['js_request_date']->option->newMethod = 'text';
$dbo->cols['js_request_date']->option->editMethod = 'text';
$dbo->cols['js_request_by'] = new DBO_COL('js_request_by', 'varchar', '-1', '104');
$dbo->cols['js_request_by']->inputTypeDefault = 'text';
$dbo->cols['js_request_by']->searchMode = 'exact';
$dbo->cols['js_request_by']->capContClassDefault = array();
$dbo->cols['js_request_by']->valContClassDefault = array();
$dbo->cols['js_request_by']->option->defaultMethod = 'text';
$dbo->cols['js_request_by']->option->searchMethod = 'text';
$dbo->cols['js_request_by']->option->listMethod = 'text';
$dbo->cols['js_request_by']->option->detailMethod = 'text';
$dbo->cols['js_request_by']->option->newMethod = 'text';
$dbo->cols['js_request_by']->option->editMethod = 'text';
$dbo->cols['js_title'] = new DBO_COL('js_title', 'varchar', '-1', '104');
$dbo->cols['js_title']->inputTypeDefault = 'text';
$dbo->cols['js_title']->searchMode = 'exact';
$dbo->cols['js_title']->capContClassDefault = array();
$dbo->cols['js_title']->valContClassDefault = array();
$dbo->cols['js_title']->option->defaultMethod = 'text';
$dbo->cols['js_title']->option->searchMethod = 'text';
$dbo->cols['js_title']->option->listMethod = 'text';
$dbo->cols['js_title']->option->detailMethod = 'text';
$dbo->cols['js_title']->option->newMethod = 'text';
$dbo->cols['js_title']->option->editMethod = 'text';
$dbo->cols['js_description'] = new DBO_COL('js_description', 'text', '-1', '-1');
$dbo->cols['js_description']->inputTypeDefault = 'text';
$dbo->cols['js_description']->mandatoryDefault = 1;
$dbo->cols['js_description']->searchMode = 'exact';
$dbo->cols['js_description']->capContClassDefault = array();
$dbo->cols['js_description']->valContClassDefault = array();
$dbo->cols['js_description']->option->defaultMethod = 'text';
$dbo->cols['js_description']->option->searchMethod = 'text';
$dbo->cols['js_description']->option->listMethod = 'text';
$dbo->cols['js_description']->option->detailMethod = 'text';
$dbo->cols['js_description']->option->newMethod = 'text';
$dbo->cols['js_description']->option->editMethod = 'text';
$dbo->cols['js_material_provided'] = new DBO_COL('js_material_provided', 'varchar', '-1', '104');
$dbo->cols['js_material_provided']->inputTypeDefault = 'text';
$dbo->cols['js_material_provided']->searchMode = 'exact';
$dbo->cols['js_material_provided']->capContClassDefault = array();
$dbo->cols['js_material_provided']->valContClassDefault = array();
$dbo->cols['js_material_provided']->option->defaultMethod = 'text';
$dbo->cols['js_material_provided']->option->searchMethod = 'text';
$dbo->cols['js_material_provided']->option->listMethod = 'text';
$dbo->cols['js_material_provided']->option->detailMethod = 'text';
$dbo->cols['js_material_provided']->option->newMethod = 'text';
$dbo->cols['js_material_provided']->option->editMethod = 'text';
$dbo->cols['js_cyan'] = new DBO_COL('js_cyan', 'varchar', '-1', '16');
$dbo->cols['js_cyan']->inputTypeDefault = 'checkbox';
$dbo->cols['js_cyan']->searchMode = 'exact';
$dbo->cols['js_cyan']->capContClassDefault = array();
$dbo->cols['js_cyan']->valContClassDefault = array();
$dbo->cols['js_cyan']->option->default = 'Y';
$dbo->cols['js_cyan']->option->defaultMethod = 'text';
$dbo->cols['js_cyan']->option->searchMethod = 'text';
$dbo->cols['js_cyan']->option->listMethod = 'text';
$dbo->cols['js_cyan']->option->detailMethod = 'text';
$dbo->cols['js_cyan']->option->newMethod = 'text';
$dbo->cols['js_cyan']->option->editMethod = 'text';
$dbo->cols['js_magenta'] = new DBO_COL('js_magenta', 'varchar', '-1', '16');
$dbo->cols['js_magenta']->inputTypeDefault = 'checkbox';
$dbo->cols['js_magenta']->searchMode = 'exact';
$dbo->cols['js_magenta']->capContClassDefault = array();
$dbo->cols['js_magenta']->valContClassDefault = array();
$dbo->cols['js_magenta']->option->default = 'Y';
$dbo->cols['js_magenta']->option->defaultMethod = 'text';
$dbo->cols['js_magenta']->option->searchMethod = 'text';
$dbo->cols['js_magenta']->option->listMethod = 'text';
$dbo->cols['js_magenta']->option->detailMethod = 'text';
$dbo->cols['js_magenta']->option->newMethod = 'text';
$dbo->cols['js_magenta']->option->editMethod = 'text';
$dbo->cols['js_yellow'] = new DBO_COL('js_yellow', 'varchar', '-1', '16');
$dbo->cols['js_yellow']->inputTypeDefault = 'checkbox';
$dbo->cols['js_yellow']->searchMode = 'exact';
$dbo->cols['js_yellow']->capContClassDefault = array();
$dbo->cols['js_yellow']->valContClassDefault = array();
$dbo->cols['js_yellow']->option->default = 'Y';
$dbo->cols['js_yellow']->option->defaultMethod = 'text';
$dbo->cols['js_yellow']->option->searchMethod = 'text';
$dbo->cols['js_yellow']->option->listMethod = 'text';
$dbo->cols['js_yellow']->option->detailMethod = 'text';
$dbo->cols['js_yellow']->option->newMethod = 'text';
$dbo->cols['js_yellow']->option->editMethod = 'text';
$dbo->cols['js_black'] = new DBO_COL('js_black', 'varchar', '-1', '16');
$dbo->cols['js_black']->inputTypeDefault = 'checkbox';
$dbo->cols['js_black']->searchMode = 'exact';
$dbo->cols['js_black']->capContClassDefault = array();
$dbo->cols['js_black']->valContClassDefault = array();
$dbo->cols['js_black']->option->default = 'Y';
$dbo->cols['js_black']->option->defaultMethod = 'text';
$dbo->cols['js_black']->option->searchMethod = 'text';
$dbo->cols['js_black']->option->listMethod = 'text';
$dbo->cols['js_black']->option->detailMethod = 'text';
$dbo->cols['js_black']->option->newMethod = 'text';
$dbo->cols['js_black']->option->editMethod = 'text';
$dbo->cols['js_color_1'] = new DBO_COL('js_color_1', 'varchar', '-1', '16');
$dbo->cols['js_color_1']->inputTypeDefault = 'text';
$dbo->cols['js_color_1']->mandatoryDefault = 1;
$dbo->cols['js_color_1']->searchMode = 'exact';
$dbo->cols['js_color_1']->capContClassDefault = array();
$dbo->cols['js_color_1']->valContClassDefault = array();
$dbo->cols['js_color_1']->option->defaultMethod = 'text';
$dbo->cols['js_color_1']->option->searchMethod = 'text';
$dbo->cols['js_color_1']->option->listMethod = 'text';
$dbo->cols['js_color_1']->option->detailMethod = 'text';
$dbo->cols['js_color_1']->option->newMethod = 'text';
$dbo->cols['js_color_1']->option->editMethod = 'text';
$dbo->cols['js_color_2'] = new DBO_COL('js_color_2', 'varchar', '-1', '16');
$dbo->cols['js_color_2']->inputTypeDefault = 'text';
$dbo->cols['js_color_2']->mandatoryDefault = 1;
$dbo->cols['js_color_2']->searchMode = 'exact';
$dbo->cols['js_color_2']->capContClassDefault = array();
$dbo->cols['js_color_2']->valContClassDefault = array();
$dbo->cols['js_color_2']->option->defaultMethod = 'text';
$dbo->cols['js_color_2']->option->searchMethod = 'text';
$dbo->cols['js_color_2']->option->listMethod = 'text';
$dbo->cols['js_color_2']->option->detailMethod = 'text';
$dbo->cols['js_color_2']->option->newMethod = 'text';
$dbo->cols['js_color_2']->option->editMethod = 'text';
$dbo->cols['js_color_3'] = new DBO_COL('js_color_3', 'varchar', '-1', '16');
$dbo->cols['js_color_3']->inputTypeDefault = 'text';
$dbo->cols['js_color_3']->mandatoryDefault = 1;
$dbo->cols['js_color_3']->searchMode = 'exact';
$dbo->cols['js_color_3']->capContClassDefault = array();
$dbo->cols['js_color_3']->valContClassDefault = array();
$dbo->cols['js_color_3']->option->defaultMethod = 'text';
$dbo->cols['js_color_3']->option->searchMethod = 'text';
$dbo->cols['js_color_3']->option->listMethod = 'text';
$dbo->cols['js_color_3']->option->detailMethod = 'text';
$dbo->cols['js_color_3']->option->newMethod = 'text';
$dbo->cols['js_color_3']->option->editMethod = 'text';
$dbo->cols['js_color_4'] = new DBO_COL('js_color_4', 'varchar', '-1', '16');
$dbo->cols['js_color_4']->inputTypeDefault = 'text';
$dbo->cols['js_color_4']->mandatoryDefault = 1;
$dbo->cols['js_color_4']->searchMode = 'exact';
$dbo->cols['js_color_4']->capContClassDefault = array();
$dbo->cols['js_color_4']->valContClassDefault = array();
$dbo->cols['js_color_4']->option->defaultMethod = 'text';
$dbo->cols['js_color_4']->option->searchMethod = 'text';
$dbo->cols['js_color_4']->option->listMethod = 'text';
$dbo->cols['js_color_4']->option->detailMethod = 'text';
$dbo->cols['js_color_4']->option->newMethod = 'text';
$dbo->cols['js_color_4']->option->editMethod = 'text';
$dbo->cols['js_color_5'] = new DBO_COL('js_color_5', 'varchar', '-1', '16');
$dbo->cols['js_color_5']->inputTypeDefault = 'text';
$dbo->cols['js_color_5']->searchMode = 'exact';
$dbo->cols['js_color_5']->capContClassDefault = array();
$dbo->cols['js_color_5']->valContClassDefault = array();
$dbo->cols['js_color_5']->option->defaultMethod = 'text';
$dbo->cols['js_color_5']->option->searchMethod = 'text';
$dbo->cols['js_color_5']->option->listMethod = 'text';
$dbo->cols['js_color_5']->option->detailMethod = 'text';
$dbo->cols['js_color_5']->option->newMethod = 'text';
$dbo->cols['js_color_5']->option->editMethod = 'text';
$dbo->cols['js_angle_1'] = new DBO_COL('js_angle_1', 'varchar', '-1', '16');
$dbo->cols['js_angle_1']->inputTypeDefault = 'text';
$dbo->cols['js_angle_1']->searchMode = 'exact';
$dbo->cols['js_angle_1']->capContClassDefault = array();
$dbo->cols['js_angle_1']->valContClassDefault = array();
$dbo->cols['js_angle_1']->option->defaultMethod = 'text';
$dbo->cols['js_angle_1']->option->searchMethod = 'text';
$dbo->cols['js_angle_1']->option->listMethod = 'text';
$dbo->cols['js_angle_1']->option->detailMethod = 'text';
$dbo->cols['js_angle_1']->option->newMethod = 'text';
$dbo->cols['js_angle_1']->option->editMethod = 'text';
$dbo->cols['js_angle_2'] = new DBO_COL('js_angle_2', 'varchar', '-1', '16');
$dbo->cols['js_angle_2']->inputTypeDefault = 'text';
$dbo->cols['js_angle_2']->searchMode = 'exact';
$dbo->cols['js_angle_2']->capContClassDefault = array();
$dbo->cols['js_angle_2']->valContClassDefault = array();
$dbo->cols['js_angle_2']->option->defaultMethod = 'text';
$dbo->cols['js_angle_2']->option->searchMethod = 'text';
$dbo->cols['js_angle_2']->option->listMethod = 'text';
$dbo->cols['js_angle_2']->option->detailMethod = 'text';
$dbo->cols['js_angle_2']->option->newMethod = 'text';
$dbo->cols['js_angle_2']->option->editMethod = 'text';
$dbo->cols['js_angle_3'] = new DBO_COL('js_angle_3', 'varchar', '-1', '16');
$dbo->cols['js_angle_3']->inputTypeDefault = 'text';
$dbo->cols['js_angle_3']->searchMode = 'exact';
$dbo->cols['js_angle_3']->capContClassDefault = array();
$dbo->cols['js_angle_3']->valContClassDefault = array();
$dbo->cols['js_angle_3']->option->defaultMethod = 'text';
$dbo->cols['js_angle_3']->option->searchMethod = 'text';
$dbo->cols['js_angle_3']->option->listMethod = 'text';
$dbo->cols['js_angle_3']->option->detailMethod = 'text';
$dbo->cols['js_angle_3']->option->newMethod = 'text';
$dbo->cols['js_angle_3']->option->editMethod = 'text';
$dbo->cols['js_angle_4'] = new DBO_COL('js_angle_4', 'varchar', '-1', '16');
$dbo->cols['js_angle_4']->inputTypeDefault = 'text';
$dbo->cols['js_angle_4']->searchMode = 'exact';
$dbo->cols['js_angle_4']->capContClassDefault = array();
$dbo->cols['js_angle_4']->valContClassDefault = array();
$dbo->cols['js_angle_4']->option->defaultMethod = 'text';
$dbo->cols['js_angle_4']->option->searchMethod = 'text';
$dbo->cols['js_angle_4']->option->listMethod = 'text';
$dbo->cols['js_angle_4']->option->detailMethod = 'text';
$dbo->cols['js_angle_4']->option->newMethod = 'text';
$dbo->cols['js_angle_4']->option->editMethod = 'text';
$dbo->cols['js_angle_5'] = new DBO_COL('js_angle_5', 'varchar', '-1', '16');
$dbo->cols['js_angle_5']->inputTypeDefault = 'text';
$dbo->cols['js_angle_5']->searchMode = 'exact';
$dbo->cols['js_angle_5']->capContClassDefault = array();
$dbo->cols['js_angle_5']->valContClassDefault = array();
$dbo->cols['js_angle_5']->option->defaultMethod = 'text';
$dbo->cols['js_angle_5']->option->searchMethod = 'text';
$dbo->cols['js_angle_5']->option->listMethod = 'text';
$dbo->cols['js_angle_5']->option->detailMethod = 'text';
$dbo->cols['js_angle_5']->option->newMethod = 'text';
$dbo->cols['js_angle_5']->option->editMethod = 'text';
$dbo->cols['js_bleeding'] = new DBO_COL('js_bleeding', 'varchar', '-1', '16');
$dbo->cols['js_bleeding']->inputTypeDefault = 'select';
$dbo->cols['js_bleeding']->searchMode = 'exact';
$dbo->cols['js_bleeding']->capContClassDefault = array();
$dbo->cols['js_bleeding']->valContClassDefault = array();
$dbo->cols['js_bleeding']->option->default = '0
3
5
7
10
15';
$dbo->cols['js_bleeding']->option->defaultMethod = 'text';
$dbo->cols['js_bleeding']->option->searchMethod = 'text';
$dbo->cols['js_bleeding']->option->listMethod = 'text';
$dbo->cols['js_bleeding']->option->detailMethod = 'text';
$dbo->cols['js_bleeding']->option->newMethod = 'text';
$dbo->cols['js_bleeding']->option->editMethod = 'text';
$dbo->cols['js_bleeding_remark'] = new DBO_COL('js_bleeding_remark', 'varchar', '-1', '1004');
$dbo->cols['js_bleeding_remark']->inputTypeDefault = 'TextareaAutosize';
$dbo->cols['js_bleeding_remark']->searchMode = 'exact';
$dbo->cols['js_bleeding_remark']->capContClassDefault = array();
$dbo->cols['js_bleeding_remark']->valContClassDefault = array();
$dbo->cols['js_bleeding_remark']->option->defaultMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->searchMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->listMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->detailMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->newMethod = 'text';
$dbo->cols['js_bleeding_remark']->option->editMethod = 'text';
$dbo->cols['js_carcode'] = new DBO_COL('js_carcode', 'varchar', '-1', '16');
$dbo->cols['js_carcode']->inputTypeDefault = 'select';
$dbo->cols['js_carcode']->searchMode = 'exact';
$dbo->cols['js_carcode']->capContClassDefault = array();
$dbo->cols['js_carcode']->valContClassDefault = array();
$dbo->cols['js_carcode']->option->default = 'select car_id,car_name from mcarton
order by car_name';
$dbo->cols['js_carcode']->option->defaultMethod = 'sql';
$dbo->cols['js_carcode']->option->searchMethod = 'text';
$dbo->cols['js_carcode']->option->listMethod = 'text';
$dbo->cols['js_carcode']->option->detailMethod = 'text';
$dbo->cols['js_carcode']->option->newMethod = 'text';
$dbo->cols['js_carcode']->option->editMethod = 'text';
$dbo->cols['js_distortion'] = new DBO_COL('js_distortion', 'varchar', '-1', '5');
$dbo->cols['js_distortion']->inputTypeDefault = 'select';
$dbo->cols['js_distortion']->searchMode = 'exact';
$dbo->cols['js_distortion']->capContClassDefault = array();
$dbo->cols['js_distortion']->valContClassDefault = array();
$dbo->cols['js_distortion']->option->default = 'H|Horizontal
V|Vertical';
$dbo->cols['js_distortion']->option->defaultMethod = 'text';
$dbo->cols['js_distortion']->option->searchMethod = 'text';
$dbo->cols['js_distortion']->option->listMethod = 'text';
$dbo->cols['js_distortion']->option->detailMethod = 'text';
$dbo->cols['js_distortion']->option->newMethod = 'text';
$dbo->cols['js_distortion']->option->editMethod = 'text';
$dbo->cols['js_distortion_value'] = new DBO_COL('js_distortion_value', 'numeric', '-1', '1310728');
$dbo->cols['js_distortion_value']->displayDataType = 'currency';
$dbo->cols['js_distortion_value']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['js_distortion_value']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_distortion_value']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_distortion_value']->displayDetailModifier = 'showPercentageDet';
$dbo->cols['js_distortion_value']->inputNewModifier = 'showPercentage';
$dbo->cols['js_distortion_value']->inputEditModifier = 'showPercentage';
$dbo->cols['js_distortion_value']->inputTypeDefault = 'TextInputControl';
$dbo->cols['js_distortion_value']->searchMode = 'exact';
$dbo->cols['js_distortion_value']->capContClassDefault = array();
$dbo->cols['js_distortion_value']->valContClassDefault = array();
$dbo->cols['js_distortion_value']->valContExtClassDefault = 'input-group';
$dbo->cols['js_distortion_value']->option->defaultMethod = 'text';
$dbo->cols['js_distortion_value']->option->searchMethod = 'text';
$dbo->cols['js_distortion_value']->option->listMethod = 'text';
$dbo->cols['js_distortion_value']->option->detailMethod = 'text';
$dbo->cols['js_distortion_value']->option->newMethod = 'text';
$dbo->cols['js_distortion_value']->option->editMethod = 'text';
$dbo->cols['js_diecut_ind'] = new DBO_COL('js_diecut_ind', 'varchar', '-1', '5');
$dbo->cols['js_diecut_ind']->inputTypeDefault = 'radio';
$dbo->cols['js_diecut_ind']->mandatoryDefault = 1;
$dbo->cols['js_diecut_ind']->searchMode = 'exact';
$dbo->cols['js_diecut_ind']->capContClassDefault = array();
$dbo->cols['js_diecut_ind']->valContClassDefault = array();
$dbo->cols['js_diecut_ind']->option->default = 'Y|Yes
N|No';
$dbo->cols['js_diecut_ind']->option->defaultMethod = 'text';
$dbo->cols['js_diecut_ind']->option->searchMethod = 'text';
$dbo->cols['js_diecut_ind']->option->listMethod = 'text';
$dbo->cols['js_diecut_ind']->option->detailMethod = 'text';
$dbo->cols['js_diecut_ind']->option->newMethod = 'text';
$dbo->cols['js_diecut_ind']->option->editMethod = 'text';
$dbo->cols['js_thicknessplate'] = new DBO_COL('js_thicknessplate', 'varchar', '-1', '104');
$dbo->cols['js_thicknessplate']->inputTypeDefault = 'text';
$dbo->cols['js_thicknessplate']->searchMode = 'exact';
$dbo->cols['js_thicknessplate']->capContClassDefault = array();
$dbo->cols['js_thicknessplate']->valContClassDefault = array();
$dbo->cols['js_thicknessplate']->option->defaultMethod = 'text';
$dbo->cols['js_thicknessplate']->option->searchMethod = 'text';
$dbo->cols['js_thicknessplate']->option->listMethod = 'text';
$dbo->cols['js_thicknessplate']->option->detailMethod = 'text';
$dbo->cols['js_thicknessplate']->option->newMethod = 'text';
$dbo->cols['js_thicknessplate']->option->editMethod = 'text';
$dbo->cols['js_category'] = new DBO_COL('js_category', 'varchar', '-1', '504');
$dbo->cols['js_category']->inputTypeDefault = 'checkbox';
$dbo->cols['js_category']->searchMode = 'exact';
$dbo->cols['js_category']->capContClassDefault = array();
$dbo->cols['js_category']->valContClassDefault = array();
$dbo->cols['js_category']->option->default = 'select jcl_id, jcl_title 
from mjobcatlookup
order by jcl_title';
$dbo->cols['js_category']->option->defaultMethod = 'sql';
$dbo->cols['js_category']->option->searchMethod = 'text';
$dbo->cols['js_category']->option->listMethod = 'text';
$dbo->cols['js_category']->option->detailMethod = 'text';
$dbo->cols['js_category']->option->newMethod = 'text';
$dbo->cols['js_category']->option->editMethod = 'text';
$dbo->cols['js_trapping_size'] = new DBO_COL('js_trapping_size', 'numeric', '-1', '1310728');
$dbo->cols['js_trapping_size']->displayDataType = 'currency';
$dbo->cols['js_trapping_size']->inputTypeDefault = 'TextInputControl';
$dbo->cols['js_trapping_size']->searchMode = 'exact';
$dbo->cols['js_trapping_size']->capContClassDefault = array();
$dbo->cols['js_trapping_size']->valContClassDefault = array();
$dbo->cols['js_trapping_size']->valContExtClassDefault = 'form-group';
$dbo->cols['js_trapping_size']->option->defaultMethod = 'text';
$dbo->cols['js_trapping_size']->option->searchMethod = 'text';
$dbo->cols['js_trapping_size']->option->listMethod = 'text';
$dbo->cols['js_trapping_size']->option->detailMethod = 'text';
$dbo->cols['js_trapping_size']->option->newMethod = 'text';
$dbo->cols['js_trapping_size']->option->editMethod = 'text';
$dbo->cols['js_barcodetype'] = new DBO_COL('js_barcodetype', 'varchar', '-1', '54');
$dbo->cols['js_barcodetype']->inputTypeDefault = 'select';
$dbo->cols['js_barcodetype']->searchMode = 'exact';
$dbo->cols['js_barcodetype']->capContClassDefault = array();
$dbo->cols['js_barcodetype']->valContClassDefault = array();
$dbo->cols['js_barcodetype']->option->default = 'select lu_code,lu_title from fclookup
where lu_cat = \'BARCODETYPE\'
order by lu_title';
$dbo->cols['js_barcodetype']->option->defaultMethod = 'sql';
$dbo->cols['js_barcodetype']->option->searchMethod = 'text';
$dbo->cols['js_barcodetype']->option->listMethod = 'text';
$dbo->cols['js_barcodetype']->option->detailMethod = 'text';
$dbo->cols['js_barcodetype']->option->newMethod = 'text';
$dbo->cols['js_barcodetype']->option->editMethod = 'text';
$dbo->cols['js_barcodenumber'] = new DBO_COL('js_barcodenumber', 'varchar', '-1', '104');
$dbo->cols['js_barcodenumber']->inputTypeDefault = 'text';
$dbo->cols['js_barcodenumber']->searchMode = 'exact';
$dbo->cols['js_barcodenumber']->capContClassDefault = array();
$dbo->cols['js_barcodenumber']->valContClassDefault = array();
$dbo->cols['js_barcodenumber']->option->defaultMethod = 'text';
$dbo->cols['js_barcodenumber']->option->searchMethod = 'text';
$dbo->cols['js_barcodenumber']->option->listMethod = 'text';
$dbo->cols['js_barcodenumber']->option->detailMethod = 'text';
$dbo->cols['js_barcodenumber']->option->newMethod = 'text';
$dbo->cols['js_barcodenumber']->option->editMethod = 'text';
$dbo->cols['js_primcat'] = new DBO_COL('js_primcat', 'int4', '4', '-1');
$dbo->cols['js_primcat']->inputTypeDefault = 'text';
$dbo->cols['js_primcat']->searchMode = 'exact';
$dbo->cols['js_primcat']->capContClassDefault = array();
$dbo->cols['js_primcat']->valContClassDefault = array();
$dbo->cols['js_primcat']->option->default = 'select jcl_id, jcl_title 
from mjobcatlookup
order by jcl_title';
$dbo->cols['js_primcat']->option->defaultMethod = 'sql';
$dbo->cols['js_primcat']->option->searchMethod = 'text';
$dbo->cols['js_primcat']->option->listMethod = 'text';
$dbo->cols['js_primcat']->option->detailMethod = 'text';
$dbo->cols['js_primcat']->option->newMethod = 'text';
$dbo->cols['js_primcat']->option->editMethod = 'text';
$dbo->cols['js_status'] = new DBO_COL('js_status', 'varchar', '-1', '104');
$dbo->cols['js_status']->inputTypeDefault = 'text';
$dbo->cols['js_status']->searchMode = 'exact';
$dbo->cols['js_status']->capContClassDefault = array();
$dbo->cols['js_status']->valContClassDefault = array();
$dbo->cols['js_status']->option->defaultMethod = 'text';
$dbo->cols['js_status']->option->searchMethod = 'text';
$dbo->cols['js_status']->option->listMethod = 'text';
$dbo->cols['js_status']->option->detailMethod = 'text';
$dbo->cols['js_status']->option->newMethod = 'text';
$dbo->cols['js_status']->option->editMethod = 'text';
$dbo->cols['js_completiondate'] = new DBO_COL('js_completiondate', 'timestamptz', '8', '-1');
$dbo->cols['js_completiondate']->inputTypeDefault = 'text';
$dbo->cols['js_completiondate']->searchMode = 'exact';
$dbo->cols['js_completiondate']->capContClassDefault = array();
$dbo->cols['js_completiondate']->valContClassDefault = array();
$dbo->cols['js_completiondate']->option->defaultMethod = 'text';
$dbo->cols['js_completiondate']->option->searchMethod = 'text';
$dbo->cols['js_completiondate']->option->listMethod = 'text';
$dbo->cols['js_completiondate']->option->detailMethod = 'text';
$dbo->cols['js_completiondate']->option->newMethod = 'text';
$dbo->cols['js_completiondate']->option->editMethod = 'text';
$dbo->cols['js_assignto'] = new DBO_COL('js_assignto', 'varchar', '-1', '54');
$dbo->cols['js_assignto']->inputTypeDefault = 'text';
$dbo->cols['js_assignto']->searchMode = 'exact';
$dbo->cols['js_assignto']->capContClassDefault = array();
$dbo->cols['js_assignto']->valContClassDefault = array();
$dbo->cols['js_assignto']->option->defaultMethod = 'text';
$dbo->cols['js_assignto']->option->searchMethod = 'text';
$dbo->cols['js_assignto']->option->listMethod = 'text';
$dbo->cols['js_assignto']->option->detailMethod = 'text';
$dbo->cols['js_assignto']->option->newMethod = 'text';
$dbo->cols['js_assignto']->option->editMethod = 'text';
$dbo->cols['js_refid'] = new DBO_COL('js_refid', 'int4', '4', '-1');
$dbo->cols['js_refid']->inputTypeDefault = 'text';
$dbo->cols['js_refid']->searchMode = 'exact';
$dbo->cols['js_refid']->capContClassDefault = array();
$dbo->cols['js_refid']->valContClassDefault = array();
$dbo->cols['js_refid']->option->defaultMethod = 'text';
$dbo->cols['js_refid']->option->searchMethod = 'text';
$dbo->cols['js_refid']->option->listMethod = 'text';
$dbo->cols['js_refid']->option->detailMethod = 'text';
$dbo->cols['js_refid']->option->newMethod = 'text';
$dbo->cols['js_refid']->option->editMethod = 'text';
$dbo->cols['attachment'] = new DBO_COL('attachment', 'unknown', '-2', '-1');
$dbo->cols['attachment']->inputTypeDefault = 'Dropzone';
$dbo->cols['attachment']->size = '10M/5';
$dbo->cols['attachment']->format = '.zip, .rar';
$dbo->cols['attachment']->mandatoryNew = 1;
$dbo->cols['attachment']->searchMode = 'exact';
$dbo->cols['attachment']->capContClassDefault = array();
$dbo->cols['attachment']->valContClassDefault = array();
$dbo->cols['attachment']->option->defaultMethod = 'text';
$dbo->cols['attachment']->option->searchMethod = 'text';
$dbo->cols['attachment']->option->listMethod = 'text';
$dbo->cols['attachment']->option->detailMethod = 'text';
$dbo->cols['attachment']->option->newMethod = 'text';
$dbo->cols['attachment']->option->editMethod = 'text';
$dbo->cols['remark'] = new DBO_COL('remark', 'unknown', '-2', '-1');
$dbo->cols['remark']->inputTypeDefault = 'TextareaAutosize';
$dbo->cols['remark']->size = 3;
$dbo->cols['remark']->searchMode = 'exact';
$dbo->cols['remark']->capContClassDefault = array();
$dbo->cols['remark']->valContClassDefault = array();
$dbo->cols['remark']->option->defaultMethod = 'text';
$dbo->cols['remark']->option->searchMethod = 'text';
$dbo->cols['remark']->option->listMethod = 'text';
$dbo->cols['remark']->option->detailMethod = 'text';
$dbo->cols['remark']->option->newMethod = 'text';
$dbo->cols['remark']->option->editMethod = 'text';
$dbo->cols['js_orgid'] = new DBO_COL('js_orgid', 'int4', '4', '-1');
$dbo->cols['js_orgid']->inputTypeDefault = 'select';
$dbo->cols['js_orgid']->searchMode = 'exact';
$dbo->cols['js_orgid']->capContClassDefault = array();
$dbo->cols['js_orgid']->valContClassDefault = array();
$dbo->cols['js_orgid']->option->defaultMethod = 'text';
$dbo->cols['js_orgid']->option->searchMethod = 'text';
$dbo->cols['js_orgid']->option->listMethod = 'text';
$dbo->cols['js_orgid']->option->detailMethod = 'text';
$dbo->cols['js_orgid']->option->newMethod = 'text';
$dbo->cols['js_orgid']->option->editMethod = 'text';
$dbo->cols['js_model'] = new DBO_COL('js_model', 'varchar', '-1', '2004');
$dbo->cols['js_model']->inputTypeDefault = 'text';
$dbo->cols['js_model']->searchMode = 'exact';
$dbo->cols['js_model']->capContClassDefault = array();
$dbo->cols['js_model']->valContClassDefault = array();
$dbo->cols['js_model']->option->defaultMethod = 'text';
$dbo->cols['js_model']->option->searchMethod = 'text';
$dbo->cols['js_model']->option->listMethod = 'text';
$dbo->cols['js_model']->option->detailMethod = 'text';
$dbo->cols['js_model']->option->newMethod = 'text';
$dbo->cols['js_model']->option->editMethod = 'text';
$dbo->cols['js_diecut_no'] = new DBO_COL('js_diecut_no', 'varchar', '-1', '104');
$dbo->cols['js_diecut_no']->inputTypeDefault = 'radio';
$dbo->cols['js_diecut_no']->searchMode = 'exact';
$dbo->cols['js_diecut_no']->capContClassDefault = array();
$dbo->cols['js_diecut_no']->valContClassDefault = array();
$dbo->cols['js_diecut_no']->option->defaultMethod = 'text';
$dbo->cols['js_diecut_no']->option->searchMethod = 'text';
$dbo->cols['js_diecut_no']->option->listMethod = 'text';
$dbo->cols['js_diecut_no']->option->detailMethod = 'text';
$dbo->cols['js_diecut_no']->option->newMethod = 'text';
$dbo->cols['js_diecut_no']->option->editMethod = 'text';
$dbo->cols['info'] = new DBO_COL('info', 'unknown', '-2', '-1');
$dbo->cols['info']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['info']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['info']->inputNewModifier = 'showinfo';
$dbo->cols['info']->inputEditModifier = 'showinfo';
$dbo->cols['info']->inputTypeDefault = 'text';
$dbo->cols['info']->searchMode = 'exact';
$dbo->cols['info']->capContClassDefault = array();
$dbo->cols['info']->valContClassDefault = array();
$dbo->cols['info']->option->defaultMethod = 'text';
$dbo->cols['info']->option->searchMethod = 'text';
$dbo->cols['info']->option->listMethod = 'text';
$dbo->cols['info']->option->detailMethod = 'text';
$dbo->cols['info']->option->newMethod = 'text';
$dbo->cols['info']->option->editMethod = 'text';
$dbo->cols['js_carid'] = new DBO_COL('js_carid', 'int4', '4', '-1');
$dbo->cols['js_carid']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['js_carid']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_carid']->displayDetailModifier = 'displayCartonDetail';
$dbo->cols['js_carid']->inputEditModifier = 'displayCartonEdit';
$dbo->cols['js_carid']->inputTypeDefault = 'select';
$dbo->cols['js_carid']->mandatoryDefault = 1;
$dbo->cols['js_carid']->searchMode = 'exact';
$dbo->cols['js_carid']->capContClassDefault = array();
$dbo->cols['js_carid']->valContClassDefault = array();
$dbo->cols['js_carid']->option->default = 'select car_id,car_name from mcarton
order by car_name';
$dbo->cols['js_carid']->option->defaultMethod = 'sql';
$dbo->cols['js_carid']->option->searchMethod = 'text';
$dbo->cols['js_carid']->option->listMethod = 'text';
$dbo->cols['js_carid']->option->detailMethod = 'text';
$dbo->cols['js_carid']->option->newMethod = 'text';
$dbo->cols['js_carid']->option->editMethod = 'text';
$dbo->cols['jobcategory'] = new DBO_COL('jobcategory', 'varchar', '-1', '-1');
$dbo->cols['jobcategory']->inputTypeDefault = 'PixelAdminCheckboxInline';
$dbo->cols['jobcategory']->searchMode = 'exact';
$dbo->cols['jobcategory']->capContClassDefault = array();
$dbo->cols['jobcategory']->valContClassDefault = array();
$dbo->cols['jobcategory']->option->default = 'select jcl_id, jcl_title 
from mjobcatlookup
order by jcl_title';
$dbo->cols['jobcategory']->option->new = 'select jcl_id, jcl_title 
from mjobcatlookup where jcl_status = \'ACTIVE\'
order by jcl_title';
$dbo->cols['jobcategory']->option->edit = 'select jcl_id, jcl_title 
from mjobcatlookup where jcl_status = \'ACTIVE\'
order by jcl_title';
$dbo->cols['jobcategory']->option->defaultMethod = 'sql';
$dbo->cols['jobcategory']->option->searchMethod = 'text';
$dbo->cols['jobcategory']->option->listMethod = 'text';
$dbo->cols['jobcategory']->option->detailMethod = 'text';
$dbo->cols['jobcategory']->option->newMethod = 'sql';
$dbo->cols['jobcategory']->option->editMethod = 'sql';
$dbo->cols['js_decision'] = new DBO_COL('js_decision', 'varchar', '-1', '54');
$dbo->cols['js_decision']->inputTypeDefault = 'text';
$dbo->cols['js_decision']->searchMode = 'exact';
$dbo->cols['js_decision']->capContClassDefault = array();
$dbo->cols['js_decision']->valContClassDefault = array();
$dbo->cols['js_decision']->option->defaultMethod = 'text';
$dbo->cols['js_decision']->option->searchMethod = 'text';
$dbo->cols['js_decision']->option->listMethod = 'text';
$dbo->cols['js_decision']->option->detailMethod = 'text';
$dbo->cols['js_decision']->option->newMethod = 'text';
$dbo->cols['js_decision']->option->editMethod = 'text';
$dbo->cols['js_width'] = new DBO_COL('js_width', 'varchar', '-1', '54');
$dbo->cols['js_width']->inputTypeDefault = 'text';
$dbo->cols['js_width']->searchMode = 'exact';
$dbo->cols['js_width']->capContClassDefault = array();
$dbo->cols['js_width']->valContClassDefault = array();
$dbo->cols['js_width']->option->defaultMethod = 'text';
$dbo->cols['js_width']->option->searchMethod = 'text';
$dbo->cols['js_width']->option->listMethod = 'text';
$dbo->cols['js_width']->option->detailMethod = 'text';
$dbo->cols['js_width']->option->newMethod = 'text';
$dbo->cols['js_width']->option->editMethod = 'text';
$dbo->cols['js_height'] = new DBO_COL('js_height', 'varchar', '-1', '54');
$dbo->cols['js_height']->inputTypeDefault = 'text';
$dbo->cols['js_height']->searchMode = 'exact';
$dbo->cols['js_height']->capContClassDefault = array();
$dbo->cols['js_height']->valContClassDefault = array();
$dbo->cols['js_height']->option->defaultMethod = 'text';
$dbo->cols['js_height']->option->searchMethod = 'text';
$dbo->cols['js_height']->option->listMethod = 'text';
$dbo->cols['js_height']->option->detailMethod = 'text';
$dbo->cols['js_height']->option->newMethod = 'text';
$dbo->cols['js_height']->option->editMethod = 'text';
$dbo->cols['js_manrequiretime'] = new DBO_COL('js_manrequiretime', 'int4', '4', '-1');
$dbo->cols['js_manrequiretime']->inputTypeDefault = 'text';
$dbo->cols['js_manrequiretime']->searchMode = 'exact';
$dbo->cols['js_manrequiretime']->capContClassDefault = array();
$dbo->cols['js_manrequiretime']->valContClassDefault = array();
$dbo->cols['js_manrequiretime']->option->defaultMethod = 'text';
$dbo->cols['js_manrequiretime']->option->searchMethod = 'text';
$dbo->cols['js_manrequiretime']->option->listMethod = 'text';
$dbo->cols['js_manrequiretime']->option->detailMethod = 'text';
$dbo->cols['js_manrequiretime']->option->newMethod = 'text';
$dbo->cols['js_manrequiretime']->option->editMethod = 'text';
$dbo->cols['js_requiretime'] = new DBO_COL('js_requiretime', 'int4', '4', '-1');
$dbo->cols['js_requiretime']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_requiretime']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_requiretime']->inputNewModifier = 'showRequiredMinute';
$dbo->cols['js_requiretime']->inputEditModifier = 'showRequiredMinute';
$dbo->cols['js_requiretime']->inputTypeDefault = 'text';
$dbo->cols['js_requiretime']->searchMode = 'exact';
$dbo->cols['js_requiretime']->capContClassDefault = array();
$dbo->cols['js_requiretime']->valContClassDefault = array();
$dbo->cols['js_requiretime']->option->defaultMethod = 'text';
$dbo->cols['js_requiretime']->option->searchMethod = 'text';
$dbo->cols['js_requiretime']->option->listMethod = 'text';
$dbo->cols['js_requiretime']->option->detailMethod = 'text';
$dbo->cols['js_requiretime']->option->newMethod = 'text';
$dbo->cols['js_requiretime']->option->editMethod = 'text';
$dbo->cols['filehistory'] = new DBO_COL('filehistory', 'unknown', '-2', '-1');
$dbo->cols['filehistory']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['filehistory']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['filehistory']->displayDetailModifier = 'showFileHistory';
$dbo->cols['filehistory']->inputEditModifier = 'showFileHistory';
$dbo->cols['filehistory']->inputTypeDefault = 'text';
$dbo->cols['filehistory']->searchMode = 'exact';
$dbo->cols['filehistory']->capContClassDefault = array();
$dbo->cols['filehistory']->valContClassDefault = array();
$dbo->cols['filehistory']->option->defaultMethod = 'text';
$dbo->cols['filehistory']->option->searchMethod = 'text';
$dbo->cols['filehistory']->option->listMethod = 'text';
$dbo->cols['filehistory']->option->detailMethod = 'text';
$dbo->cols['filehistory']->option->newMethod = 'text';
$dbo->cols['filehistory']->option->editMethod = 'text';
$dbo->cols['js_request_dateinmth'] = new DBO_COL('js_request_dateinmth', 'varchar', '-1', '54');
$dbo->cols['js_request_dateinmth']->inputTypeDefault = 'text';
$dbo->cols['js_request_dateinmth']->searchMode = 'exact';
$dbo->cols['js_request_dateinmth']->capContClassDefault = array();
$dbo->cols['js_request_dateinmth']->valContClassDefault = array();
$dbo->cols['js_request_dateinmth']->option->defaultMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->searchMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->listMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->detailMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->newMethod = 'text';
$dbo->cols['js_request_dateinmth']->option->editMethod = 'text';
$dbo->cols['js_jobcolor'] = new DBO_COL('js_jobcolor', 'varchar', '-1', '54');
$dbo->cols['js_jobcolor']->inputTypeDefault = 'radio';
$dbo->cols['js_jobcolor']->mandatoryDefault = 1;
$dbo->cols['js_jobcolor']->searchMode = 'exact';
$dbo->cols['js_jobcolor']->capContClassDefault = array();
$dbo->cols['js_jobcolor']->valContClassDefault = array();
$dbo->cols['js_jobcolor']->option->default = '1
2
3
4';
$dbo->cols['js_jobcolor']->option->defaultMethod = 'text';
$dbo->cols['js_jobcolor']->option->searchMethod = 'text';
$dbo->cols['js_jobcolor']->option->listMethod = 'text';
$dbo->cols['js_jobcolor']->option->detailMethod = 'text';
$dbo->cols['js_jobcolor']->option->newMethod = 'text';
$dbo->cols['js_jobcolor']->option->editMethod = 'text';
$dbo->cols['joboutput'] = new DBO_COL('joboutput', 'varchar', '-1', '-1');
$dbo->cols['joboutput']->inputTypeDefault = 'PixelAdminCheckboxInline';
$dbo->cols['joboutput']->searchMode = 'exact';
$dbo->cols['joboutput']->capContClassDefault = array();
$dbo->cols['joboutput']->valContClassDefault = array();
$dbo->cols['joboutput']->option->default = 'select jol_id,jol_title from mjoboutputlookup order by jol_title';
$dbo->cols['joboutput']->option->new = 'select jol_id,jol_title from mjoboutputlookup where jol_status = \'ACTIVE\' order by jol_title';
$dbo->cols['joboutput']->option->edit = 'select jol_id,jol_title from mjoboutputlookup where jol_status = \'ACTIVE\' order by jol_title';
$dbo->cols['joboutput']->option->defaultMethod = 'sql';
$dbo->cols['joboutput']->option->searchMethod = 'text';
$dbo->cols['joboutput']->option->listMethod = 'text';
$dbo->cols['joboutput']->option->detailMethod = 'text';
$dbo->cols['joboutput']->option->newMethod = 'sql';
$dbo->cols['joboutput']->option->editMethod = 'sql';
$dbo->cols['js_lpi'] = new DBO_COL('js_lpi', 'int4', '4', '-1');
$dbo->cols['js_lpi']->displayDataType = 'int';
$dbo->cols['js_lpi']->inputTypeDefault = 'TextInputControl';
$dbo->cols['js_lpi']->size = 5;
$dbo->cols['js_lpi']->searchMode = 'exact';
$dbo->cols['js_lpi']->capContClassDefault = array();
$dbo->cols['js_lpi']->valContClassDefault = array();
$dbo->cols['js_lpi']->valContExtClassDefault = 'form-group';
$dbo->cols['js_lpi']->option->defaultMethod = 'text';
$dbo->cols['js_lpi']->option->searchMethod = 'text';
$dbo->cols['js_lpi']->option->listMethod = 'text';
$dbo->cols['js_lpi']->option->detailMethod = 'text';
$dbo->cols['js_lpi']->option->newMethod = 'text';
$dbo->cols['js_lpi']->option->editMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__'] = new DBO_COL('__map_mjobbarcode__jbc_jsid__', 'int4', '4', '-1');
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->displayDetailModifierMethod = 'phpfunc';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->displayDetailModifier = 'genDetailTableDisplay';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputNewModifier = 'genDetailTableInput';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputEditModifier = 'genDetailTableInput';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->inputTypeDefault = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->mandatoryDefault = 1;
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->searchMode = 'exact';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->capContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->valContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->defaultMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->searchMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->listMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->detailMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->newMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_jsid__']->option->editMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_btcode__'] = new DBO_COL('__map_mjobbarcode__jbc_btcode__', 'unknown', '-2', '-1');
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->inputTypeDefault = 'select';
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->mandatoryDefault = 1;
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->searchMode = 'exact';
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->capContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->valContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->option->default = 'select bt_code, bt_name from mbarcodetype order by 2';
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->option->defaultMethod = 'sql';
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->option->searchMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->option->listMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->option->detailMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->option->newMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_btcode__']->option->editMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__'] = new DBO_COL('__map_mjobbarcode__jbc_value__', 'unknown', '-2', '-1');
$dbo->cols['__map_mjobbarcode__jbc_value__']->inputTypeDefault = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->mandatoryDefault = 1;
$dbo->cols['__map_mjobbarcode__jbc_value__']->searchMode = 'exact';
$dbo->cols['__map_mjobbarcode__jbc_value__']->capContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_value__']->valContClassDefault = array();
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->defaultMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->searchMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->listMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->detailMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->newMethod = 'text';
$dbo->cols['__map_mjobbarcode__jbc_value__']->option->editMethod = 'text';
$dbo->cols['js_mcid'] = new DBO_COL('js_mcid', 'int4', '4', '-1');
$dbo->cols['js_mcid']->inputTypeDefault = 'select';
$dbo->cols['js_mcid']->searchMode = 'exact';
$dbo->cols['js_mcid']->capContClassDefault = array();
$dbo->cols['js_mcid']->valContClassDefault = array();
$dbo->cols['js_mcid']->option->default = 'select mc_id, mc_printer_name, org_name from mcustmachine join fcorg on mc_orgid = org_id order by 3,2';
$dbo->cols['js_mcid']->option->new = 'select mc_id, mc_printer_name, org_name from mcustmachine join fcorg on mc_orgid = org_id order by 3,2';
$dbo->cols['js_mcid']->option->edit = 'select mc_id, mc_printer_name, org_name from mcustmachine join fcorg on mc_orgid = org_id order by 3,2';
$dbo->cols['js_mcid']->option->defaultMethod = 'sql';
$dbo->cols['js_mcid']->option->searchMethod = 'text';
$dbo->cols['js_mcid']->option->listMethod = 'text';
$dbo->cols['js_mcid']->option->detailMethod = 'text';
$dbo->cols['js_mcid']->option->newMethod = 'sql';
$dbo->cols['js_mcid']->option->editMethod = 'sql';
$dbo->cols['js_code'] = new DBO_COL('js_code', 'varchar', '-1', '36');
$dbo->cols['js_code']->inputTypeDefault = 'text';
$dbo->cols['js_code']->searchMode = 'exact';
$dbo->cols['js_code']->capContClassDefault = array();
$dbo->cols['js_code']->valContClassDefault = array();
$dbo->cols['js_code']->option->defaultMethod = 'text';
$dbo->cols['js_code']->option->searchMethod = 'text';
$dbo->cols['js_code']->option->listMethod = 'text';
$dbo->cols['js_code']->option->detailMethod = 'text';
$dbo->cols['js_code']->option->newMethod = 'text';
$dbo->cols['js_code']->option->editMethod = 'text';
$dbo->cols['js_month_occur'] = new DBO_COL('js_month_occur', 'int4', '4', '-1');
$dbo->cols['js_month_occur']->inputTypeDefault = 'text';
$dbo->cols['js_month_occur']->searchMode = 'exact';
$dbo->cols['js_month_occur']->capContClassDefault = array();
$dbo->cols['js_month_occur']->valContClassDefault = array();
$dbo->cols['js_month_occur']->option->defaultMethod = 'text';
$dbo->cols['js_month_occur']->option->searchMethod = 'text';
$dbo->cols['js_month_occur']->option->listMethod = 'text';
$dbo->cols['js_month_occur']->option->detailMethod = 'text';
$dbo->cols['js_month_occur']->option->newMethod = 'text';
$dbo->cols['js_month_occur']->option->editMethod = 'text';
$dbo->cols['js_price'] = new DBO_COL('js_price', 'numeric', '-1', '1310728');
$dbo->cols['js_price']->inputNewModifierMethod = 'phpfunc';
$dbo->cols['js_price']->inputEditModifierMethod = 'phpfunc';
$dbo->cols['js_price']->inputNewModifier = 'showPrice';
$dbo->cols['js_price']->inputEditModifier = 'showPrice';
$dbo->cols['js_price']->inputTypeDefault = 'text';
$dbo->cols['js_price']->attributeDefault = array('readonly'=>array('readonly'));
$dbo->cols['js_price']->searchMode = 'exact';
$dbo->cols['js_price']->capContClassDefault = array();
$dbo->cols['js_price']->valContClassDefault = array();
$dbo->cols['js_price']->option->defaultMethod = 'text';
$dbo->cols['js_price']->option->searchMethod = 'text';
$dbo->cols['js_price']->option->listMethod = 'text';
$dbo->cols['js_price']->option->detailMethod = 'text';
$dbo->cols['js_price']->option->newMethod = 'text';
$dbo->cols['js_price']->option->editMethod = 'text';
$dbo->cols['pmc_id'] = new DBO_COL('pmc_id', 'int4', '4', '-1');
$dbo->cols['pmc_id']->inputTypeDefault = 'text';
$dbo->cols['pmc_id']->searchMode = 'exact';
$dbo->cols['pmc_id']->capContClassDefault = array();
$dbo->cols['pmc_id']->valContClassDefault = array();
$dbo->cols['pmc_id']->option->defaultMethod = 'text';
$dbo->cols['pmc_id']->option->searchMethod = 'text';
$dbo->cols['pmc_id']->option->listMethod = 'text';
$dbo->cols['pmc_id']->option->detailMethod = 'text';
$dbo->cols['pmc_id']->option->newMethod = 'text';
$dbo->cols['pmc_id']->option->editMethod = 'text';

// support multiple language. only caption
global $LANG;
if(file_exists(dirname(__FILE__).DIRECTORY_SEPARATOR.$dbo->id.'.conf.lang.'.$LANG.'.php')){
	require(dirname(__FILE__).DIRECTORY_SEPARATOR.$dbo->id.'.conf.lang.'.$LANG.'.php');
}else if($availang = glob(dirname(__FILE__).DIRECTORY_SEPARATOR.$dboID.'.conf.lang.*')){
	require($availang[0]);
}

// for DBO Builder
$dbo->saveDir = dirname(dirname(__FILE__));

$dbo->run();

/*
$dbo->newModifier = 'dbo_jobsheet_custom_new';
function dbo_jobsheet_custom_new($table, $cols){
	global $DB;
	$ret = array();
	$ok = $DB->doInsert($table, $cols);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

$dbo->editModifier = 'dbo_jobsheet_custom_edit';
function dbo_jobsheet_custom_edit($table, $cols, $wheres){
	global $DB;
	$ret = array();
	$ok = $DB->doUpdate($table, $cols, $wheres);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

$dbo->searchModifier = 'dbo_jobsheet_custom_search';
function dbo_jobsheet_custom_search(&$search){
}

$dbo->deleteModifier = 'dbo_jobsheet_custom_delete';
function dbo_jobsheet_custom_delete($table, $wheres){
	global $DB;
	$ret = array();
	$ok = $DB->doDelete($table, $wheres);
	if(!$ok){
		$ret[] = $DB->lastError;
	}
	return $ret;
}

function dbo_jobsheet_display_modifier($col, $colVal, $data=array(), $html=null){
}
*/
?>